### ISSUE TITLE
Custom resolver receives already-resolved $ref

### ISSUE THREAD

**Issue by germanschnyder** [stoplightio/spectral#1033]
When implementing a custom resolver I get the $ref already resolved instead of the value expressed in the openapi file.

**To Reproduce**

Implement example custom resolver:

```
module.exports = new Resolver({
  resolvers: {
    file: {
      resolve(ref) {
        console.log(ref.path()) <-- this will output the full path of the $ref content
     }
    }
  }
}
```

**Expected behavior**
Receive the exact value specified in the $ref field (for example, mydir/myfile.yml) instead of the resolved full path (that may not exist and I'm trying to fix)

**Environment (remove any that are not applicable):**
 - Library version: 5.2.0
 - OS: Ubuntu

**Comment by nulltoken** [comment]
@germanschnyder In order to help understand your context, could you please provide a simple end-to-end repro case?

**Comment by germanschnyder** [comment]
Sure. 
Here the mail file:

```
openapi: 3.0.2
info:
  title: Test
  version: 0.1.1
  contact:
    name: My Name
  description: api description
servers:
  - url: 'http://localhost'
    description: To be replaced
tags:
 - name: apis
   description: These are api operations
paths:
  /api-management/apis:
    $ref: 'paths/apis.yml'
```

Here the apis.yml (goes inside `paths` folder)

```
post:
  summary: Create a new API definition
  operationId: api-create
  responses:
    '201':
      description: Created
      headers:
        Location:
          schema:
            type: string
          description: Resource location
          required: true
    '400':
      description: Bad Request
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
  requestBody:
    content:
      application/json:
        schema:
          $ref: 'model/api.yml'    
        examples: {}
    description: API Definition
  tags:
    - apis
  description: Creates a new API definition
parameters: []

```

And here the api.yml (goes inside `model` folder)

```
type: object
description: This model represent an API
properties:
  id:
    type: string
    format: uuid

  name:
    type: string    
```

And then you have the custom resolver

```
const path = require('path');
const fs = require('fs');

const { Spectral } = require("@stoplight/spectral");
const { Resolver } = require("@stoplight/json-ref-resolver");


module.exports = new Resolver({
  resolvers: {
    file: {
      resolve(ref) {
         return new Promise((resolve, reject) => {
          const basePath = process.cwd();
          const refPath = ref.path();
          console.log("RefPath: " + refPath);
          fs.readFile(path.join(basePath, refPath), 'utf8', (err, data) => {
            if (err) {
              reject(err);
            } else {
              resolve(data);
            }
          });
        });
 
      }
    }
  }
});

```

Then if you try `spectral lint root.yml --resolver resolver.js` you get the log with the full path to the file already resolver instead of the content of the $ref field.

```bash
RefPath: /home/User/examples/paths/model/api.yml

error  invalid-ref  ENOENT: no such file or directory, open '/home/User/examples/paths/model/api.yml'
```

I was expecting to get `model/api.yml` in there so i can effectively run my own resolving logic.

**Comment by nulltoken** [comment]
@germanschnyder :wave:

⚠️ Full disclosure: I'm not deeply versed with resolvers. However, I've been burnt a bit once or twice by them.

The [doco](https://github.com/stoplightio/json-ref-resolver#usage) states:

- Resolver constructor accepts some `IResolverOpts` that are _`"used on every resolve call for this resolver instance"`_.
- Among those options exist `dereferenceInline` and `dereferenceRemote` that contribute to control the resolving behavior (both are, by default, set to `true`).
- The `resolve()` method also accepts some options that will override the ones specified at the constructor level. However, Spectral [doesn't seem](https://github.com/stoplightio/spectral/blob/develop/src/documentInventory.ts#L56-L58) to override `dereferenceInline` nor `dereferenceRemote` settings.

So, it's possible that tweaking your resolver as proposed below may help you forward:

```
module.exports = new Resolver({
  dereferenceInline: false,  // not sure overriding this setting is _required_ in your use case. 
  dereferenceRemote: false,
  resolvers: {
     (...snipped...)
  }
});
```

**Comment by nulltoken** [comment]
@germanschnyder Scratch the last comment. Setting those settings to false won't actually solve your issue.

After carefully re-reading your initial request, it looks like you might rather be interested in hooking higher into the resolving process, and that might require overriding other methods.

```
  /**
   * Hook to customize which properties are resolved.
   *
   * By default, only `$ref` keys are considered and processed.
   *
   * If defined, this hook is called for every single property in source, so it should be performant!
   *
   * It should return the string to be resolved, or nothing to skip.
   *
   * Note, this overrides the default behavior. If you would like to preserve that, call the exported `defaultGetRef`
   * as part of your custom `getRef` function.
   */
  getRef?: (key: string, val: any) => string | void;

  /**
   * Hook to transform the final ref value before it is resolved.
   *
   * It should return a URI object to change the value being resolved, or void to make no changes.
   */
  transformRef?: (opts: IRefTransformer, ctx: any) => uri.URI | void;
```

**Comment by nulltoken** [comment]
@germanschnyder 

>I was expecting to get model/api.yml in there so i can effectively run my own resolving logic.

Could you please further describe what you're trying to achieve?

**Comment by germanschnyder** [comment]
Well, I need to resolve all the refs relative to the main file. And the example in the docs doesn't work as expected.

**Comment by nulltoken** [comment]
>Well, I need to resolve all the refs relative to the main file. And the example in the docs doesn't work as expected.

@germanschnyder Clear.

However, you shouldn't need a custom resolver for that.

When I run Spectral against the sample you've provided, here's what I get.

```
PS C:\spectral> npx @stoplight/spectral@5.2.0 lint --verbose --fail-severity=hint root.yml
Found 54 rules (43 enabled)
Linting c:/spectral/root.yml
OpenAPI 3.x detected
No results with a severity of 'hint' or higher found!
```

if I drop the `operationId` from file `apis.yml` and run the same command again:

```
PS C:\spectral> npx @stoplight/spectral@5.2.0 lint --verbose --fail-severity=hint root.yml
Found 54 rules (43 enabled)
Linting c:/spectral/root.yml
OpenAPI 3.x detected

c:/spectral/paths/apis.yml
 1:6  warning  operation-operationId  Operation should have an `operationId`.

✖ 1 problem (0 errors, 1 warning, 0 infos, 0 hints)
```

You'll notice the error originates from the `apis.yml` (which has been properly resolved from the `root.yml` file)

What's the output of this command against the repro case in your context (with and without the `operationId`)?

**Comment by germanschnyder** [comment]
```bash
➜  example tree
.
├── deep.yml
├── model
│   └── api.yml
├── paths
│   └── apis.yml
└── resolver
    └── itx-resolver.js

3 directories, 4 files
➜  example spectral lint deep.yml
OpenAPI 3.x detected

/home/german/example/paths/apis.yml
 1:1  error  invalid-ref  ENOENT: no such file or directory, open '/home/german/example/paths/model/api.yml'

✖ 1 problem (1 error, 0 warnings, 0 infos, 0 hints)
```

**Comment by nulltoken** [comment]
@germanschnyder Oh, I think I've got it now.

my layout is different:

```
├── deep.yml
└── paths 
    ├── apis.yml
    └── model
        └── api.yml
```

Which explains why it works on my box.

References in `apis.yml` look for a `model` folder next to this file.

Would you want to have the `model` folder sitting next to the `paths` one, you'd have to update the refs in `apis.yaml` so that they escape of the current directory (eg. `$ref: '../model/api.yml'`)

**Comment by germanschnyder** [comment]
Well, that's the whole thing right ? 
I have a particular scenario where i need to resolve all the refs relative to the root :) 
There is an [enhancement in spectral that was supposed to do that](https://github.com/stoplightio/spectral/issues/717) but doesn't work as I expected.

 I was expecting the custom resolver feature to allow me to custom resolve my files.

**Comment by nulltoken** [comment]
>I have a particular scenario where i need to resolve all the refs relative to the root :)

@germanschnyder the scope of what you're trying to achieve is now so much clearer ;-)

However, I'm slightly puzzled as to why you'd have to have a physical layout that doesn't match the logical references. Could you please share a little bit more about the constraints of your context?

Below a little something that should get you started on this path. It relies on a `transformRef` hook that allows you to dynamically patch each reference.

```
npx @stoplight/spectral@5.2.0 lint root.yml --resolver resolver.js
```

works on my machine with the following setup

```
├── resolver.js
├── root.yml
├── model
│   └── api.yml
└── paths
    └── apis.yml (operationId being dropped)
```

**resolver.js**:

```
const path = require('path');
const fs = require('fs');
const URI = require('urijs');

const { Resolver } = require("@stoplight/json-ref-resolver");

// base location against which every remote relative file ref should be retrieved from
const baseUri = __dirname; // Feel free to change it according to your needs/setup/location of your resolver file.

module.exports = new Resolver({
  transformRef: (opts, ctx) => {
    // /!\ Warning. Hacky code. Not production ready.
    // Doesn't consider all the possible $ref values (different schemes, absolute paths, ...)
    if (opts.val.$ref && !String(opts.val.$ref).startsWith("#")) {
      const transformed = URI(path.join(baseUri, opts.val.$ref))
      return transformed;
    }
    return opts.ref;
  },
  resolvers: {
    file: {
      resolve(ref, ctx) {
        return new Promise((resolve, reject) => {
          const refPath = ref.toString();
          console.log("file RefPath: " + refPath);
          fs.readFile(refPath, 'utf8', (err, data) => {
            if (err) {
              reject(err);
            } else {
              resolve(data);
            }
          });
        });
      }
    }
  }
});
```

Beware that Spectral might not be completely ready yet to cope with refs transformations. In the file below the name of the offending file is "undefined" (cc @P0lip)

```
PS C:\spectral> npx @stoplight/spectral@5.2.0 lint root.yml --resolver resolver.js
file RefPath: c:\spectral\paths\apis.yml
file RefPath: c:\spectral\model\api.yml
OpenAPI 3.x detected

undefined
 15:24  warning  operation-operationId  Operation should have an `operationId`.
```

**Comment by germanschnyder** [comment]
There's a bug on the openapi generator that my team is  using on the java projects that needs all the refs to be relative to the main file so it properly generate the classes. I was expecting to use this custom resolver thing to provide a temporary solution until then.

Will consider your hack and give it a try to see if i can get it to work. DIdn't notice that i was able to modify the 'transformRef' logic tough. That is the kind of behavior i was expecting to override in the resolver.resolver(..) override.

**Comment by nulltoken** [comment]
@germanschnyder 

I managed to get rid of the `undefined` thingie by normalizing the path. It now properly returns the proper path.

```
PS C:\spectral> npx @stoplight/spectral@5.2.0 lint root.yml --resolver resolver.js
file RefPath: c:/spectral/paths/apis.yml
file RefPath: c:/spectral/model/api.yml
OpenAPI 3.x detected

c:/spectral/paths/apis.yml
 1:6  warning  operation-operationId  Operation should have an `operationId`.

✖ 1 problem (0 errors, 1 warning, 0 infos, 0 hints)
```


**resolver.js**:

```
const path = require('path');
const fs = require('fs');
const URI = require('urijs');
const normalize = require('@stoplight/path').normalize;

const { Resolver } = require("@stoplight/json-ref-resolver");

// base location against which every remote relative file ref should be retrieved from
const baseUri = __dirname;

module.exports = new Resolver({
  baseUri,
  transformRef: (opts, ctx) => {
    // /!\ Warning. Hacky code. Not production ready.
    // Doesn't consider all the possible $ref values (different schemes, absolute paths, ...)
    if (opts.val.$ref && !String(opts.val.$ref).startsWith("#")) {
      const transformed = URI(normalize(path.join(baseUri, opts.val.$ref)))
      return transformed;
    }
    return opts.ref;
  },
  resolvers: {
    file: {
      resolve(ref, ctx) {
        return new Promise((resolve, reject) => {
          const refPath = ref.toString();
          console.log("file RefPath: " + refPath);
          fs.readFile(refPath, 'utf8', (err, data) => {
            if (err) {
              reject(err);
            } else {
              resolve(data);
            }
          });
        });
      }
    }
  }
});
```
>There's a bug on the openapi generator that my team is using on the java projects that needs all the refs to be relative to the main file so it properly generate the classes.

Duh. That's not the best world to live in. I feel your pain.

Thanks a lot for sharing this context!

>Will consider your hack and give it a try to see if i can get it to work. 

Hopefully this will help you find a workaround.

I'm going to close this for now. Feel free to comment about your findings!
