### ISSUE TITLE
Turn `oas3-unused-components-schema` into a more versatile rule

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#1073]
**User story.**
OpenaApi 3.x [Components](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#componentsObject) section list a lot of reusable objects. But we currently only focus on `schemas` orphaned objects. We could do so much more!!!

Proposal:
- Slightly tweak the function to make it accept an array of reusable objects locations and process them all as potential sources. The `given` property may have to be tweaked as well (`$`?).
- Rename this rule into  `oas3-unused-components-object` 
- Extend the test suites to cover those additional paths

Would this proposal be considered as a possible addition:
 - Create another issue targeting the `oas2` ruleset (and another one for the soon to be released `asyncapi` ruleset)

**Comment by nulltoken** [comment]
@philsturgeon Thoughts?

**Comment by philsturgeon** [comment]
Yeah I think we could have:

- oas2-unused-definition
- oas3-unused-component
- async-unused-component

Let's do this as a followup task when #965 is done.

**Comment by P0lip** [comment]
I think we can consider this closed thanks to https://github.com/stoplightio/spectral/pull/1440
