### ISSUE TITLE
Describe how to cope with unexpected issues in a custom function

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#1096]
**Chore summary**
Provide some guidance to the custom function writer with regards to errors

**Tasks**
- [ ] Add a section to `functions.md`

From https://github.com/stoplightio/spectral/pull/1058/files#r408418822

> @P0lip What's the effect from throwing from within a function? Does the whole process crash down? Do we get a special kind of result or a console log?

We'd get a console.log, same as we do when any other custom function throws an exception.
The whole process would still keep on going.

> if I prefer to see a CI build fail rather than having it pass for the wrong reasons

I'd return a regular error, i.e.
```
return [{ message: 'Network error. The check could not be performed' }]
```

**Comment by P0lip** [comment]
This will be addressed in v6!
