### ISSUE TITLE
How to use a bundler with spectral to use 'require' in custom functions?

### ISSUE THREAD

**Issue by astavria4** [stoplightio/spectral#1116]
"Require calls will work only in Node.js, and will cause errors for anyone trying to use the ruleset in the browser. If your ruleset is definitely going to only be used in the context of NodeJS then using them is ok, but if you are distributing your rulesets to the public we recommend avoiding the use of require() to increase portability."

I have a extensions.js file that has functions I reuse in multiple rulesets. Its very similar to:

const foo = require('./foo');
module.exports = (obj) => {
 if(!foo.testNode(obj)) return false; 
};

Im using spectral within an api. I have a swagger page where users put the yaml file in. Can you give me an example on how to use a bundler with the above code so that when the ruleset can be loaded and run?

**Comment by nulltoken** [comment]
@astavria4 

>Can you give me an example on how to use a bundler with the above code so that when the ruleset can be loaded and run?

The doc also states *"If you have any module system, you need to use some bundler, preferably Rollup.js as it generates efficient bundles."*

Although documenting how to use a bundler might be seen as a little out of scope of the Spectral documentation, I agree with you that this section could be improved a bit.

Meanwhile, below a couple of links which should get you started on your journey:
- The rollup.js quickstart: https://rollupjs.org/guide/en/#quick-start
- You could also study how we use rollup.js internally to bundle our own functions: https://github.com/stoplightio/spectral/blob/develop/rollup.config.js

**Comment by nulltoken** [comment]
@astavria4 Have you successfully leveraged rollupjs?

**Comment by astavria4** [comment]
No we have not. It’s not as intuitive and very little info online for what we are trying to accomplish. We are copy and pasting code instead of leveraging functions. We decided that if we can’t fix it in the next few sprints we would leverage another linter.

________________________________

**Comment by philsturgeon** [comment]
@astavria4 [require() support was added](https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/guides/5-custom-functions.md) in Spectral v5.2.0 as one of a few things to make things more enjoyable for NodeJS users. We're on v5.5.0 now so make sure you stay up to date to get access to the best functionality.
