### ISSUE TITLE
Ability to use 'show-unmatched-globs' in CI pipelines for missing specs

### ISSUE THREAD

**Issue by axelssonHakan** [stoplightio/spectral#1117]
**Describe the bug**
Right now the `show-unmatched-globs` only logs a message if a spec isn't found using a glob. It would be nice if it would change the exitCode as well (`process.exitCode = 1;`).
https://github.com/stoplightio/spectral/blob/develop/src/cli/services/linter/linter.ts#L73

Maybe the yarg option `--show-unmatched-globs` could be made to take a string and use that to change exit code if that is behaviour the user wants

- `--show-unmatched-globs=empty/info/warn` >> exitCode=0
- `--show-unmatched-globs=error`>> exitCode=1

**To Reproduce**

1. Run this CLI command `npx spectral lint --show-unmatched-globs globReturningEmptyArray`
2. `echo $?` >> 0

**Expected behaviour**
In CI environments it would be preferred if the `--show-unmatched-globs` returned an exitCode > 0 so you don't get any "false" positive tests

**Comment by nulltoken** [comment]
@P0lip Or maybe could we add an additional switch (`--fail-on-unmatched-globs`)... Thoughts?

**Comment by P0lip** [comment]
My apologies for dropping a ball on this one.
`--fail-on-unmatched-globs` sounds good.
