### ISSUE TITLE
--format junit includes just one failure

### ISSUE THREAD

**Issue by alexrainman** [stoplightio/spectral#1122]
In the other hand, ```--format json``` includes all them.

**Comment by nulltoken** [comment]
@alexrainman To help troubleshooting your issue, could you please provide
- a minimal repro case
- the command you're running
- the version number of the library you're using
- what you expect vs what you see

**Comment by nulltoken** [comment]
@alexrainman Have you had the time to work on a small repro case?

**Comment by P0lip** [comment]
Hey, is still an issue?
