### ISSUE TITLE
Equivilent paths points at paths not the bad path

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#1130]
If there are two paths that are causing a problem, we should point to one of those problematic paths, not just `paths:`.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/67381/80498624-dd8d1600-8963-11ea-8a49-4e7fc8018bc5.png">

Clicking that problem on the right "The paths foo and bar are equivalent" takes me to the paths object, and then I have to scroll for ages to find the problematic ones. That's if I'm in code view anyway. In Form view it just does nothing.

**Comment by P0lip** [comment]
> Clicking that problem on the right "The paths foo and bar are equivalent" takes me to the paths object, and then I have to scroll for ages to find the problematic ones. That's if I'm in code view anyway. In Form view it just does nothing.

Which one is the problematic one? I assume is the latter one in the document, but just want to make sure we are on the same page.
