### ISSUE TITLE
provide configuration option to suppress specific rule failures

### ISSUE THREAD

**Issue by marklindell** [stoplightio/spectral#1145]
**User story.**
As a API developer, I want to configure rule suppressions in the .spectral.yml file to apply to specific rules failures based on a combination of line location/range, severity, and rule name so that I can per project and specific instance decide if a rule is applicable in a specific instance.

I need this for my custom rules.

**Comment by marklindell** [comment]
I see another issue that is identical.

**Comment by ralphpina** [comment]
Which is there issue? 🙂
