### ISSUE TITLE
Feature to extend ruleset without a filereader dependency

### ISSUE THREAD

**Issue by codeasashu** [stoplightio/spectral#1151]
**User story.**
As a javacript developer, I should be able to extend existing ruleset without having to create/read a file, so that I can override existing ruleset partially.

**Is your feature request related to a problem?**
I am trying to override few rules of OAS 3 but I am working in a client side application, which does not have access to `fs.readFile` method. Is there a way I can pass in `extends` and be able to reference existing rule? 

For example, I am trying to make `info.description` non-required. So extending oas3 ruleset and overriding `info.description` seems intuitive. Something like:

```js
spectral.setRuleset({
        extends: "spectral:oas3",
        functions: [],
        exceptions: {},
        rules: {
          "info-description": false,
        },
      });
```
But it seems like this method completely ignores `extends`.

**Describe the solution you'd like**
Seems like the only way for now is to have a yaml/json rule file which allows `extends`. A method should exists to allow javascript objects to be passed in just as they would after being read from file/remote location.

**Comment by P0lip** [comment]
@codeasashu 
Hey!
You can try registering custom assets. This can be accomplished in the following way
`Spectral.registerStaticAssets(require('@stoplight/spectral/rulesets/assets/assets.json'));`

Then, there won't be any need for fs calls and everything will be handled automatically by Spectral, so basically you won't need to change anything in your code, besides adding that extra call I mentioned above.

**Comment by philsturgeon** [comment]
@P0lip could we find a home for this advice in the Docs?

**Comment by codeasashu** [comment]
@P0lip I think I've made some progress, but I am still lost. Just need few more nitpicks and I think I'll be there.

So this is what I have for now:

```js
lintSpec(spec) {
      Spectral.registerStaticAssets(require('@stoplight/spectral/rulesets/assets/assets.json'))
      const spectral = new Spectral();
      //spectral.registerFormat('oas3', isOpenApiv3)
      spectral.setRuleset({
        extends: "spectral:oas3",
        functions: [],
        exceptions: {},
        rules: {
          "info-description": {
            "description": "This description will allow null values",
            "recommended": false,
            "type": "style",
            "given": "$",
            "then": {
              "field": "info.description",
              "function": "falsy"
            }
        },
        },
      });
      spectral.run(spec)
        .then(results => {
          console.log('here are the results', results, spec)
        });
}
```

So now, this now only loads my `info.description` rules but discard every other rule. So I now have overwritten the original rules, by the ones I have just defined. Can you kindly share any small snippets so I can have little more idea in this direction?

**Comment by P0lip** [comment]
> @P0lip could we find a home for this advice in the Docs?

It's not a part of public API. It only serves for Studio.

@codeasashu
`setRuleset` does not support `extends`.
It expects an actual resolved ruleset to be supplied.

What you can try doing is the following:
```
lintSpec(spec) {
      Spectral.registerStaticAssets(require('@stoplight/spectral/rulesets/assets/assets.json'))
      const spectral = new Spectral();
      spectral.registerFormat('oas3', isOpenApiv3)
      await spectral.loadRuleset('spectral:oas');
      spectral.mergeRules({
        "info-description": {
          "then": {
            "field": "info.description",
            "function": "falsy"
          },
        ,}
     });
    
     // rest
}
```
Let me know how it went!

**Comment by P0lip** [comment]
I'm going to close this one.
Do feel free to re-open if it turns out to be not working for you :)
