### ISSUE TITLE
Tslint is officially deprecated. Time for eslint?

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#1152]
**Chore summary**
https://github.com/palantir/tslint/commit/119458e17c5bd37ca84b6d7a7a4295649d2103c0 shows that Tslint is considered as deprecated.

https://github.com/palantir/tslint/issues/4534 makes it even more clear

**Tasks**
- [ ] Migrate to Eslint (package.json, husky hook, ...)

**Comment by P0lip** [comment]
Yeah, totally agree.
We'd need to do it gradually, I guess.
I have a branch somewhere with some ESLint setup. We could start from there.
Will push it shortly.

**Comment by philsturgeon** [comment]
Yes please.
