### ISSUE TITLE
Break out OASv2 JSON schema oddities into separate rules

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/spectral#12]
We will have some separate validation rules that can be used to enable/disable validations for specific exceptions that OAS makes to their JSON schema support. These exceptions are documented in the  [OASv2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject) specification.

**Comment by casserni** [comment]
- [ ] oneOf
- [ ] anyOf
- [ ] allOf
- [ ] type needs to be one of the allowed values?

look at the errors, make em better

**Comment by philsturgeon** [comment]
Hey, whats the proposed plan here? If a document is 100% OpenAPI v2.0 compatible then there shouldn't be any issues with JSON Schema things should there? So long as we have AJV set up to understand OpenAPI v2.0 using the [official metaschema](https://github.com/OAI/OpenAPI-Specification/tree/master/schemas) then we should be ok? It will throw an error if you try to use anyOf thanks to the additionalProperties usage in the official metaschema.

Maybe you are suggesting a specific set of rules to basically look out for OpenAPI v3.0 and/or JSON Schema keywords in a v2.0 file, so Spectral can say "Warning: The fooBar keyword is OpenAPI v3.0 and not supported in v2.0!" just in case somebody copies and pastes an incorrect thing off of StackOverflow? 

Did I get it right, or do you mean something else?

**Comment by rossmcdonald** [comment]
No plan that I know of yet, but the intention here was to provide specific rules that a user could enable/disable if they wanted to use something that wasn't in the official metaschema.

> If a document is 100% OpenAPI v2.0 compatible then there shouldn't be any issues with JSON Schema things should there? So long as we have AJV set up to understand OpenAPI v2.0 using the official metaschema then we should be ok?

Yes, that's correct, and that's how it currently functions today. There are just some instances where you may want to use `anyOf`, etc even though it's not technically supported in that spec. So we could have a dedicated rule that you could enable/disable use of `anyOf` without it always marking the spec as invalid.

> Maybe you are suggesting a specific set of rules to basically look out for OpenAPI v3.0 and/or JSON Schema keywords in a v2.0 file, so Spectral can say "Warning: The fooBar keyword is OpenAPI v3.0 and not supported in v2.0!" just in case somebody copies and pastes an incorrect thing off of StackOverflow?

That's a great idea, but not what this issue was originally intended for (though having that functionality would be awesome). In general the errors and error messages could use a lot of love.

**Comment by philsturgeon** [comment]
Is it very common for people to create invalid OpenAPI v2/v3/Json Schema combinations? 

As far as I know, people are writing

a) OpenAPI v2
b) OpenAPI v3
c) OpenAPI v3 + JSON Schema proper

I think writing specific functionality which makes folks think writing OpenAPI v3 or JSON Schema keywords like allOf into OpenAPI v2 would be potentially confusing for a lot of people, and be encouraging behaviour which will lead to edge cases and specs which only work in Spectral.

For Speccy I implemented a special switch that would convert "JSON Schema Proper" to "OpenAPI-flavoured JSON Schema" and this helped a lot of folks out with wanting to use actual JSON Schema for some stuff but still have proper OpenAPI which could be used anywhere. Maybe we could look into this sort of thing instead?

https://blog.apisyouwonthate.com/openapi-and-json-schema-divergence-part-2-52e282e06a05

**Comment by erik-hansen** [comment]
Example: I left the host field blank intentionally and it's not required by [OAS2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields).  However, the oas2-schema rule validates a specific pattern, not including the possibility of blank.  So, I get this:
![image](https://user-images.githubusercontent.com/6989957/58127091-68e51f80-7bc9-11e9-92da-d9a1aa52f7a8.png)

Would be helpful if host field pattern checking was split out of this rule to create a seperate "warn" severity, or add to the existing "api-host" rule.

Point is, the oas2-schema rule should focus on the required structure of the spec.  Optional and specific field validations should be split out into separate rules.
