### ISSUE TITLE
Support validating examples keyword of a JSON schema

### ISSUE THREAD

**Issue by awlayton** [stoplightio/spectral#1211]
**User story.**
I am trying to migrate my schema checking from mocha tests I wrote to spectral. There is a way to validate the `example` keyword of OAS3 already, but I also need to validated the `examples` array keyword of JSON Schema.

**Describe the solution you'd like**
Perhaps `schemaPath` could support a JSONPath in place of a field?

**Additional context**
Here was my attempt at a custom rule before realizing it is not possible with `schemaPath`:
```json
{
  "valid-examples": {
    "description": "Examples must be valid against their schema",
    "message": "{{error}}",
    "recommended": true,
    "type": "validation",
    "given": "$.examples^",
    "then": {
      "function": "schemaPath",
      "functionOptions": {
        "allErrors": true,
        "field": "$.examples[*]",
        "schemaPath": "$"
      }
    }
  }
}
```

Or maybe support saying that the field is an array?
```json
{
  "valid-examples": {
    "description": "Examples must be valid against their schema",
    "message": "{{error}}",
    "recommended": true,
    "type": "validation",
    "given": "$.examples^",
    "then": {
      "function": "schemaPath",
      "functionOptions": {
        "allErrors": true,
        "arrayField": true,
        "field": "examples",
        "schemaPath": "$"
      }
    }
  }
}
```

**Comment by nulltoken** [comment]
@awlayton 👋 

The asyncapi ruleset contains a rule than ensure values of the `examples` array are valid against their defined schema (cf. https://github.com/stoplightio/spectral/blob/develop/src/rulesets/asyncapi/index.json#L264-L283) and the matching tests (cf. https://github.com/stoplightio/spectral/blob/develop/src/rulesets/asyncapi/__tests__/asyncapi-schema-examples.ts)

Does that help?

**Comment by awlayton** [comment]
That was very helpful thanks. Sorry for the issue.
