### ISSUE TITLE
Questions regarding treeware clause

### ISSUE THREAD

**Issue by prabhu** [stoplightio/spectral#1221]
**Chore summary**
I maintain a license audit tool that highlights license conditions for open-source packages. It currently uses SPDX id (eg: Apache-2.0 for this project) to determine the conditions. Enterprise customers keep an eye on license conditions by using automated tools and scripts that are implemented similarly. Recently, a client flagged up this project to see if I can enhance my software.

This project is a treeware which is quite interesting and confusing simultaneously. While I can appreciate the good intentions behind asking for a tree there are a number of questions:

- What constitutes a production use?
- How can this be enforced? What evidence or paper-work is expected from a client?
- What can be done if a client simply cannot plant a tree? Can they seek an alternative license or should they stop using such treeware projects?

I know I am picking this project instead of asking the treeware people. But this is another legal challenge too. What if the condition of a treeware gets updated after clients become compliant. For instance, it currently says a tree (single). What if it says a forest (multiple trees) from tomorrow.

Thanks for your help.

**Comment by philsturgeon** [comment]
The mention of Treeware should not be under license, our license is Apache 2.0 and there's no Tree clause in that license. It should be somewhere like "Thanks" so you can show us thanks if you like the product. To be clear, theere are no more legal obligations to buy us a tree than there is to buy anyone a coffee or a beer or subscribe to their patreon. 

I'll move the header so nobody else is confused about this. Thank you!
