### ISSUE TITLE
Document httpAndFileResolver usage for JavaScript API

### ISSUE THREAD

**Issue by DavidBiesack** [stoplightio/spectral#1225]
**User story.**
As a developer, I can reuse the same Resolver used by Spectral CLI when using the JavaScript API, so that I can validate OpenAPI documents which `$ref` schemas via https/http schemas.

**Is your feature request related to a problem?**
When embedding Spectral JavaScript API, the default resolver does not resolve http/http schemas. I get
```
 {
    code: 'invalid-ref',
    path: [ ... ],
    message: "No resolver defined for scheme 'https' in ref https://production.api.apiture.com/schemas/mySchema/v1.0.0/model.json",
    severity: 0,
    range: { start: [Object], end: [Object] }
  }
```

**Describe the solution you'd like**

The default Resolver used when using `new Spectral()` (not passing in an explicit `resolver` in the options) should be the same `httpAndFileResolver` used in the CLI.

If you choose to not change the default for `new Spectral()`, please export `httpAndFileResolver` from the module, or add a constructor `static httpAndFileResolver(): Resolver` from the `Spectral` or other class so I can access it, for example via `new Spectral({resolver: Spectral:httpAndFileResolver()})`. (Also update the docs as necessary.)

I know work is underway to migrate off `@stoplight/json-ref-resolver`. If that takes priority, please provide equivalent functionality to `httpAndFileResolver` for the JavaScript API in that refactor

**Additional context**
I'm using 5.4.0
See [the guide](https://community.stoplight.io/t/how-to-specify-http-https-resolver-from-spectral-typescript-api/1328).
Thus, I need to recreate `httpAndFileResolver` and `httpResolver` and `fileResolver` (by copying code from Spectral).

**Comment by DavidBiesack** [comment]
(I raised this in the [community forum](https://community.stoplight.io/t/how-to-specify-http-https-resolver-from-spectral-typescript-api/1328) but did not get any response or workaround.)

**Comment by nulltoken** [comment]
@DavidBiesack 

I believe the following should work for you:

```
import { httpAndFileResolver } from '@stoplight/spectral/dist/resolvers/http-and-file';
```

**Comment by philsturgeon** [comment]
@nulltoken there we go! Let's get that in the docs for JS API so folks know for next time.

**Comment by DavidBiesack** [comment]
Perfect - works nicely. 

I still suggest making `httpFileResolver` the _default_ for `new Spectral()`, to make it work "out of the box" (convention over customization, fewer surprises), and to minimize possible dependencies or breaking changes as you replace the resolver framework.

**Comment by nulltoken** [comment]
@philsturgeon I'm not sure it should be documented as is. It's not exported from the default namespace. As far as I remember, everything that's not part of the default namespace is considered as `internal thingies` not part of the officially maintained API surface and subject to potential changes.

@P0lip Thoughts?

**Comment by philsturgeon** [comment]
Oh nevermind, if we're making it default then lets not worry about documenting it. Let's make this part of v6 as its breaking, and we've got a few breaking bits coming.
