### ISSUE TITLE
Error code when installing spectral from npm

### ISSUE THREAD

**Issue by rmerceragari** [stoplightio/spectral#1226]
**Describe the bug**
When I install spectral via npm I get a nonzero return code from the npm install

**To Reproduce**

1. docker run --rm -it ubuntu:20.04 /bin/bash
2. apt-get update && apt-get install npm -y
3. npm install -g @stoplight/spectral
4. echo $? <--- non zero

Oddly; if i rerun the npm install after this it works... idk weird.

**Expected behavior**
Get zero from echo $?

**Screenshots**
Here's what I get:
/usr/local/bin/spectral -> /usr/local/lib/node_modules/@stoplight/spectral/dist/cli/index.js

> core-js@3.6.5 postinstall /usr/local/lib/node_modules/@stoplight/spectral/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

**Additional context**

**Comment by philsturgeon** [comment]
Not much to go on here, could have been anything going on with npm. If it continues to happen and/or you find a more damning error please can you share it with us? 

Thank you!
