### ISSUE TITLE
Rule to enforce files ending with new line

### ISSUE THREAD

**Issue by mpetrunic** [stoplightio/spectral#1259]
**User story.**
As a api spec developer, I would like to add rule to spectral.yml to enforce spec (yaml) files to end with new line.

**Is your feature request related to a problem?**
Github is always complaining on missing new line on file end.

**Describe the solution you'd like**
Is it possible to define such custom rule*

**Additional context**

**Comment by philsturgeon** [comment]
Spectral pretty much works on JSON/YAML, which means it's not going to know if there is a new line or not. There are quite a few ways to do that without Spectral which might be more in scope for it:

Maybe something like Linelint would sort it out for you? https://github.com/marketplace/actions/linelint

**Comment by mpetrunic** [comment]
Seems reasonable. I was curious if I could avoid yet another tool.
