### ISSUE TITLE
`operation-2xx-response` rule should not be recommended

### ISSUE THREAD

**Issue by krystof-k** [stoplightio/spectral#1273]
I suggest to move `operation-2xx-response` rule out from recommended, as it is reasonable to have endpoints that have no success response but only 3xx redirects. Or maybe change the rule to allow 2xx or 3xx responses.

What do you think?

**Comment by philsturgeon** [comment]
@krystof-k hey there! Could you explain the use case a little more? What is happening with your API where only 3xx is coming out of it? I seem to remember the YouTube API used to do this, where a successful POST would then say "this worked out and you should follow to the `Location` to get the content" but this always struct as a weird choice. 204 with a Content-Location would be more correct.

If you want room to be creative, you can [turn that rule off](https://meta.stoplight.io/docs/spectral/docs/guides/4-custom-rulesets.md#disabling-rules), but maybe there is a legit use case I'm forgetting and you could help remind me!

**Comment by krystof-k** [comment]
We use it for forwarding to pre-signed URL on AWS S3. Client requests `GET /files/{file ID}` and if authorized, server generates the URL and sends `Location: https://bucket.s3.amazonaws.com/file.ext?X-Amz-Signature=blabla` header in the response.

**Comment by philsturgeon** [comment]
Ahh nice use case.

Ok, let's change this rule from `operation-2xx-response` to `operation-success` and look for anything starting with a 2 or a 3.

**Comment by krystof-k** [comment]
Cool! :)

BTW thanks for mentioning `Content-Location` header, seems I'm using the `Location` header for newly created object in 201 Created response wrong :)
