### ISSUE TITLE
Is it possible to reference core functions in custom functions?

### ISSUE THREAD

**Issue by vitaly-magyari** [stoplightio/spectral#1275]
**User story.**
As a custom rule developer I'd like to implement rules in such a way that check are performed if there is a marker field is absent in document, and skipped otherwise

**Is your feature request related to a problem?**
I have special schemas that are not subject to say `info-contact` check and they are marked by `info:skip-contact: true` field. 

the core rule is quite simple
```
    "info-contact": {
      "description": "Info object should contain `contact` object.",
      "recommended": true,
      "type": "style",
      "given": "$",
      "then": {
        "field": "info.contact",
        "function": "truthy"
      }
    },
```
But I'm at a loss as to how to add that extra check. I can write my custom function, yes, but I can't reference `truthy` from it, I think. So in a more complex core function case I have to either re-write completely or extract from the source. Am I wrong? I there a better way?

**Describe the solution you'd like**
Something along the lines of:
```
module.exports = (targetVal, opts, _paths, otherValues) => {
  const { value } = opts;
  if (targetVal.info["skip-info"] === true) return;
  
  return core.truthy(tagretVal.info) // I'd rather reference a rule here, but that's probably too much to ask...
    
  };
```

**Comment by P0lip** [comment]
@vitaly-magyari 
Hey!
Yep, it's possible to do so!

```js
module.exports = function (targetVal, opts, _paths, otherValues) {
  const { value } = opts;
  if (targetVal.info["skip-info"] === true) return;
  
  return this.functions.truthy(tagretVal.info, opts, _paths, otherValues);    
};
```

**Comment by nulltoken** [comment]
Tagged as `documentation`. This may be interesting to add to the custom function section of the doco.

**Comment by im-shyam** [comment]
Hi, I ran into the same problem and we started using custom functions of spectral in our code base doing something like this 
```
import {
  casing as casingFn,
  CasingType,
} from "@stoplight/spectral/dist/functions/casing";
```
and usage will be like 

```
      const msg:
        | void
        | IFunctionResult[]
        | Promise<void | IFunctionResult[]> = casingFn(
        name,
        { type: CasingType.camel },
        {} as IFunctionPaths,
        {} as IFunctionValues
      );

```
Let me know if this is the right way to do it and if you could use it as well.
