### ISSUE TITLE
Surface custom ruleset issues in a more standard way

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#1283]
Currently issues in custom rulesets are detected and reported. However, from a UX standpoint, it may make sense to surface them to the caller using the format that Spectral use for rules.

As such, issues in files and issues in custom rulesets would be reported in the same manner (The "source" would be the ruleset, the ranges would point at problems in the ruleset....).

Teaching Spectral to behave this way would make ruleset editing in VSCode (leveraging the `vscode-spectral` extension) a much more user friendly experience, for instance.

**Comment by nulltoken** [comment]
As #1021 will implement a pre-validation step, making this issue happen may actually be an good starting point.

**Comment by philsturgeon** [comment]
PRs exist for validation improvements. https://github.com/stoplightio/spectral/pull/2026
