### ISSUE TITLE
Add resolve command from speccy

### ISSUE THREAD

**Issue by duydao** [stoplightio/spectral#1286]
**User story.**
As a user, I would like to resolve a document with all $refs into a single document, so that I can use it on a mock server or on an API Gateway to generate the Endpoints

**Is your feature request related to a problem?**
Currently, there is no way to save the resolved document like in [speccy](https://github.com/wework/speccy#usage). This makes it hard to use the API file in different services, where everything must be in one file.

**Describe the solution you'd like**
- Add a command line argument to lint & resolve the document, printing the resolut to STDOUT
- an argument to save the output to the filesystem

**Additional context**
Maybee we could use the speccy implementation, see speccy resolve https://github.com/wework/speccy#usage -> 
speccy resolve [options] <file-or-url>  pull in external $ref files to create one mega-file

**Comment by nulltoken** [comment]
@duydao FWIW https://github.com/stoplightio/spectral/pull/433 introduced `runWithResolved()` which just does this. However, it's not been surfaced at the CLI level. I'm not sure there are any plans to surface this at the CLI level though.

Maybe as a workaround could you try and whip up a simple Node.js script that would leverage https://github.com/APIDevTools/json-schema-ref-parser and invoke `dereference()`?

**Comment by duydao** [comment]
@nulltoken Thanks for your hint. I've checked out json-schema-ref-parser, and it also has a bundle() method that does what I was looking for. Closing this Issue, thanks again!
