### ISSUE TITLE
Document the Rule: `no-$ref-siblings`

### ISSUE THREAD

**Issue by stephenlprice** [stoplightio/spectral#1307]
**User story.**
My OpenAPI file contains a `$ref` next to an additional property `nullable: false` and I am using Spectral to correct it. If I run Spectral in CLI this rule is surfaced however the rule is not documented under the OpenAPI Ruleset: https://meta.stoplight.io/docs/spectral/docs/reference/openapi-rules.md

**Is your feature request related to a problem?**
I want to learn more about this rule. Stoplight Studio also enforces this rule and directs users to the Spectral docs, however this rule is not described.

**Describe the solution you'd like**
When Spectral surfaces the error `$ref cannot be placed next to any other properties` with the name `no-$ref-siblings`, I can find a description of this error in the docs.

**Comment by nulltoken** [comment]
@stephenlprice Could you please take a look at #1308 and see if the proposed addition fits you?
