### ISSUE TITLE
Need static response sample API

### ISSUE THREAD

**Issue by vijayjava1** [stoplightio/spectral#1319]
**Chore summary**
I need sample request/response and API for static example using stoplight inbuilt prism. 

**Tasks**

>>>>>>>>>>>>>>
Below is the request and response details. Based on request it has to retrieve that perticular recard.
If I have 100 records defined in response example then it has to fetch only the relavant record based on my request input. 
Request:
{
"id":12
}
Response:
{
"id":12,
"name":"Vijay", 
"location":"India"
}
>>>>>>>>>>>>>>
Request:
{
"id":20
}
Response:
{
"id":20,
"name":"kumar", 
"location":"Blr"
}
**Additional context**
This is to understand static example filtering based on searching.

**Comment by philsturgeon** [comment]
Sorry friend, this is spectral not prism. Different tool!
