### ISSUE TITLE
Access to target document in custom functions

### ISSUE THREAD

**Issue by ederparaiso** [stoplightio/spectral#1335]
**User story.**
As a custom function user, I can do access to resolved target document that spectral runs lint, so that I can build composed rules that analyzes target values (jsonpath given fields) and fields beyond this values.

**Is your feature request related to a problem?**
Some of my custom functions need to access context beyond `targetValue` (resolved jsonpath in `given` field of the rules). Changing the given field to `$` works but don't make sense to rule. In spectral current version its possible to access document through `otherValues` property (using, `otherValues.documentInventory.resolved`). Although it works, this solution is discouraged in official docs since it serves for internal purposes. The only recommended properties are `otherValues.original` and `otherValues.given`.

**Describe the solution you'd like**
I would like to suggest to expose access to target document context (resolved) in a "official recommended manner", for example through `otherValues.resolvedDocument`.

**Comment by nulltoken** [comment]
>Some of my custom functions need to access context beyond `targetValue` (resolved jsonpath in `given` field of the rules).
>Changing the given field to `$` works but don't make sense to rule. 

@ederparaiso In order to better understand why exposing the whole document would be desirable, could you please share with us:
- what your custom functions do?
- why pointing out to `$` would make little sense in your context?

**Comment by ederparaiso** [comment]
@nulltoken, my apologies for taking so long to answer you.

> what do your custom functions perform?

Our use case is a little bit complex, but I'll try to explain the idea. We use spectral in a ci pipeline for pull request analysis. Due to some requirements, we lint only changed portions of document. The document that spectral lints contains an oas3 data and an extra field called "diff" which contains paths of changed oas document. Some rules depends on "diff" paths and "original" document to do a context analysis.

Another example would be situations where we need to perform composed conditions. Maybe a bad example, but suppose that if "license" field is present, we need to ensure "contact" field exists. We could set `$.license` to `given` field and the custom function would check on `otherValues` if `$.contact` is present.

> why pointing out to $ would make little sense in your context?

If I set `$` as "given" path, I need to perform at least two JSON paths calculations beyond default JSON path that spectral runs on `given` field. So using spectral becomes unnecessary and redundant. Setting the correct "diff" path turns the rule more meaningful and the function more reusable and generic. Thus, for large documents, setting `$` will duplicate the same content in spectral context, consuming more resources unnecessary.

**Comment by P0lip** [comment]
Hey @ederparaiso.
You don't need to worry about it.
When we added that feature back in the day, `documentInvetory` didn't have any stable API, but now it's considered stable.
Feel free to use it.
I'll update the documentation at some point.

**Comment by ederparaiso** [comment]
Thank you @P0lip !
