### ISSUE TITLE
Serve spectral linting via API

### ISSUE THREAD

**Issue by stevendoll** [stoplightio/spectral#1340]
**User story.**
As an API Platform Manager , I can access Spectral via API, so that I can integrate business and quality rules into my platform processes.

**Describe the solution you'd like**
Spectral is available via command line and directly in javascript. That works well if I use it locally. But how to we integrate this with our API registry, business/security policies, or CI/CD pipelines? Ideally we would like to POST with the yaml text in the payload, and get back something like:

    { 
        errors: 
        [
            { 
                lineNumber: 5,
                errorCode: "Missing404Response",
                description: "A 404 response is required when a path parameter is present."
            },
            { 
                lineNumber: 22,
                errorCode: "CreationRequires201Response",
                description: "A 201 response with a location header is required when a resource is created."
            },

        ]
        warnings:
            { 
                lineNumber: 105,
                warningCode: "Query parameter that is required",
                description: "Requiring a query parameter is discouraged. A better practice is to make it optional and include a sensible default."
            },
    }

We're also interested in the ref$ expansion that spectral can do.

**Comment by marbemac** [comment]
Hi @stevendoll - an interesting request! Drilling into the gap a little bit more, where does the CLI option fall short? We've seen a lot of folks successfully use the in their CI/CD pipeline, similar to how you'd run tests.

**Comment by stevendoll** [comment]
Marc,

We’re envisioning a stand-alone service that can be consumed by multiple points in the chain. This can support multiple use cases from quality to cyber to compliance to reuse. 

Regards. 

Steven

**Comment by philsturgeon** [comment]
So you'd be looking for a way to run this service yourself in your own environment, not a central `spectral.stoplight.io/api` that anyone can use to handle this? 

If it's for yourself, the JavaScript API could be wrapped in a simple node script to achieve this quite quickly. We could probably put together an example and make a blog post out of it.

**Comment by stevendoll** [comment]
Thanks for the ideas. I think wrapping the js API is pretty close to our use case. I’ll keep my eyes open for that blog post, because it’s a little outside of my experience. 

Steven

**Comment by stevendoll** [comment]
One of our engineers has made a wrapper that works in an AWS lambda. We'd love your feedback...

**Comment by philsturgeon** [comment]
@stevendoll absolutely, please gimme a link or email phil@stoplight.io if you like.
