### ISSUE TITLE
Help needed with custom rule

### ISSUE THREAD

**Issue by alexrainman** [stoplightio/spectral#1343]
Need to make definitions fields ```example``` and ```description``` required but cannot figure it out the correct ```given``` path.

Please help.

**Comment by P0lip** [comment]
Hey!
You can try using https://jsonpath.com/ and see whether it helps you generate the right JSON path expression.

BTW, could you please please use the [Stoplight Community Forum](https://community.stoplight.io) for your future support questions?
GH Issues is primarily for bugs & features, meaning the support is rather a bit limited here.
