### ISSUE TITLE
Nullable enum warning for null value in example section

### ISSUE THREAD

**Issue by sergle** [stoplightio/spectral#1353]
I receive warning when trying to use null value in example section for property with enum.

**To Reproduce**

1. Given this OpenAPI/AsyncAPI document:
[nullable_enum.yaml](https://github.com/stoplightio/spectral/files/5274847/nullable_enum.txt)

2. Run this CLI command:
> spectral lint -v nullable_enum.yaml

3. See error
> Found 82 rules (66 enabled)
> Linting nullable_enum.yaml
> OpenAPI 3.x detected
> 
> nullable_enum.yaml
>  39:23  warning  typed-enum  Enum value `null` does not respect the specified type `string`.
> ✖ 1 problem (0 errors, 1 warning, 0 infos, 0 hints)
> 

**Expected behavior**
No warnings produced

**Environment:**
 - Library version: 5.5.0
 - OS: Debian 9 (image node:14.11-slim from Docker Hub)

**Additional context**
FROM node:14.11-slim
RUN yarn global add @stoplight/spectral
ADD nullable_enum.yaml nullable_enum.yaml
RUN spectral lint -v nullable_enum.yaml

**Comment by philsturgeon** [comment]
Do you even need to have that null in there? Isn't that redundant?

**Comment by sergle** [comment]
Yes, it's redundant. But I'm trying to document existing API which is already used in such way.

**Comment by philsturgeon** [comment]
OpenAPI wouldn’t care unless... are you trying to have a literal null or a string which is a “null”? If the API is spitting out “null” then you cannot use nullable: true.

**Comment by sergle** [comment]
A literal null.

**Comment by philsturgeon** [comment]
Ok so when you’ve removed it from the OpenAPI description, how does Spectral behave? It’s one less thing for us to worry about and as it’s literally redundant it doesn’t need to be there. If it’s still broke we can look into it.

**Comment by sergle** [comment]
When I remove result:null from example, output is:
> Found 82 rules (66 enabled)
> Linting /tmp/nullable_enum.yaml
> OpenAPI 3.x detected
> 
> /tmp/nullable_enum.yaml
>  39:23  warning  typed-enum  Enum value `null` does not respect the specified type `string`.
> 
> ✖ 1 problem (0 errors, 1 warning, 0 infos, 0 hints)

When I remove null from enum values, output is:
> Found 82 rules (66 enabled)
> Linting /tmp/nullable_enum.yaml
> OpenAPI 3.x detected
> 
> /tmp/nullable_enum.yaml
>  41:25  error  oas3-valid-schema-example  `result` property should be equal to one of the allowed values: OK, FAILED
> 
> ✖ 1 problem (1 error, 0 warnings, 0 infos, 0 hints)

When I remove both result:null and null from enum values, no problem found.
