### ISSUE TITLE
Take x-nullable into consideration for oas2 valid examples

### ISSUE THREAD

**Issue by igas** [stoplightio/spectral#1359]
**Describe the bug**

`oas2-valid-response-schema-example` does not consider `x-nullable`

**To Reproduce**

1. clone https://github.com/igas/examples-examples
2. `spectral lint oas2.yaml`
3. See error `63:24    error  oas2-valid-response-schema-example  `nickname` property type should be string`

**Expected behavior**
Because nickname has x-nullable I expect it not to raise error

**Additional context**
I believe it's related to #1284 as it started failing with 5.5.0 upgrade attempt

**Comment by igas** [comment]
Thanks @P0lip!

**Comment by corroded** [comment]
@P0lip Curious why this was reverted in master? https://github.com/stoplightio/spectral/commit/621c02505e1178a4aef7817c138ac45e7a88287d

**Comment by P0lip** [comment]
@corroded Hey. I had to revert it since patch-package didn't work too well with npm installations of Spectral.
Binaries worked just fine. I'll revisit it soon - I'm hoping to get it out in one of the next releases.
