### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by sultanarif-p** [stoplightio/spectral#1373]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**

**To Reproduce**

1. Given this OpenAPI/AsyncAPI document '...'
2. Run this CLI command '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

**Comment by P0lip** [comment]
Hey!
Could you please describe what the issue is?
There doesn't seem to be other information than the contents of our issue template.
