### ISSUE TITLE
Multiple extends with enabled extra rules does not work

### ISSUE THREAD

**Issue by exoszajzbuk** [stoplightio/spectral#1380]
When using multiple extends turning ON specific rules in the "base" ruleset does not work in the extended one, but turning rules OFF does.

**To Reproduce**

Have a `base.yaml` like this (where by default `tag-description` is turned off and `operation-operationId` is turned on)

```
extends: spectral:oas

rules:
  tag-description: true
  operation-operationId: off
```

and a `ruleset.yaml` like this:

```
extends: ./base.yaml
```

with the following test OpenAPI document in `api.yaml`

```
openapi: 3.0.0
servers:
  - description: Test API
    url: https://example.com/api
info:
  description: 'Test API'
  version: 1.0.0
  title: Test API
  contact:
    email: contact@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: test                # !!! note tag not having description !!!
paths:
  /test:
    get:                      # !!! note endpoint not having operationId !!!
      tags:
        - test
      summary: 'Test Operation'
      description: 'Test Operation'
      responses:
        '200':
          description: successful operation
```

When running `npx spectral lint api.yaml -r ruleset.yaml` the result is:

```
OpenAPI 3.x detected
No results with a severity of 'error' or higher found!
```

**Expected behavior**

Since in `base.yaml` the rule `tag-description` is turned ON, I'd expect the command above to fail on the missing tag description. Please note that on the other hand `operation-operationId: off` does work (the example above missed `operationId` so without explicitly turning it off the command should fail).

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0] - 5.6.0
 - OS: [e.g. Windows 7] - macOS 10.15.6

**Comment by P0lip** [comment]
Isn't this issue similar (or perhaps a duplicate) to https://github.com/stoplightio/spectral/issues/1352?

**Comment by exoszajzbuk** [comment]
It is maybe connected, but definitely not a duplicate

**Comment by exoszajzbuk** [comment]
any updates on this?

**Comment by P0lip** [comment]
Hey @exoszajzbuk. No update yet. I can only confirm that the issue you raised is indeed valid and we're hoping to address the issue.
