### ISSUE TITLE
bump up ajv to >=6.12.3 to fix high CVE in dependency 

### ISSUE THREAD

**Issue by rahmer** [stoplightio/spectral#1381]
**Describe the bug**
Spectral depends on AJV and the current dependency version, 6.12.2 has a High vulnerability against it (Prototype Pollution). Any version >=6.12.3 has it fixed (current latest is 6.12.6 as of filing this report)

**To Reproduce**
1. Confirm CVE severity and impacted version at https://snyk.io/vuln/npm:ajv

**Expected behavior**
All dependencies should be at a version that have all known High CVEs resolved where fixes are available.

**Environment (remove any that are not applicable):**
 - Library version: spectral v5.6.0

**Additional context**
Proposed Fix: bump up dependency to 6.12.3 or later

**Comment by P0lip** [comment]
Resolved in https://github.com/stoplightio/spectral/commit/95fafbb1e0c1d17199e48111fc1e1e2c9464278a
The next release will contain the fix.
