### ISSUE TITLE
defined function is not registered in the core functions index

### ISSUE THREAD

**Issue by iwb-rubentytgat** [stoplightio/spectral#1384]
**Describe the bug**
The `defined` function, while implemented and documented, does not appear to be registered as a core function.

**To Reproduce**

1. Given any ruleset referencing the core function `defined`
2. It will throw an error: `Function defined not found. Called by rule foo.`

**Expected behavior**
It should find the `defined` function.

**Additional context**
Origin of the issue is probably in this file: https://github.com/stoplightio/spectral/blob/v5.6.0/src/functions/index.ts

The `defined` function is not included in the CoreFunctions map, unlike all the other core functions.

**Comment by P0lip** [comment]
Fixed in 5.7.1
