### ISSUE TITLE
Support the ignoring of specific rules from the OAS definition

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/spectral#1404]
**User story.**
As an API Designer
I want to improve my legacy APIs overtime and not be told off for non compliance when I cannot change
So that any errors shown are useful and I am not overwhelmed

**Is your feature request related to a problem?**
There is not a way to disable specific rules from the API definition. The spectral file has to be changed. 

**Describe the solution you'd like**
Zally https://github.com/zalando/zally allows the use of `x-zally-ignor` within the API definition to disable specific rules (as does other linters we use)
It would be great to be able to provide an ID for each rule similar how google AIPs have (this will also help tie back linting rules to standards) and to include an ignor property (at API, path or operation level) that will disable the linting of specific rules if the legacy API is not able to be compliant with all rules at this time.

**Comment by P0lip** [comment]
Hey.
My apologies for a delay response.
Spectral supports [exceptions](https://github.com/stoplightio/spectral/blob/develop/docs/guides/6-exceptions.md).
I believe this might be something you are looking for.
LMK if that meets your expectation!

**Comment by savage-alex** [comment]
Hi @P0lip, no need to apologies at all! This is a good start for sure! In the future had you thought about allowing the API definition to be annotated directly so that teams can still use the master record but annotate any rules they wish to disable either on the whole API or on a given path / operation. For now lets close this one!

**Comment by P0lip** [comment]
> This is a good start for sure! In the future had you thought about allowing the API definition to be annotated directly so that teams can still use the master record but annotate any rules they wish to disable either on the whole API or on a given path / operation

Yeah, that's certainly not a bad idea!
