### ISSUE TITLE
improve custom ruleset documentation

### ISSUE THREAD

**Issue by delanym** [stoplightio/spectral#1410]
The documentation is by example, but there's a lot of funky syntax going on that could be explained up front.

My use case is that I'm trying to create a rule where component schemas ending in "Request" or "Response" must have a property "x-message-type" with pattern [0-9]{4}

Its not clear to me how the selector works and how regex fits into that. 

Also the subject of ruleset groups (Recommended vs All) isn't explained anywhere. There's only a passing reference to it at https://meta.stoplight.io/docs/spectral/docs/guides/4-custom-rulesets.md#disabling-rules

What is this double bracket syntax? [[spectral:oas, all]]
Are there other groups?

**Comment by delanym** [comment]
I see the selector is jsonpath plus

**Comment by philsturgeon** [comment]
@delanym It seems like you've discovered the selector is JSON Path Plus. I'll mention that in the [Given documentation](https://meta.stoplight.io/docs/spectral/docs/guides/4-custom-rulesets.md#given). 

@P0lip could you help me out with some words about `What is this double bracket syntax? [[spectral:oas, all]]`? I'll take a swing at documenting recommended vs not.

**Comment by P0lip** [comment]
> @P0lip could you help me out with some words about What is this double bracket syntax? [[spectral:oas, all]]? I'll take a swing at documenting recommended vs not.

That double bracket syntax is just JSON-ish notation for nested arrays

```yaml
-
  - spectral:oas
  - all
```
is equal to
```yaml
[["spectral:oas", "all"]] # or [[spectral:oas, all]]
```
and 
```json
[["spectral:oas", "all"]]
```

**Comment by philsturgeon** [comment]
Ok I've made a PR for recommended vs all and I'm leaving it there.
