### ISSUE TITLE
Question: Using Spectral API, how to use URL instead of OpenApi document and how to define the output format?

### ISSUE THREAD

**Issue by TarekMansour** [stoplightio/spectral#1469]
I want to use [Spectral Javascript API](https://meta.stoplight.io/docs/spectral/docs/guides/3-javascript.md), and I want to ask on how:
- to use `URL` instead of `OpenApiDocument`, for example to do this `spectral.run(myURL).then(console.log);`
- to define the **output format** like we can do with **Spectral CLI** ( `--format html` ).

Thank you!

**Comment by P0lip** [comment]
Hey!
I moved the question over to https://github.com/stoplightio/spectral/discussions/1475 and provided an answer there as well!
Please let me know if that was what you were looking for.
Happy to help further if needed.
I'll close the issue for now. Let's discuss any potential caveats in the thread I linked above. Thanks!
