### ISSUE TITLE
Feature : Skip rule

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#147]
### **I'm submitting a...**
  - [ ] bug report
  - [x] feature request

### What is the current behavior?

You will get all errors for everything in whatever ruleset, and there is no way to disable it. 

### What is the expected behavior?

As a Spectral CLI user, sometimes I like a whole ruleset but a specific rule is really annoying me for some reason. I would like to be able to pass `--skip=valid-example` and spectral would not even bother running that. 

### What is the motivation / use case for changing the behavior?

Plenty of folks have pointed out that the default ruleset is a bit more opinionated than they might like, so turning off a few errors temporarily whilst their team catch up on fixing them would help.

**Comment by cg-cnu** [comment]
Hey hi Phil! Have written a bit of TS and familiar with OpenAPI  but haven't come across spectral. Sounds like an interesting project. Would like to get myself familiar with the project and work on this issue. Am I eligible to pick it up ?

**Comment by philsturgeon** [comment]
Hey @cg-cnu, of course you are! Let me know if you have any questions, and I’ll check back in with you if things go quiet. :)

**Comment by philsturgeon** [comment]
@cg-cnu hey! This was a great change and I appreciate the work you put in. Life does have a habit of getting in the way, but we needed this pronto as a workaround for #187, so I finished up the testing for you. Thanks for the work!
