### ISSUE TITLE
ignore - failure status code

### ISSUE THREAD

**Issue by miqui** [stoplightio/spectral#1471]
**Describe the bug**
Not a defect, but a question: how do I avoid and or how to override the 1 status code (even if the yaml/json content can generate an error) ?

I want to run spectral without of failing the job (at least for now while i debug/tune my ruleset)

..thank..

**Comment by P0lip** [comment]
Hey!
You can try to pass [`---fail-severity`](https://github.com/stoplightio/spectral/blob/develop/docs/guides/2-cli.md) with a different value or use [exceptions](https://github.com/stoplightio/spectral/blob/develop/docs/guides/6-exceptions.md).
LMK if that helped. 
I'll close the issue in the meantime.
Feel free to reopen if more help is needed.
