### ISSUE TITLE
Option to sort the OpenAPI properties

### ISSUE THREAD

**Issue by thim81** [stoplightio/spectral#1538]
**User story.**
As a OpenAPI editor, I can sort my OpenAPI properties, so that I can easier maintain my OpenAPI spec in a more consistent manner.

**Is your feature request related to a problem?**
The OpenAPI blocks can become very inconsistent if a great number of people contribute towards the spec.
YAML is a very open format, so the order is less relevant when you enter new properties.  

**Describe the solution you'd like**
To have the option to define the "sorting" in a simple manner of the sublevels of certain OpenAPI parts:
Example: Paths properties > operationID | Summary | paramaters | request body | response

That we have to option to run a command via Spectral to sort the part according to a hierarchy or another consistent manner.

**Comment by mnaumanali94** [comment]
We have discussion going on here that should address requests like these: https://github.com/stoplightio/spectral/discussions/98

**Comment by thim81** [comment]
hi @mnaumanali94 
I was not aware that this issue was still open.
Since I pitched the feature request, I created an open-source CLI [openapi-format](https://www.npmjs.com/package/openapi-format) that handles the sorting for me.

**Comment by mnaumanali94** [comment]
Oo nice - That seems useful! We might end up using it too 🙏🏼
