### ISSUE TITLE
No error message when openapi spec file does not exist

### ISSUE THREAD

**Issue by roubles** [stoplightio/spectral#1577]
**Describe the bug**
If the spec file passed in to spectral linter does not exist, spectral just says:
"No results with a severity of 'error' or higher found!"

This can be misleading in the case of a typo in the path to the file, someone may just think their file is clean.

**To Reproduce**

spectral lint /path/to/file/that/does/not/exist.yml

**Expected behavior**

If the file does not exist, spectral should print to STDERR, 'OpenAPI Spec file not found at specified location'

**Comment by P0lip** [comment]
Hey!
You can use ` --fail-on-unmatched-globs` flag.
