### ISSUE TITLE
<STDIN> in junit testsuite name tag doesn't parse in AzureDevOps Test Result Publishing

### ISSUE THREAD

**Issue by andylockran** [stoplightio/spectral#1581]
**Describe the bug**
I've used spectral to output the junit.xml file as part of a pipeline on Azure DevOps.

The AzureDevOps CI process has a pipeline step to product a test results summary page, as derived from a junit-compliant output.

Unfortunately the spectral output isn't accepted as being junit-compliant due to the error below:

2021-04-20T13:03:01.1685016Z ##[warning]Failed to read /azp/agent/_work/9/s/SPECTRAL-1618923773.xml. Error : '<', hexadecimal value 0x3C, is an invalid attribute character. Line 3, position 84.

This appears to be the <[[CDATA xxx ]]> section in the junit output, as it's rejecting the `<` from being valid xml. 

I'm trying to workout if this is invalid junit output, or a problem with the ADO junit parser.

 - Spectral version: 5.9.1
 - OS: Ubuntu

**Additional context**
If the junit schema is valid, and this is a problem with ADO, many apologies.

**Comment by andylockran** [comment]
Apologies - I was able to resolve this.

The CDATA character was fine - i'd piped the yml definition into spectral and it didn't like the name "<STDIN>" - which was causing the problem.

<testsuite package="org.spectral" time="0" tests="87" errors="0" failures="87" name="<STDIN>">

**Comment by raleigh04** [comment]
Thanks for the update and we're glad you were able to resolve your issue!
