### ISSUE TITLE
Function to validate if a contract changed between commits

### ISSUE THREAD

**Issue by johnowl** [stoplightio/spectral#1594]
**User story.**
As a developer, I can be able to be warned when a field is removed from an existing OpenAPI request or response object, so that I can avoid API contract changes.

**Is your feature request related to a problem?**
Avoid API contract changing, it sould be nice to choose what kind of changes are allowed and forbidden. Thinhs like field added or field removed.

**Describe the solution you'd like**
A function to validate OpenAPI objects between commits.

**Comment by mnaumanali94** [comment]
Hey! Spectral's geared towards applying style constraints on API specification documents. This is beyond spectral's paradigm and can potentially be better fulfilled by a diff/changelog tool. You can check out [Azure OpenAPI diff](https://github.com/Azure/openapi-diff ) or [leave an insight on our roadmap](https://roadmap.stoplight.io/c/30-notifications-activity-summary-breaking-changes-etc) for a feature we're planning inside Stoplight Platform.
