### ISSUE TITLE
Strange dockerhub release 67.67.67

### ISSUE THREAD

**Issue by languitar** [stoplightio/spectral#1611]
**Chore summary**

We received a set of renovate MRs today for a new Spectral Docker image 67.67.67. Is that release intended or a release bug?

**Additional context**

Recovering for people who have already updated to that release via Renovate is probably a hard thing due to the large jump in semver versions.

**Comment by wmhilton** [comment]
OK, v67.67.67 of the Docker image is bye-bye.
