### ISSUE TITLE
Drop `schemaPath` function

### ISSUE THREAD

**Issue by P0lip** [stoplightio/spectral#1621]
`schemaPath` function relies on Spectral's internals and is used only by AsyncAPI ruleset.
 
- [ ] Remove the SchemaPath usage in AsyncAPI ruleset.
- [ ] Create a custom function if we cannot use any other spectral function to achieve the same outcome. 
- [ ] Use the custom function in the AsyncAPI ruleset.

**Comment by philsturgeon** [comment]
This is legacy left over from the old example validation code. It should be removed and asyncapi updated to not need it.
