### ISSUE TITLE
Rule for external http(s) references

### ISSUE THREAD

**Issue by sebas2day** [stoplightio/spectral#1651]
**User story.**
I would like to have a rule where I can disallow any http(s) references but allow for example relative file references.

**Is your feature request related to a problem?**
In our solution we don't want to have specifications that have external references over http because those references can suddenly change making a specification suddenly break. We want to enforce our developers not having these references. We commit all specifications + their references as a whole in our repo.

**Describe the solution you'd like**
Some rule like `no-external-http-$ref`.

**Additional context**
NA

**Comment by mnaumanali94** [comment]
Hey! Have you tried creating a custom rule for this? You can create a custom ruleeset that extends our existing rules which are for the most common use cases/validations in OpenAPI and AsyncAPI

**Comment by sebas2day** [comment]
No not yet but that sounds like something I could definitely work with.

Nonetheless could this be something being considered as part of the core rulesets? The proposed rule probably needs more votes though :)

**Comment by mnaumanali94** [comment]
Here's a guide on creating custom rules: https://meta.stoplight.io/docs/spectral/docs/guides/4-custom-rulesets.md

> Nonetheless could this be something being considered as part of the core rulesets? The proposed rule probably needs more votes though :)

This is pretty use case specific as http references are valid. We could consider it if it gets a lot of love.

**Comment by philsturgeon** [comment]
Maybe throw up a PR or blog it. We'd love to see more people sharing their custom rules and cool things they're doing with Spectral, but we probably don't want to be adding it to the core as its valid OAS like @mnaumanali94 said. :)
