### ISSUE TITLE
Install script is broken

### ISSUE THREAD

**Issue by yli-dev** [stoplightio/spectral#1750]
**Describe the bug**
The install script at https://raw.githack.com/stoplightio/spectral/master/scripts/install.sh is not working, with error
`Error requesting. Download binary from https://github.com/stoplightio/spectral/releases/latest/download/spectral-linux`

**To Reproduce**

Run `curl -L https://raw.githack.com/stoplightio/spectral/master/scripts/install.sh | sh`

**Expected behavior**
The script should successfully install spectral binary to my machine.

**Environmen:**
 - OS: Ubuntu 18.04.5 LTS

**Comment by carbonin** [comment]
Duplicate of https://github.com/stoplightio/spectral/issues/1745 I think?

**Comment by yli-dev** [comment]
@carbonin you are right. Closing this issue.
