### ISSUE TITLE
Update to AsyncAPI Spec 2.1.0 & 2.2.0 & 2.3.0

### ISSUE THREAD

**Issue by danielkocot** [stoplightio/spectral#1759]
**User story.**
As a API designer, I can run spectral to check my AsyncAPI, nowadays I'm only able to check specs with version 2.0.0. 

**Is your feature request related to a problem?**
The new release 2.1.0 of the spec is not supported by Spectral.

**Describe the solution you'd like**
The ruleset should be extended.

https://www.asyncapi.com/blog/release-notes-2.1.0
https://www.asyncapi.com/blog/release-notes-2.2.0
https://www.asyncapi.com/blog/release-notes-2.3.0

**Comment by danielkocot** [comment]
Any updates, @P0lip? :)

**Comment by P0lip** [comment]
Hey @danielkocot.
Unfortunately no progress on this ticket has been made :(

**Comment by magicmatatjahu** [comment]
I created PR to support all 2.X.X versions of AsyncAPI - https://github.com/stoplightio/spectral/pull/2067 I didn't add any new rules (e.g. validate defined servers on a channel level in 2.2.0 version), as this will be added in other PRs. This PR only adds spec JSON Schema validation.

cc @danielkocot @P0lip

**Comment by danielkocot** [comment]
Thanks @magicmatatjahu!
