### ISSUE TITLE
Update rulesets docs to show how to ignore paths for specific rules

### ISSUE THREAD

**Issue by gonzadocarmo** [stoplightio/spectral#1769]
**Chore summary**
Update documentation to reflect how to ignore rules for specific properties/fields/paths.

**Additional context**
See impl here: https://github.com/stoplightio/spectral/issues/1018#issuecomment-601011695
https://github.com/stoplightio/spectral/pull/939/commits/014806269c4b533264c9529bebfc1c76312782e3

**Comment by P0lip** [comment]
Hey!
It's available here https://github.com/stoplightio/spectral/blob/develop/docs/guides/4-custom-rulesets.md#overrides

Example:

```json
{
  "rules": {
    "valid-thing": {
      "given": "$..foo",
      "then": {
        "function": "truthy"
      }
    }
  },
  "overrides": [
    {
      "files": ["**#/foo"],
      "rules": {
        "valid-thing": "off"
      }
    },
    {
      "files": ["**#/bar/foo"],
      "rules": {
        "valid-thing": "hint"
      }
    }
  ]
}
```

Instead of `**`, you can also specify any other glob pattern that matches a particular file.

**Comment by gonzadocarmo** [comment]
thanks @P0lip 
I was thinking about bringing this back.. https://github.com/stoplightio/spectral/pull/1770/commits/aecea914842f3a0906ddb4686aa8a0c8e0820344

how would the JSON config above would look like to disable the rule "my-rule-name" for this path "#/components/schemas/Item/properties/LASTNAME" from the example in the PR diff?

**Comment by P0lip** [comment]
This would be something more or less as follows
```yaml
extends: spectral:oas
overrides:
  "**#/components/schemas/Item/properties/LASTNAME":
    rules: 
      my-rule-name: off
```

**Comment by gonzadocarmo** [comment]
Well... that's exactly what this change is about. I added that as an example on the rulesets doc file.
I was asking how that would look like with the "overrides" example you provided? Is there a way to use overrides for this? If not, I'd like to have that example added into the doc. Thoughts?

**Comment by P0lip** [comment]
Ah sorry, I mispelled.
I meant to state `overrides` there. Updated the example.

**Comment by gonzadocarmo** [comment]
I see. How about repurposing this PR to add that example  into https://github.com/stoplightio/spectral/blob/develop/docs/guides/4-custom-rulesets.md#overrides?
I see there's one example including files and not specific paths/properties??

**Comment by P0lip** [comment]
@gonzadocarmo yup, that would be great!

**Comment by P0lip** [comment]
Hey! In #1772 I made it so that the old syntax works again, so I believe we can close this issue for now.
If you'd like to update the documentation, you're still more than welcome to do it!
Thanks and hit me up if you have any questions.
