### ISSUE TITLE
Disable recursive resolution in spectral

### ISSUE THREAD

**Issue by rahulgopal88** [stoplightio/spectral#1778]
**User story.**
As a spectral developer, I want to disable recursive resolution, so that I can use my custom rule set to only parse the source code of relevant API

**Is your feature request related to a problem?**
Disable the resolution of $ref. Currently on running a spectral linter, all the $ref are resolved and then the rule set is applied. This can lead to a lot of redundant warnings/errors which are not in the current file.

**Describe the solution you'd like**
Please disable the parsing of the all $ref. A feature to parse and run the linter only on the source code would be great.

We have already tried `:resolved: false` . This does not seem to meet our need.

**Comment by kscheirer** [comment]
`resolved: false` is the correct way to do this. Can you post the rule and result you are seeing?

**Comment by P0lip** [comment]
I'd say `resolved` set to `false` is likely what you're up for here.

Alternatively, one can try providing a custom ref resolver that's no-op, meaning it doesn't attempt to resolve any $refs.
This one is a bit hacky however, and you probably don't want to do this.

**Comment by P0lip** [comment]
I'll close this one out. If the answers above weren't sufficient, please reopen the ticket and provide us with more informations.
Thank you!
