### ISSUE TITLE
Certain valid patterns are not accepted by schema function 

### ISSUE THREAD

**Issue by P0lip** [stoplightio/spectral#1782]
**Describe the bug**

In some cases, Ajv bails upon a valid pattern.
It's presumably an issue with Ajv, or, with the way we use Ajv.

**To Reproduce**

1. Run the following snippet
```js
const Ajv = require('ajv');
const ajv = new Ajv();
const assert = require('assert');

const schema = {
  type: 'string',
  pattern: '^[A-Za-z0-9\\-\\_]',
};

assert.ok(ajv.validate(schema, 'test-case-1'));
```
2. Exits with non-zero code

**Expected behavior**

Exits with a zero-code

Related to https://github.com/stoplightio/platform-internal/issues/7541

**Comment by mmiask** [comment]
My findings so far: the provided snippet fails directly in:
```
/spectral/node_modules/ajv/dist/vocabularies/validation/pattern.js:19:89)
```

The error message we get is
```
SyntaxError: Invalid regular expression: /^[A-Za-z0-9\-\_]/: Invalid escape
```

What causes the failure is a provided regex pattern `'^[A-Za-z0-9\\-\\_]'`, to be more specific `\\_` fragment.
When using string literal as a pattern for new `RegExp('pattern', 'u')` ,  the backslash is an escape, so to use it in the regular expression, we need to escape it at the string literal level. `/a\*b/` and `new RegExp("a\\*b")` create the same expression.
So we can either use `String.raw`stringliteral`` and somehow pass it to `ajv` as option, or replace `\\` with `\\\\`.

**Comment by raleigh04** [comment]
Related to Spectral not working with BIG APIs.  (#7541)
