### ISSUE TITLE
The v6.0.0 docker image is not being pushed.

### ISSUE THREAD

**Issue by machisuke** [stoplightio/spectral#1786]
**Chore summary**
The v6.0.0 docker image is not being pushed.

https://hub.docker.com/r/stoplight/spectral/tags?page=1&ordering=last_updated

**Tasks**
- [ ] Tag v6.0.0 to push the v6.0.0 dokcer image.

**Additional context**

This is the circleci job thas releases images to docker hub.
https://github.com/stoplightio/spectral/blob/45de601dc7feba346b79417e7db32cb00181ab39/.circleci/config.yml#L254-L259

**Comment by machisuke** [comment]
@P0lip Could you please confirm?

**Comment by P0lip** [comment]
Hey @machisuke
I can confirm it's not pushed - my apologies for the troubles.
I'll try to push the tag later this week / early next week. Prior to that, a few minor changes will have to be applied, but this shouldn't take long.
I will make sure to let you know once the docker image is out.
Thank you for your patience and once again sorry for the inconvenience.

**Comment by jgumpert** [comment]
Hi all,

@P0lip, is there any proposed date for the release of version 6.0.0?

**Comment by hiddewie** [comment]
The NPM module of version 6.0.0 also has not been published yet. The last 6.0.0 alpha version is 6.0.0-alpha3.

ref https://www.npmjs.com/package/@stoplight/spectral

If needed I can make a separate issue because this one is about the Docker image.

**Comment by jgumpert** [comment]
Yes @hiddewie, please.
It would be great to have version 6.0.0 stable, as soon as posible.

**Comment by hiddewie** [comment]
@emilioSp opened #1832 which seems the same issue

**Comment by P0lip** [comment]
Heyo, I'll try to get this done next week!

**Comment by P0lip** [comment]
Hey.
The latest image is available.
https://hub.docker.com/r/stoplight/spectral/tags?page=1&ordering=last_updated
