### ISSUE TITLE
[Feature] Disallow changing values

### ISSUE THREAD

**Issue by yordis** [stoplightio/spectral#1792]
**User story.**
As a programmer, I would like to disable the ability to modify operations ID

**Is your feature request related to a problem?**
If somebody changes the operation ID by mistake, or intentionally; it will cause breaking changes and compilation failures in our setup.

**Describe the solution you'd like**
Add a rule where we can disable the ability to change the operation ID. I thought maybe be able to point the rule to some cache file version or something like that, where the rule could compare the values

**Additional context**

Having some way to compare values with cache data could potentially be used to create rules for disallowing breaking changes in general beside the operation id such as changing the type of an schema.

**Comment by P0lip** [comment]
Hey!
Unfortunately, this would be probably out of scope for Spectral.
It's a similar case to https://github.com/stoplightio/spectral/issues/1504
You can check out the proposed solution there to see if it's a match for you.

**Comment by yordis** [comment]
Could that be reconsidered?

The custom plugin could expect a file path, and try to compare both values.

We have other files that are not OpenAPI at the moment that need such a feature as well.

**Comment by P0lip** [comment]
> Could that be reconsidered?

I'll leave the call to our PM, @mnaumanali94

**Comment by mnaumanali94** [comment]
@yordis I understand that disallowing breaking changes is a need across many places, but it is beyond the scope of what Spectral is built for. Spectral primarily aims at linting JSON/YAML files to adhere to standards. Comparing files isn't something that we have any plans to add to Spectral. 

Apologies that Spectral won't work out for you for this particular use case.

**Comment by yordis** [comment]
🤷🏻 hopefully can make a plugin work, thank you regardless.
