### ISSUE TITLE
'ownKeys' on proxy: trap returned duplicate entries

### ISSUE THREAD

**Issue by maxbec** [stoplightio/spectral#1814]
**Describe the bug**
On execution of `spectral lint` on a local yml file this error pop's up:
`'ownKeys' on proxy: trap returned duplicate entries`

**To Reproduce**

1. Run this CLI command `spectral lint` behind a proxy server.

**Expected behavior**
Error like above.

**Environment (remove any that are not applicable):**
 - Library version: latest
 - OS: Windows 10

**Comment by P0lip** [comment]
Hey!
Any chance you could provide us the document you use?

**Comment by maxbec** [comment]
Unfortunately not! :/ But maybe you can give me a hint where to look.

**Comment by P0lip** [comment]
I have a hunch it might be caused by https://github.com/stoplightio/ordered-object-literal/blob/master/src/index.mjs#L38.
Any chance you have duplicate properties in your document? is it a YAML or JSON doc?

**Comment by maxbec** [comment]
Thank you. I will have a look. It is YAML.

**Comment by P0lip** [comment]
Have you had the chance to look into this yet?
I'd be very happy to dive into it but would need at least a small reproducible example.
If you could come up with any sample, that'd be great.

**Comment by watson20201** [comment]
Hi, I to have the same issue using json files. Is it possible to log which key is duplicated? The last time I ran it was on the 20 Sep it was fine. Running Linter on that same commit now fails.

**Comment by P0lip** [comment]
> Is it possible to log which key is duplicated

this would be a JSON/YAML property that's a duplicate, so you should be able to look it up in some text editor.

> running Linter on that same commit now fails.

Do you have some $refs there that could have changed in the meantime?

**Comment by watson20201** [comment]
I have been using Visual Code with the JSON editor plugin and that normally highlights any duplicated properties. But in this case nothing is showing as an error.

**Comment by P0lip** [comment]
Do you have any $refs somewhere?

**Comment by watson20201** [comment]
Yes, we are using $refs quite a lot. Our schemas are highly normalised and there are around 50 definitions. An example is we have a base date-time schema which is reference by a number of other schemas.
eg 

    "date-time-extended": {
      "$ref": "../../Base/DataTypes.json#/components/schemas/date-time-extended"
    },
...
    "lastOccupiedDate": {
      "$ref": "#/components/schemas/date-time-extended"
    },

Visual Studio Code normally highlights the error when there are duplicate $refs with the same keys. 
Is it possible to log the key and the document name where Spectral thinks there are duplicate properties?

**Comment by P0lip** [comment]
> Visual Studio Code normally highlights the error when there are duplicate $refs with the same keys.

What I meant was that the referenced documents may have some $refs with duplicate props.

> Is it possible to log the key and the document name where Spectral thinks there are duplicate properties?

Not quite, however, if you can consistently reproduce the error, I'd be happy to handle over a custom Spectral instance with some more verbose logging.
Would that work?

**Comment by watson20201** [comment]
Yes, that will be great if you can create a custom instance with more verbose logging.

**Comment by P0lip** [comment]
@watson20201 
here you go https://drive.google.com/drive/folders/1qxClrQB54Qa6cGLYC_RpLS-ma8im5ld6?usp=sharing.
It's the same kind of a binary as in here https://github.com/stoplightio/spectral/releases/tag/v6.1.0, just with a bit of more logging.
You can run it as any other Spectral instance - no extra flag is required.

**Comment by watson20201** [comment]
Thanks @P0lip, I will give that a go today.

**Comment by watson20201** [comment]
Hi @P0lip, below is the output from the instrumental version of the Spectral version.

spectral-win.exe lint **/*.json -r Linter/Common.Rules.yml
Error running Spectral! 'ownKeys' on proxy: trap returned duplicate entries
at entries
at _process        …snapshot/spectral/packages/ruleset-migrator/src/index.ts:90  Object.entries(input).map(async ([key, value]) => {
at                 …snapshot/spectral/packages/ruleset-migrator/src/index.ts:91  const propertyValue = await _process(value, hooks, `${path}/${key}`);     
at map
at _process        …snapshot/spectral/packages/ruleset-migrator/src/index.ts:90  Object.entries(input).map(async ([key, value]) => {
at async process   …napshot/spectral/packages/ruleset-migrator/src/index.ts:105  return (await _process(input, hooks, '')) as namedTypes.ObjectExpression; 
at migrateRuleset  …snapshot/spectral/packages/ruleset-migrator/src/index.ts:57  tree.ruleset = await process(ruleset, hooks);
at getRuleset      …ral/packages/cli/src/services/linter/utils/getRuleset.ts:53  const migratedRuleset = await migrateRuleset(rulesetFile, {
at lint            …shot/spectral/packages/cli/src/services/linter/linter.ts:14  const ruleset = await getRuleset(flags.ruleset);

**Comment by P0lip** [comment]
@watson20201 yes, that's really helpful, thank you.
I know where the issue lies now.

**Comment by P0lip** [comment]
There's a fix over here https://github.com/stoplightio/spectral/commit/c65ba50ba8050e260a893c92d2237e0eaf71fd3a
I'm going to create a PR later this week.
In the meantime, if you need a workaround you can rename the dropped rules as described here https://github.com/stoplightio/spectral/blob/develop/docs/migration-guides/6.0.md#rulesets

**Comment by watson20201** [comment]
Thanks @P0lip for your quick response in getting a fix out.

**Comment by ralphpina** [comment]
@P0lip any plans to open a PR with your fix?

**Comment by P0lip** [comment]
I put the PR here https://github.com/stoplightio/spectral/pull/1912

Overall, the issue is caused by the fact you use rules that are no longer supported in 6.x.
Please refer to [migration guide](https://github.com/stoplightio/spectral/blob/develop/docs/migration-guides/6.0.md#rulesets) to learn more about it.
The fact we handle them in ruleset-migrator is to ease the migration process, but you'll inevitably need to use the other rules as indicated in the documentation.
