### ISSUE TITLE
Spectral dependency vulnerabilities

### ISSUE THREAD

**Issue by benjamin-mogensen** [stoplightio/spectral#1818]
**Chore summary**
Update dependencies so that they use later versions that are not having any security vulnerabilities

**Additional context**
In Github we have received two dependabot warnings for @stoplight/spectral@6.0.0-alpha3 (same version that Stoplight Desktop is using) one for immer and one for pac-resolver. Not sure how these are normally fixed - but is it possible to release a new version of Spectral that does not have these vulnerabilities?

![image](https://user-images.githubusercontent.com/73802221/132089866-38408647-6006-47d3-aa22-bde5f777de02.png)

**Comment by Linuus** [comment]
Any updates on this? There's a high severity security issue for pac-resolver that has been fixed in 5.0 and we can't update since spectral-cli has a dependency on 4.x.

**Comment by P0lip** [comment]
>  @stoplight/spectral@6.0.0-alpha3 (same version that Stoplight Desktop is using)

We use `@stoplight/spectral-core` in Studio. If you're a cli user, you can use `@stoplight/spectral-cli`.

>  There's a high severity security issue for pac-resolver that has been fixed in 5.0 and we can't update since spectral-cli has a dependency on 4.x.

I'm about to update dependencies in spectral-cli.

**Comment by P0lip** [comment]
Feel free to upgrade to 6.0.1.

**Comment by P0lip** [comment]
We should be good now!

**Comment by Linuus** [comment]
> We should be good now!

Awesome, thanks! 👍
