### ISSUE TITLE
Spectral throws for property with name starting with "@" that has example

### ISSUE THREAD

**Issue by mikekistler** [stoplightio/spectral#1827]
**Describe the bug**

Spectral throws an exception on an API doc with a schema property where the name starts with "@" and there is an example.
E.g.:
```
{
    "swagger": "2.0",
    "info": {
      "title": "trouble",
      "version": "1.0"
    },
    "host": "localhost:8000",
    "schemes": [ "http", "https" ],
    "paths": {
    },
    "definitions": {
      "Trouble": {
        "description": "Trouble",
        "properties": {
          "@foo": {
            "type": "string",
            "example": "bar"
          }
        }
      }
    }
  }
```

**To Reproduce**

1. Given the OpenAPI/AsyncAPI document above
2. Run this CLI command
  ```
  spectral lint trouble.json
  ```
3. See error
  ```
OpenAPI 2.0 (Swagger) detected
TypeError: Unknown value type f
    at JSONPath._trace (C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:766:17)
    at C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:745:23
    at C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:909:9
    at Array.forEach (<anonymous>)
    at JSONPath._walk (C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:908:24)
    at JSONPath._trace (C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:743:12)
    at JSONPath._trace (C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:698:19)
    at C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:706:23
    at C:\Users\mikekistler\AppData\Roaming\npm\node_modules\@stoplight\spectral\node_modules\jsonpath-plus\dist\index-umd.js:909:9
    at Array.forEach (<anonymous>)

c:/Users/mikekistler/Projects/mkistler/spectral-test/trouble.json
  1:1   warning  openapi-tags            OpenAPI object should have non-empty `tags` array.
  3:12  warning  info-contact            Info object should contain `contact` object.                             info
  3:12  warning  info-description        OpenAPI object info `description` must be present and non-empty string.  info
 12:17  warning  oas2-unused-definition  Potentially unused definition has been detected.                         definitions.Trouble

✖ 4 problems (0 errors, 4 warnings, 0 infos, 0 hints)

  ```

**Expected behavior**

No exception.

**Environment**
 - Library version: Spectral@5.9.2, but also happens with spectral-cli@6.0.0 just not as obvious
 - OS: Windows 10 (but also happens on MacOS)

**Additional context**

The problem does not occur without **both** the "@" in the property name and an example.  Hopefully that is helpful in identifying the root of the problem.

**Comment by P0lip** [comment]
Yeah, this is an issue with JSONPath-plus.
I swapped JSONPath-plus with our own implementation -> https://github.com/stoplightio/spectral/pull/1785
It's been merged and released, but we are still to release a new standalone package (cli).
That said, once released, the issue should be gone.
I'll let you know when that happens.

**Comment by P0lip** [comment]
[Confirmed](https://github.com/stoplightio/spectral/commit/4e8da71a36526e51fae06be0a13db5dd77ad77d6#diff-c0837cae965b2ef8f3718d74589b20eeb204063b2376c4d01a1303299523b6ed) to be fixed in the recent `@stoplight/spectral-core` package.

I also gave it a try live and works.

![image](https://user-images.githubusercontent.com/9273484/133230487-25300b04-ebb1-4775-b3e6-9b89e41820ee.png)

The fix will be propagated automatically when a new version of CLI package is released.
If you don't use the binaries / docker images, you should be able to simply reinstall `@stoplight/spectral-cli` for that newer version of spectral-core to be picked up. A npm/yarn cache might need to be wiped beforehand.
