### ISSUE TITLE
spectral 6.0.0 on npm

### ISSUE THREAD

**Issue by emilioSp** [stoplightio/spectral#1832]
Hi guys! How are you? I hope you are doing well.

@P0lip I'm sorry to bother you but for an urgent project, I should use the open api 3.1.0 specification.

I saw that you have already implemented its support in the spectral version 6.0.0, but on npm there is still the old spectral version (5.9.2)

Do you have in plan to publish the 6.0.0 version on npm in a short time?

Thank you very much!

**Comment by hiddewie** [comment]
Ref https://github.com/stoplightio/spectral/issues/1786 and specifically https://github.com/stoplightio/spectral/issues/1786#issuecomment-920839529

**Comment by mnaumanali94** [comment]
Ref: #1836

**Comment by P0lip** [comment]
@emilioSp what Nauman said.
IIRC you happened to use the JS API of Spectral, so you might be interested in `@stoplight/spectral-core` which doesn't have any CLI specific code.
LMK if you have any questions

**Comment by emilioSp** [comment]
@P0lip thanks! now it's clear! Indeed I use both the cli both the core 😁

I've solved the problem for the cli using https://www.npmjs.com/package/@stoplight/spectral-cli
