### ISSUE TITLE
Can't install Spectral 6.0.0 on macOS Big Sur

### ISSUE THREAD

**Issue by AX-LLaidley** [stoplightio/spectral#1855]
**Describe the bug**

When I tried to install Spectral 6.0.0 on macOS Big Sur 11.6, it shows up as a document, rather than a pkg or dmg file. When I try to open this file, my Mac first tries to open it in TextEdit, and then I get an error that "spectral-macos cannot be opened because it is from an unidentified developer. macOS cannot verify that this app is free from malware."

**To Reproduce**

1. Download spectral-macos from https://github.com/stoplightio/spectral/releases/tag/v6.0.0
2. Click on the downloaded file in Chrome or in Finder.
3. See error

**Expected behavior**
Expected behavior was that I could download spectral-macos, open the file, and install Spectral 6.0.0

**Screenshots**

<img width="264" alt="Screen Shot 2021-09-29 at 11 01 33 AM" src="https://user-images.githubusercontent.com/81706296/135295774-55fad895-9e10-44c7-b0c4-740cda187b1d.png">

**Environment (remove any that are not applicable):**
 - Library version: 6.0.0
 - OS: macOS Big Sur 11.6
 - Browser: Google Chrome Version 94.0.4606.61 (Official Build) (x86_64)

**Comment by P0lip** [comment]
Hey!
This is not an installer.
Spectral doesn't offer any GUI and is supposed to be used from the terminal.
Once it's downloaded, one can open the terminal and run `./spectral-macos lint` 
We have a brief overview available [here](https://github.com/stoplightio/spectral/blob/develop/docs/guides/2-cli.md)
