### ISSUE TITLE
Cannot find module '@stoplight/spectral-ruleset-migrator'

### ISSUE THREAD

**Issue by stuft2** [stoplightio/spectral#1884]
**Describe the bug**
```shell
Error: Cannot find module '@stoplight/spectral-ruleset-migrator'
```

Spectral v6.0.0 does include 
```
"@stoplight/spectral-ruleset-migrator": "^1.1.0"
```
while Spectral v6.0.1 does not.

However, [Line 7](https://github.com/stoplightio/spectral/blob/f1932c4058a7024af178002a9d803839db6d95ed/packages/cli/src/services/linter/utils/getRuleset.ts#L7) of `@stoplight/spectral-cli/src/services/linter/utils/getRuleset.js` still requires `@stoplight/spectral-ruleset-migrator`.

**To Reproduce**

1. Given any OpenAPI v2 or v3 document
2. Run this CLI command: lint
3. See error

**Expected behavior**
Spectral should lint my OpenAPI or Swagger documents

**Environment (remove any that are not applicable):**
 - Library version: 6.0.1
 - OS: MacOS

**Comment by P0lip** [comment]
True, I must have accidentally renamed `-bundler` to `-migrator`.
The fix will be out tomorrow, in early afternoon CET.
In the meantime, feel free to install `@stoplight/spectral-ruleset-migrator` globally - this will fix the issue until a new version is released.
I'll close this one out - will respond here tomorrow once 6.0.2 or 6.1.0 is out.

**Comment by P0lip** [comment]
@stuft2 apologies for the delay, but it's out.
