### ISSUE TITLE
can't fetch spectral custom ruleset over https with self signed certificate in certificate chain

### ISSUE THREAD

**Issue by OnimeNoKyo** [stoplightio/spectral#1888]
Describe the bug

Spectral-cli fails to fetch custom ruleset that is loaded over HTTPS.

To Reproduce

    With spectral-cli v5.9.2
    Given any OpenAPI document
    Run this CLI command

spectral lint -r https://internal-bitbucket-repository/raw/rulesets/main-ruleset.yaml open-api.yml

    See error

Could not parse https://internal-bitbucket-repository/raw/rulesets/main-ruleset.yaml: request to https://internal-bitbucket-repository/raw/rulesets/main-ruleset.yaml failed, reason: self signed certificate in certificate chain

Expected behavior

    With spectral-cli v5.9.2
    Given any OpenAPI document
    Run this CLI command (same as above)

spectral lint -r https://internal-bitbucket-repository/raw/rulesets/main-ruleset.yaml open-api.yml

    See good results

OpenAPI 3.x detected
No results with a severity of 'error' or higher found!

Environment (remove any that are not applicable):

    Library version: 5.9.2
    OS: reproduced on Windows 10

**Comment by P0lip** [comment]
I'm afraid this is not something we'd address in the Spectral itself, as doing so may introduce a security flaw.
That error is presumably raised by [OpenSSL](https://www.openssl.org/docs/man1.1.0/man3/X509_STORE_CTX_set_current_cert.html).
The solution here would be to follow the steps [here](https://stackoverflow.com/a/12180757).
Alternatively, if you do know what you're doing, set [NODE_TLS_REJECT_UNAUTHORIZED](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value) env variable to `'0'`.

**Comment by tejasj654** [comment]
Where does spectral look for certificates? I have a trusted certificate available for the request I am making but not sure where to put it.

**Comment by P0lip** [comment]
It follows Node.js in that respect, but you can manually override it using [SSL_CERT_DIR](https://nodejs.org/api/cli.html#ssl_cert_dirdir) or [SSL_CERT_FILE](https://nodejs.org/api/cli.html#ssl_cert_filefile)
