### ISSUE TITLE
Spectral outline and plan

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/spectral#1899]
**Chore summary**
Prepare a plan for revising the Spectral doc.

**Tasks**
- Review Discord feedback.
- Prepare draft outline/TOC.
- Review with Phil.

**Draft Outline**
https://www.notion.so/stoplight/Draft-Spectral-Outline-aa57815825fd457a923a6a88e14f1b11

**Comment by pamgoodrich** [comment]
@philsturgeon and @mnaumanali94 : This is the initial draft of a proposed reorg and sprucing up of the Spectral doc. Nauman, Phil and I went over it this morning and agreed on at least the Getting Started and Advanced Topics sections. Can we talk about this when we meet on Monday?

**Comment by mnaumanali94** [comment]
For sure. I'll try and leave some feedback here before that.
