### ISSUE TITLE
Support for 2.1.0 and 2.2.0 of AsyncAPI

### ISSUE THREAD

**Issue by galvo** [stoplightio/spectral#1919]
**User story.**
Can support be added for linting of 2.1.0 and 2.2.0 of Asyncapi?

https://www.asyncapi.com/blog/release-notes-2.1.0
https://www.asyncapi.com/blog/release-notes-2.2.0

**Comment by P0lip** [comment]
Hey!
Thanks for the issue.
Since we have a similar one https://github.com/stoplightio/spectral/issues/1759 already I'll merge yours with the existing one.
