### ISSUE TITLE
exclusiveMaximum must be number

### ISSUE THREAD

**Issue by galvo** [stoplightio/spectral#1939]
**Describe the bug**
Version 6.1.0 is incorrectly expecting exclusiveMaximum to be a number

**To Reproduce**

1. Given this OpenAPI spec

```
openapi: 3.0.2
info:
  title: Test
  description: |
    My Test API
  version: "0.0.1"
  contact:
    name: Me
    url: https://me.com
    email: me@me.com
  license:
    name: My License
    url: http://mylicense.com
tags:
  - name: Test
    description: "My Test"
servers:
  - url: "{protocol}://{server}:{port}"
    description: Internal API
    variables:
      protocol:
        enum:
          - "http"
          - "https"
        default: "http"
      server:
        default: "my-service"
      port:
        enum:
          - "80"
          - "443"
        default: "80"
paths:
  "/test":
    get:
      tags:
        - Test
      summary: Test exclusiveMaximum
      operationId: "testExclusiveMaximum"
      description: Get Problem
      responses:
        "200":
          description: Test exclusiveMaximum
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      description: My test schema
      properties:
        status:
          type: integer
          format: int32
          description: HTTP status code
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: Test string

```

2. Run the docker command with a ruleset defined as follows

extends: [[spectral:oas, all]]

3. See error

The following error is returned

 61:20  error  oas3-valid-schema-example  schema is invalid: data/exclusiveMaximum must be number  components.schemas.Test.properties.status.example

✖ 1 problem (1 error, 0 warnings, 0 infos, 0 hints)

**Expected behavior**
I expect that there would be no error for this field as exclusiveMaximum is of type boolean see https://swagger.io/docs/specification/data-models/data-types/

**Environment (remove any that are not applicable):**
 - Library version: 6.1.0
 - OS: Docker

**Comment by P0lip** [comment]
Thanks for the ticket!
I'm happy to tell you it's been fixed in https://github.com/stoplightio/spectral/issues/1894.
We're still to release a new docker version.
I'll let you know once it's out. In the meantime, I'll close this one out.

**Comment by galvo** [comment]
Excellent thank you

**Comment by galvo** [comment]
And the npm and Docker version number and releases aligned?

**Comment by P0lip** [comment]
> And the npm and Docker version number and releases aligned?

The code of the CLI package is the same, but the versions of dependencies may differ, depending on how they get installed by npm/yarn.
