### ISSUE TITLE
Prototype Pollution in node-jsonpointer

### ISSUE THREAD

**Issue by benjamin-mogensen** [stoplightio/spectral#1947]
**Chore summary**
Update jsonpointer pacakge to >=5.0.0 to avoid warnings on @stoplight/spectral-core, @stoplight/spectral-functions, @stoplight/spectral-rulesets

**Tasks**
- [ ] Update jsonpointer package to >=5.0.0 in @stoplight/better-ajv-errors

**Additional context**
NA

**Comment by P0lip** [comment]
I'll update it when I have a chance, but overall our usage of `jsonpointer` doesn't impose any risk, as we only use `get` function (hence we only make a read only usage of it), while the one that's potentially vulnerable is `set`.

**Comment by benjamin-mogensen** [comment]
OK thanks - I am sure its no big risk. I just see the vulnerability alerts in our GitHub repos and when doing the `npm audit` so thought I would raise it with you guys :)
