### ISSUE TITLE
Document missing schema functions

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/spectral#1961]
These schema function options are missing from the doc:
    
    
- **Location: schema function:** dialect iconXXX
    
    Recommended text: @Nauman Ali  to provide. Pam will add to Spectral doc.

This option is internal and should not be added to the doc:
    
- **Location: schema function:** prepareResults iconXXX
    
    Recommended text: @Nauman Ali to provide. Pam will add to Spectral doc.

They need to go here: 
https://meta.stoplight.io/docs/spectral/ZG9jOjExNg-core-functions#schema

Look for text here:
https://www.notion.so/stoplight/Shared-Style-Guide-Help-Text-4d29982fb0214befa7b77a4673f92d0c

**Comment by P0lip** [comment]
> Location: schema function: prepareResults iconXXX

@mnaumanali94 @pamgoodrich this is for an internal, don't document it, we shouldn't expose it in the UI either

**Comment by pamgoodrich** [comment]
@P0lip Thank you. It is exposed in shared style guides now. I'll add a note to the bug list that it should not be exposed. @mnaumanali94

**Comment by pamgoodrich** [comment]
@P0lip : If you can add some info about the dialect option to this issue, I can give help text to the UI team and add info to the Spectral doc.

**Comment by P0lip** [comment]
`draft` - the JSON Schema draft used by function. Valid values are: 'auto', 'draft4', 'draft6', 'draft7', 'draft2019-09', 'draft2020-12'.


---

On a side note - is there any reason we'd keep them in some doc?
We should keep them in the schema in the Spectral codebase itself. This way the values are not hardcoded and users can annotate their own functions.

**Comment by mnaumanali94** [comment]
There are a couple of things here:

Spectral documentation:
That's manually generated so we should document them there for sure. 

Help text in Studio for new editor:
We can pick that up from JSON schema.

**Comment by P0lip** [comment]
> That's manually generated so we should document them there for sure.

we could and probably should use json schemas we have for that. This way we don't need to update docs manually. 

Our existing documentation on functions doesn't have anything that couldn't be expressed in JSON Schema

**Comment by mnaumanali94** [comment]
How would we do that in meta currently? 

Once we have docs for Style guides, we could potentially generate it. Currently I think manual is the only way to go.

**Comment by P0lip** [comment]
> How would we do that in meta currently?

I mean, we'd have a script somewhere in this repo that would generate the markdown file based on the schemas we have.
Super simple to implement

**Comment by mnaumanali94** [comment]
Agree but style guide docs would be a thing by end of year. Maybe we just wait for that. 🤷‍♂️

**Comment by P0lip** [comment]
> Agree but style guide docs would be a thing by end of year. Maybe we just wait for that. 🤷‍♂️

but why would we want to maintain docs if we can get everything from the schema and stay up to date?
Feels nice to have no need to constantly update docs anytime we change the behavior.

**Comment by pamgoodrich** [comment]
@P0lip : I believe this has been resolved. Can I close this issue?

**Comment by P0lip** [comment]
Yes, I think we're good here
