### ISSUE TITLE
To visit multiple specs in one rules

### ISSUE THREAD

**Issue by jianyexi** [stoplightio/spectral#1968]
**User story.**
As a rule developer, I want to check multiple specs in one rules  , so that I can using linter to avoid issues that only encounter in multiple specs

**Is your feature request related to a problem?**
we want to ensure the 'operationId' is unique among multiple swaggers. The spectral can't do it

**Describe the solution you'd like**
the rule function can visit all the inputs from the CLI , like given A,B,C 3 specs as inputs, when linting A, we can pass  B,C   as a parameter to the rule function , when linting B, AC as the parameter

**Additional context**

**Comment by P0lip** [comment]
I'm uncertain whether this is something we'd handle in Spectral.
I'll let @mnaumanali94 have the final call on this one.

FWIW, it might be possible to cover that scenario with a custom function. Each custom function has access to `documentInventory`, which contains all documents that Spectral processes.

**Comment by jianyexi** [comment]
As far as I know, the `documentInventory` only take a document in its constructor, seems the mapping between the input swaggers and instances of `documentInventory` is 1:1 ?

**Comment by P0lip** [comment]
If you take 3 separate documents, then indeed it may turn out to be sufficient if the cache is missed over here https://github.com/stoplightio/spectral/blob/bef44b5df3f2e4b91913c00f81ebfed7fab4231b/packages/core/src/documentInventory.ts#L59
You can give it a shot tho.
