### ISSUE TITLE
Enabling oas3-parameter-description gives error

### ISSUE THREAD

**Issue by m-mohr** [stoplightio/spectral#1971]
**Describe the bug**

I'm adding `oas3-parameter-description` in my config and it results in a CLI error:

> `Cannot read property 'in' of null`

**To Reproduce**

1. Given this OpenAPI/AsyncAPI document: https://github.com/Open-EO/openeo-api/blob/spectral6/openapi.yaml
2. and the config file: https://github.com/Open-EO/openeo-api/blob/spectral6/.spectral.yml (this doesn't give an error, you need to activate `oas3-parameter-description: true` first)
2. Run this CLI command: spectral lint openapi.yaml
3. See error given above

**Expected behavior**
No error message, but instead a validation/lint result.
This worked before in 5.x, but got broken once I migrated vom 5 to 6.1.

Relevant line seems to be: https://github.com/stoplightio/spectral/blob/d6e2801a920499eba84e6e6fae3b9538713a27ec/packages/rulesets/src/oas/index.ts#L614

**Environment (remove any that are not applicable):**
 - Library version: 6.1.0
 - OS: Windows 10

**Comment by m-mohr** [comment]
Not sure I understand 
`      given: "$..[?(@parentProperty !== 'links' && @.parameters)]['parameters'].[?(@.in)]",`
correctly, but should that be:
`      given: "$..[?(@parentProperty !== 'links' && @.parameters)]['parameters'].[?(@.description)]",`
?

**Comment by P0lip** [comment]
@m-mohr yup, correct. Will fix.
As of 6.x one has to be mindful about accessing properties - if there's a `null` somewhere, it'll just throw an exception if you try to read the property.
