### ISSUE TITLE
Update json-schema dependency in core

### ISSUE THREAD

**Issue by Linuus** [stoplightio/spectral#1999]
**Chore summary**

Update json-schema dependency to > 0.4 as all version below it has security issues.
See: https://github.com/advisories/GHSA-896r-f27r-55mw

**Tasks**
- [ ] Bump json-schema in core

**Comment by Linuus** [comment]
@P0lip Can we also bump the dependency in cli? It still requires core 1.5.1 so we still have the json-schema issues:
https://github.com/stoplightio/spectral/blob/develop/packages/cli/package.json#L39

**Comment by P0lip** [comment]
It's `^1.5.1` tho, so you should be able to do `yarn upgrade @stoplight/spectral-core` or the npm equivalent.
Or do you use Docker images / binaries?

**Comment by Linuus** [comment]
> It's `^1.5.1` tho, so you should be able to do `yarn upgrade @stoplight/spectral-core` or the npm equivalent. Or do you use Docker images / binaries?

Ah right, thanks!

**Comment by P0lip** [comment]
@Linuus The docker image as well as the binaries are out!
I'm sorry it took so long.
