### ISSUE TITLE
Require of @stoplight/spectral-core 1.7.0 fails to error node js 16

### ISSUE THREAD

**Issue by Havunen** [stoplightio/spectral#2002]
usage:

```
const { Spectral, isOpenApiv2, isOpenApiv3, mergeRules } = require('@stoplight/spectral-core');
```

results =>

```
    Cannot find module 'nimma/legacy' from 'node_modules/@stoplight/spectral-core/dist/runner/runner.js'

    Require stack:
      node_modules/@stoplight/spectral-core/dist/runner/runner.js
      node_modules/@stoplight/spectral-core/dist/runner/index.js
      node_modules/@stoplight/spectral-core/dist/spectral.js
      node_modules/@stoplight/spectral-core/dist/index.js
      src/spectral/utils/spectral-validator.js
      src/cli-validator/utils/validator.js
      src/cli-validator/runValidator.js
      test/cli-validator/tests/error-handling.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/@stoplight/spectral-core/src/runner/runner.ts:9:1)
```

what is nimma/legacy? .... 😠

**Comment by P0lip** [comment]
It's not an issue with Node.js, but with Jest not understanding [package exports](https://nodejs.org/api/packages.html)
You should either enable ESM support in Jest as explained [here](https://jestjs.io/docs/ecmascript-modules) or set an appropriate `moduleNameMapper`, i.e. `'^nimma/legacy$': '<rootDir>/node_modules/nimma/dist/legacy/cjs/index.js',`

**Comment by tmtron** [comment]
I also had to map some more modules (when using `"ibm-openapi-validator": "0.52.0"`):  
```js
  moduleNameMapper: {
    '^nimma/legacy$': '<rootDir>/node_modules/nimma/dist/legacy/cjs/index.js',
    '^nimma/(.*)': '<rootDir>/node_modules/nimma/dist/cjs/$1',
    '^@stoplight/spectral-ruleset-bundler/(.*)$': '<rootDir>/node_modules/@stoplight/spectral-ruleset-bundler/dist/$1'
  }
```

**Comment by DavidBiesack** [comment]
I also had to add
```
    '^nimma/fallbacks$': '<rootDir>/node_modules/nimma/dist/legacy/cjs/fallbacks/index.js'
```
to get Jest to work with spectral-core

**Comment by Gerben-T** [comment]
I'm not sure what Jest has to do with this package? I downloaded `"@stoplight/spectral-cli": "^6.6.0",` so i could use `spectral lint` to lint a openapi yaml file i have, but i get the same error as in this ticket.

`moduleNameMapper` seems to be a Jest configuration, but i'm not using Jest in my project. Is this a different issue with the same error or am i missing something?

**Comment by cb-shivamagarwal** [comment]
Ref - https://github.com/stoplightio/spectral/discussions/2167#discussioncomment-2820632

**Comment by tmtron** [comment]
After upgrading to jest 28, we could remove the moduleNameMapper workaround.
