### ISSUE TITLE
Broken internal links on `meta.stoplight.io/docs/spectral`

### ISSUE THREAD

**Issue by jamietanna** [stoplightio/spectral#2005]
**Chore summary**

A number of links on the docs site (i.e. https://meta.stoplight.io/docs/spectral/ZG9jOjYyMDc0NA-rulesets) are broken, as they are linking to the markdown file, not the specific meta URL.

**Tasks**

- Find broken markdown links
- Remediate them

**Additional context**

I.e. on https://meta.stoplight.io/docs/spectral/ZG9jOjYyMDc0NA-rulesets, there is a link `../guides/2-cli.md#using-a-ruleset-file` which should be to https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTg1-spectral-cli

**Comment by P0lip** [comment]
@jamietanna hey! It appears to be working fine for me. In recent days we had an around URL handling which we promptly fixed.
Can you still reproduce the issue?

**Comment by P0lip** [comment]
I'll close this one. If you still experience the issue, let me know.
This would be the issue with our platform, so I'd forward that information forward.
