### ISSUE TITLE
Snyk high security vulnerability in `json-ref-resolver` dependency

### ISSUE THREAD

**Issue by rmkeezer** [stoplightio/spectral#2017]
> For support questions, please use the [Stoplight Discord Community](https://discord.com/invite/stoplight). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, our Discord is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**
I am running into [Snyk security vulnerability](https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032) on the [json-ref-resolver](https://github.com/stoplightio/json-ref-resolver) dependency because it is using an outdated dependency [lodash.set](https://www.npmjs.com/package/lodash.set) which has an unresolved prototype pollution vulnerability. It should instead use `set` from the [lodash](https://www.npmjs.com/package/lodash) dependency.

**To Reproduce**
See: https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032

**Additional context**
I opened a PR [here](https://github.com/stoplightio/json-ref-resolver/pull/215) and I'm opening this issue for visibility

**Comment by dpopp07** [comment]
@P0lip Any outlook on this vulnerability being addressed?

**Comment by P0lip** [comment]
Ooops, my apologies, I missed this one.
I see @rmkeezer was kind enough to create PRs, so all that's left for me is to review them. I'll make sure to do it by the end of the week.
Once again, my apologies for dropping a ball on this one.

**Comment by P0lip** [comment]
Update the dep in https://github.com/stoplightio/spectral/commit/dc97f2414caaaae4c64166122f078c2de9d81ac2.
@stoplight/spectral-ref-resolver@1.0.2 should be out in a few minutes
