### ISSUE TITLE
`spectral lint` when using NPM-provided rulesets does not resolve rulesets

### ISSUE THREAD

**Issue by jamietanna** [stoplightio/spectral#2019]
**Describe the bug**

When running `spectral lint`, via `npx`, I cannot provide an NPM-based dependency for 

**To Reproduce**

Given the following `.spectral.yaml`:

```yaml
extends: 
  - spectral:oas
  - spectral-aws-apigateway-ruleset
```

And the following `openapi.yml`:

```yaml
openapi: 3.1.0
info:
  title: ''
  version: ''
  description: ''
paths: {}
```

Then running:

```
./node_modules/.bin/spectral lint openapi.yml
# or
npx @stoplight/spectral-cli lint openapi.yml
```

**Expected behavior**

The rules from https://www.npmjs.com/package/spectral-aws-apigateway-ruleset are downloaded and executed

**Actual Behaviour**

```
ENOENT: no such file or directory, open '/home/jamie/workspaces/cddo/federated-api-model/schemas/spectral-aws-apigateway-ruleset'
```

**Screenshots**

N/A

**Environment (remove any that are not applicable):**
 - Spectral CLI: 6.1.0
 - OS: Linux

**Additional context**

N/A

**Comment by jamietanna** [comment]
Could it be this requires the migration through the `spectral-rulesset-migrator`?

**Comment by bhatikuldeep** [comment]
@jamietanna I am experiencing the same behaviour, created NPM package - https://www.npmjs.com/package/api-spectral as per the documentation - https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTky-sharing-and-distributing-rulesets#NPM; however get the same error as you've mentioned above

`ENOENT: no such file or directory, open '..api-spectral'`

**Comment by P0lip** [comment]
Hey there!
It's indeed an issue.
I sorted it out here https://github.com/stoplightio/spectral/commit/65b0a47ea29dfb71dad87d0805cec2e81527162b but I still need to find a way to test the node_modules resolution in a reasonable way.
This is the only scenario we didn't have covered 😬

**Comment by kernwig** [comment]
Is there a workaround? Perhaps a url to `spectral:oas`?

**Comment by P0lip** [comment]
Hey @kernwig 
` spectral:oas` should work just fine.
I've already opened up a PR with a solution, so the upstream package should be fixed soon.

**Comment by kernwig** [comment]
~@P0lip It does not. Installed in a package within an NPM Workspace. ("casa" is a monorepo)~

n/m: I had "spectral:oas3". Removing the `3` fixed it.

**Comment by jamietanna** [comment]
Amazing, thanks Jakub! Is there a rough idea of when this may land on NPM?

**Comment by jamietanna** [comment]
Nice, this now works with:

```json
  "dependencies": {
    "@govuk-data-standards/spectral-ruleset-govuk-public": "^0.1.0",
    "@stoplight/spectral-cli": "^6.1.1",
    "@stoplight/spectral-ruleset-migrator": "1.7.2"
  }
```

And `.spectral.yaml`:

```yaml
extends:
  - '@govuk-data-standards/spectral-ruleset-govuk-public'
formats:
  - "oas3.1"
```

Thank you! :raised_hands: 

Do we know when the next `spectral-cli` will go out that includes the dependency bump, so we don't need to manually override it?
