### ISSUE TITLE
Cannot find module 'nimma/legacy' from SpectralCore Runner

### ISSUE THREAD

**Issue by Amachua** [stoplightio/spectral#2021]
**Describe the bug**

When I load a YAML file and a custom spectral ruleset, then I would like that the spectral runner successfully finalize the analysis of the file (see following code) as it is currently blocked due to nimma.

```javascript
export const repro = async (specificationPath: string, rulesetPath: string): Promise<boolean> => {

  const spectral = new Spectral({ resolver: httpAndFileResolver });

  const ruleset = await getRuleset(rulesetPath);

  spectral.setRuleset(ruleset);

  const document = new Document(
    await readParsable(specificationPath, { encoding: 'utf8' }),
    Parsers.Yaml,
    specificationPath,
  );

  await spectral.runWithResolved(
    document,
    {
      ignoreUnknownFormat: false,
    });

  return true;
};
```

To help you on the investigation, I have created a complete standalone repro case that is available at https://github.com/Amachua/spectral-repro.

**Comment by P0lip** [comment]
It's not an issue with Spectral, but with Jest, namely jest-resolve, not supporting package exports.
Please refer to https://github.com/stoplightio/spectral/issues/2002 for a workaround.

**Comment by Amachua** [comment]
Thank you @P0lip for the quick answer, I have check the content of the workaround and it seems like it is working! Facing another issue at the moment and I might open another Issue when I have properly scope this latter. :)
