### ISSUE TITLE
Errors and omissions in documentation of overrides

### ISSUE THREAD

**Issue by mkistler** [stoplightio/spectral#2036]
**Describe the bug**

The [documentation of the Overrides feature](https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTg5-custom-rulesets#overrides) incorrectly states that it supports
> Override rulesets to apply on particular JSONPath's

This is incorrect because Overrides use _JSON Pointers_ and not JSON Paths to identify the elements in the file where overrides should be applied.

It is unfortunate that JSON Pointers are used instead of JSON Paths, since most of the other externals of Spectral use JSON Paths, but there's probably no chance of changing that now.  But all the more reason to document it clearly.  And that should include some pointers to resources on JSON pointers (e.g. how to properly escape slashes).

**To Reproduce**

Look at the documentation.

**Expected behavior**

The documentation is correct and complete (i.e. guides users to success).

**Additional context**

I am willing to submit a PR to fix the doc problems if the Spectral developers will confirm that my diagnosis is accurate.

**Comment by mnaumanali94** [comment]
@mkistler Thank you for finding this. We do use JSON pointers! We'd be grateful if you can submit a PR. We can have the tech writing team at Stoplight review and help if you go ahead with that.
