### ISSUE TITLE
Spectral: Clarify --ruleset requirement

### ISSUE THREAD

**Issue by ryotrellim** [stoplightio/spectral#2061]
Relevant conversation: https://discord.com/channels/841794018173648916/859895506271600670/939506075525320714

Relevant tickets:
https://github.com/bundesAPI/deutschland/issues/48
https://github.com/stoplightio/spectral/issues/1893
https://github.com/stoplightio/spectral-action/pull/618
https://github.com/stoplightio/spectral/issues/1796

# Goal
The first line of https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTg1-spectral-cli will actually throw an error.
i.e., Running `spectral lint petstore.yaml` immediately after install will likely fail with `No ruleset was found.`

# Solution

Add the two ways to get a ruleset.

Create a Ruleset
Spectral, being a generic YAML/JSON linter, needs a ruleset in order to be able to lint files. There are two ways to do this:
1. Run this comment to reference our predefined results:
printf '{\n  "extends": ["spectral:oas", "spectral:asyncapi"]\n}\n' > .spectral.json
2. Create your own ruleset. (Link to Custom ruleset topic.)

**Comment by P0lip** [comment]
@ryotrellim it's in the readme together with a snippet you can use, literally one of the first sentences you have there.
<img width="940" alt="image" src="https://user-images.githubusercontent.com/9273484/153952391-fe55d32a-824d-422f-8947-963648846cd2.png">

> If you intend to lint an OpenAPI or AsyncAPI document, we have a few predefined rulesets you can extend to get Spectral up and running. To reference them, you can run the following command:

**Comment by pamgoodrich** [comment]
@P0lip : I believe you are saying the doc is correct. I was able to get this command to work locally:

spectral lint openweather.json 

Once I had a ruleset named .spectral.yaml with this line at the top:

extends: spectral:oas

I can help come up with some clearer steps if that would help. Let me know.

**Comment by P0lip** [comment]
I meant the following segment. There's a command you can run that will get you started. It'll create a `.spectral.json` file which is everything you need to start linting.

<img width="940" alt="153952391-fe55d32a-824d-422f-8947-963648846cd2" src="https://user-images.githubusercontent.com/9273484/154068849-6da66fce-ec07-4502-b43e-44273f0ddca4.png">
