### ISSUE TITLE
Core function to validate json schema is not working. [bug] 

### ISSUE THREAD

**Issue by avinashpise** [stoplightio/spectral#2065]
**Describe the bug**
core function fails to execute using javascript. When trying to Implemented the schema core [function](https://meta.stoplight.io/docs/spectral/ZG9jOjExNg-core-functions#schema). I am getting error like *Cannot read property 'resolved' of undefined for core function schema*

**To Reproduce**

1. Given a custom function to validate email  
 ```
    const {casing, schema} = require("@stoplight/spectral-functions");
    validateEmail(_EmailAddress, _Path){
        let result = [];
        const emailSchema =  { type: "string", format: "email"}
        const response = schema(_EmailAddress, { schema: emailSchema, allErrors: true }, {path: _Path,rule:""});
        if(response && response.length > 0){
            result.push(...response);
        }         
        return result;
    },
```
2. Call validateEmail function with valid details
```
    validateEmail("abc@xyz.com", ["info","contact","email"]);
``` 
after the execution of validateEmail, it returns the expected result.

3. Call validateEmail function with invalid details
```
    validateEmail("abcxyz.com", ["info","contact","email"]);
```
after the execution of validateEmail, it returns the below message.
```
    const assignAjvInstance = (_a = instances.get(documentInventory)) !== null && _a !== void 0 ? _a : instances.set(documentInventory, (0, ajv_1.createAjvInstances)()).get(documentInventory);
                                                                                                                 ^

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at schema (C:\Projects\lint\node_modules\[4m@stoplight[24m\spectral-functions\dist\schema\index.js:24:114)
    at schema (C:\Projects\lint\node_modules\[4m@stoplight[24m\spectral-core\dist\ruleset\rulesetFunction.js:66:16)
    at validateEmail (C:\Projects\lint\index.js:8:26)
    at Object.<anonymous> (C:\Projects\lint\index.js:3:1)
[90m    at Module._compile (internal/modules/cjs/loader.js:1068:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:933:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
```

**Expected behavior**
It should return zero errors, but here code stops working and getting above mentioned error.

**Environment:**
 - Library version:  6.0.0
 - OS:  Windows 10

@P0lip

**Comment by P0lip** [comment]
Hey!
The usage is incorrect. It is expected to forward the initial ctx that was provided, i.e  https://github.com/stoplightio/spectral/blob/develop/packages/rulesets/src/oas/functions/oasSchema.ts#L69

**Comment by avinashpise** [comment]
Hi @P0lip,
Till today, i was using the above code snippet which was working fine. but suddenly it stops working. I have reffered the Link [https://github.com/stoplightio/spectral/issues/1907#event-5491184635](https://github.com/stoplightio/spectral/issues/1907#event-5491184635)
I tried by passing the context but still i am getting same error, do you have documentation for this? It will helps a lot.
Thanks in advance.

**Comment by P0lip** [comment]
the example I posted in #1907 is still correct.
There's doc over here https://github.com/stoplightio/spectral/blob/develop/docs/guides/5-custom-functions.md#referencing-core-functions
