### ISSUE TITLE
Critical security vulnerability in vm2

### ISSUE THREAD

**Issue by Havunen** [stoplightio/spectral#2070]
Sandbox bypass in vm2 - https://github.com/advisories/GHSA-6pw2-5hjv-9pf7
fix available via `npm audit fix`

**node_modules/vm2**

1 critical severity vulnerability

 **npm list vm2** shows this repository as part of the dependency chain

```

`-- ibm-openapi-validator@0.53.1
  `-- @stoplight/spectral-cli@6.2.0
    `-- proxy-agent@5.0.0
      `-- pac-proxy-agent@5.0.0
        `-- pac-resolver@5.0.0
          `-- degenerator@3.0.1
            `-- vm2@3.9.5

```

Connects to https://github.com/TooTallNate/node-proxy-agent/issues/74

**Comment by P0lip** [comment]
There isn't a new version of proxy-agent available, so we cannot do much about it from our side.
The workaround you provided should be sufficient for now, as luckily the denegerator package doesn't have the version pinned, so vm2 can be easily updated.

**Comment by P0lip** [comment]
We should be good now. We no longer depend on 3.9.5.
