### ISSUE TITLE
'spectral' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Koushikj9823** [stoplightio/spectral#2086]
**Describe the bug**
 I have installed [@stoplight/spectral-cli](https://www.npmjs.com/package/@stoplight/spectral-cli) using the command **npm install -g @stoplight/spectral-cli**. It gets successfully installed, But while running spectral command, it does not recognize.

**To Reproduce**

1. Run this CLI command `'spectral lint -r ./lingo-ruleset-rpc.yaml ./spec.yaml'`
2. See error: 
```
  spectral : The term 'spectral' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
  was included, verify that the path is correct and try again.
  At line:1 char:1
  + spectral lint -r ./lingo-ruleset-rpc.yaml ./spec.yaml
  + ~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (spectral:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
    

**Environment:**
 - OS: Windows 10
 - Node: 14.17.1
 - npm: 6.14.13

**Comment by P0lip** [comment]
This is probably an issue with PATH on Windows.
Perhaps this helps https://stackoverflow.com/a/29955218

**Comment by Koushikj9823** [comment]
Thanks, @P0lip it worked. It was indeed a windows PATH issue.
