### ISSUE TITLE
does not support local url path

### ISSUE THREAD

**Issue by jianyexi** [stoplightio/spectral#2094]
**Describe the bug**
if  specifies a local url path as input like , file:///C:/spcec.json , the spectral seems not work and output no errors 

**To Reproduce**

2. Run this CLI command '....'
spectral lint file:///C:/foo.json

**Expected behavior**
want to support it 
**Screenshots**

**Environment (remove any that are not applicable):**
 - OS: [e.g. Windows 11]

**Comment by P0lip** [comment]
Hey!
Is there any reason you need to use a file protocol?
We presumably don't support it yet, but the workaround here would be to get rid of that protocol assuming that's possible.
