### ISSUE TITLE
Change #main to #exports in package.json

### ISSUE THREAD

**Issue by sandro-pasquali** [stoplightio/spectral#2130]
Getting this error on install of `@stoplight/spectral-core@1.12.0`: `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in <path to spectral>package.json`.

Node 17.9.0

I believe this means the package.json file needs to change its entrypoint definition.

v `1.11.1` works fine.

My app is set to `type: "module"`.

**Comment by jammi** [comment]
I have this same issue.

**Comment by P0lip** [comment]
I believe this should be fixed in https://github.com/stoplightio/spectral/commit/ec08efee42fb1b94ee5b5aeae3d82e2809881e00.
I'll let you know once it's out.

**Comment by P0lip** [comment]
It should be fixed now.
Can any of you verify it? @sandro-pasquali @jammi

**Comment by sandro-pasquali** [comment]
Yup, working for me. Thanks!

**Comment by P0lip** [comment]
Awesome, thanks!
