### ISSUE TITLE
Release 6.3

### ISSUE THREAD

**Issue by dweber019** [stoplightio/spectral#2134]
**Chore summary**
I think the release 6.3.0 is missing?
I can see 6.3.0 at https://www.npmjs.com/package/@stoplight/spectral-cli but not in https://github.com/stoplightio/spectral/releases and https://hub.docker.com/r/stoplight/spectral/tags?page=1&name=6.

Am I missing something?

**Tasks**
- [x] Release 6.3.0

**Comment by P0lip** [comment]
Done! My apologies for keeping you waiting.
