### ISSUE TITLE
Can not install due to jsonpath

### ISSUE THREAD

**Issue by Lakitna** [stoplightio/spectral#214]
### **I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### What is the current behavior?

When trying to install spectral using `npm install @stoplight/spectral` I get the following error:

```
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE clone --mirror -q https://github.com/stoplightio/jsonpath.git C:\Data\npm\cache\_cacache\tmp\git-clone-9c9fbadd\.git --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\USER\AppData\Local\Temp\pacote-git-template-tmp\git-clone-818f94da
npm ERR! fatal: unable to access 'https://github.com/stoplightio/jsonpath.git/': SSL certificate problem: self signed certificate in certificate chain
npm ERR!
```

I'm behind a corporate proxy which is why there is a self-signed certificate.

### What is the expected behavior?

It installs without errors

### What is the motivation / use case for changing the behavior?

Spectral is unusable for me without a fix. I literally can't download it via NPM.

### Please tell us about your environment:

  - Version: 1.x or above
  - OS: Windows 10
  - Package manager: NPM
  - Node version: 8.13.0

### Other information

Running things behind a corporate proxy is a known bad experience. In this case, things break because of the hard https reference to a forked repository.

Does this have to be a reference to the fork? What's wrong with `jsonpath@1.0.0`?

**Comment by philsturgeon** [comment]
Can you use the pre built binaries instead of NPM for now? Getting our upstream changes into jsonpath is absolutely on the todo list, but it’s not a quick or easy task, so if you’re gonna stay on that corp network you’ll need another approach for now.

**Comment by Lakitna** [comment]
Locally that would work, but I was planning on linting in a pipeline when I got things up and running. I will likely have the same issue there. 

Do you really need to implement the upstream? Can't you set an old npm version as the dependency?

On second thought, I'll take a poke at answering these questions myself on my personal pc without corporate proxy :)

**Comment by philsturgeon** [comment]
We have our own commits added to jsonpath that folks didn’t get a chance to send PRs for yet, so we can’t pick a specific version no. 

There’s other solutions like we release our fork on NPM but it would be better to get out changes merged with master. There’s a story for this to get done, but it’s not at the top of the pile yet. 

--
Phil Sturgeon
@philsturgeon

**Comment by P0lip** [comment]
@Lakitna, as a workaround, you can try setting a custom resolution in your package.json, as follows
```
"resolutions": {
  "jsonpath": "http://github.com/stoplightio/jsonpath#f1c0e9e634da2d45671b7639fa0a99afc807da1"
},
```
Once a resolution is added, you should be able to successfully install Spectral using npm or yarn.
If it still doesn't work and the cert is needed for some reason, you can download our repo and provide a different link instead. It also accepts filesystem via `file:` [syntax](https://docs.npmjs.com/files/package.json#local-paths), so you can simply provide a path to the physical directory on your machine.

Note: if there is any other dependency requiring jsonpath, it will use our fork instead of the version defined in its package.json. This shouldn't be a real problem, though, as we didn't introduce any breaking changes to our fork.

**Comment by Lakitna** [comment]
I'll give the workaround a shot when I'm back on the corporate network. Thanks for thinking with me.

**Comment by Lakitna** [comment]
@P0lip The workaround does the trick. It's not perfect but it allows me to use Spectral until the upstream `jsonpath` changes have been implemented.

**Comment by P0lip** [comment]
@Lakitna really glad to hear the workaround did the trick for you. 
We'll sort out that `jsonpath` dependency issue sooner or later since it's something that annoys us as well.

**Comment by nulltoken** [comment]
Sorry to bump a closed issue, but I'm facing the same issue (behind a corp proxy failing to install spectral) and the resolution workaround doesn't work for me.

Would there be any way for you to publish an early hotfix based on #257 work?

**Comment by P0lip** [comment]
@nulltoken 
Unfortunately, the solution implemented in #257 has to be considered as a breaking change, as the new library we use for querying has a slightly different syntax, therefore custom rulesets might break.
We could try releasing a minor version until we release the next major version.
@philsturgeon what do you think about releasing a minor version with a fix? I believe there is very little chance of breakage here.

**Comment by marbemac** [comment]
@philsturgeon might be time to publish v4 on an npm beta tag?

**Comment by philsturgeon** [comment]
@marbemac yeah it looks like it's time. I'll do this first thing in the morning.

**Comment by philsturgeon** [comment]
Sorry for the hold up, we are trying to improve the Spectral build, release and publish process in line with Prism. Here's a bit of that: #274

**Comment by philsturgeon** [comment]
@Lakitna @nulltoken you can now give spectral v4.0.0-beta1 a try with `yarn add @stoplight/spectral@beta`

You should be able to remove the `"resolutions": {` workaround too.

**Comment by Lakitna** [comment]
The beta installs normally without any issues! :)
