### ISSUE TITLE
Peer dependency incorrectly met when using Yarn 3.x

### ISSUE THREAD

**Issue by toymachiner62** [stoplightio/spectral#2144]
**Describe the bug**
I upgraded to yarn 3.x and now I have a project that is showing this error 

```sh
$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @stoplight/spectral-cli@npm:6.3.0 doesn't provide rollup (p8903b), requested by @rollup/plugin-commonjs
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
```

**To Reproduce**

Create a project with `@stoplight/spectral-cli` as a devDependency and run `$ yarn install` with the latest version of yarn.

**Expected behavior**
No peer dependency error

**Environment (remove any that are not applicable):**
 - OS: macOS

**Comment by amanarch96** [comment]
Witnessing same error, post this log the workflow is stuck for 1-2 hours.
Any solution for this?

**Comment by punkpeye** [comment]
Same issue. Is there a workaround?
