### ISSUE TITLE
Add example of loading multiple rulesets using Spectral in JavaScript

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/spectral#2148]
Add example of how to use `bundleAndLoadRuleset()` method with multiple rulesets files. Method will only accept path to one file, not multiple files or a directory.

Discord thread:
https://discord.com/channels/841794018173648916/859895506271600670/969254132760342603

Slack thread:
https://stoplight-internal.slack.com/archives/C0268494GJC/p1651613549636839

jakub:this-is-fine-fire:  8 hours ago
you can create a ruleset that extends all of them

jakub:this-is-fine-fire:  8 hours ago
extends: [rulesetA, rulesetB, rulesetC]

**Comment by KiranReddy0808** [comment]
@pamgoodrich , @heitortsergent ,
I just read the conversation on discord. I'm also looking for the same loading multiple rulesets. Does your use case need to use specific ruleset paths from an array based on condition? 

If not i.e there is a constant array of file paths you could extend ruleset adding file paths in main rules.yml, give this a read https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTky-sharing-and-distributing-rulesets and example
https://github.com/KiranReddy0808/basic-oas-spec/blob/main/rules.spectral.yaml.
