### ISSUE TITLE
Spectral Executable Binaries Not Working

### ISSUE THREAD

**Issue by JGPrakash** [stoplightio/spectral#2153]
I want to install Spectral linter using Executable Binaries, I found the Executable Binaries for Spectral URL (https://github.com/stoplightio/spectral/releases/tag/v6.3.0)
In this link I found the source code(.tar.gz) in assert menu, after downloading the source code(.tar.gz) it have all the ruleset and function folder and files, unfortunately I could not able to run spectral command using this source code
If possible to run spectral command using the source code and how to do it? (As per my company policy we are not allowed to use NPM installation)

**Comment by P0lip** [comment]
Hey.
What you've downloaded weren't the binaries.
You should download one of the following files, depending on your OS.
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/9273484/167483604-09402a36-8458-40ca-8033-535152760bd3.png">
