### ISSUE TITLE
No results with a severity of 'error' or higher found!

### ISSUE THREAD

**Issue by max-moritz** [stoplightio/spectral#2156]
**Describe the bug**

Ok, this is nitpicking :blush: .... but ... `error `is the highest severity so `or higher` does not make sense in console output `No results with a severity of 'error' or higher found!`

**To Reproduce**

Run

`spectral lint -r ruleset.yml api.yml --display-only-failures`

where `api.yml` does not violate any rule defined in `ruleset.yml` with severity `error` (it may produce `warn`, `info`, `hint `results)

**Expected behavior**

`No results with a severity of 'error' found!`

**Environment (remove any that are not applicable):**

 - Library version: 6.3.0
 
**Additional context**

Generally, output should be one of:
`No results with a severity of 'error' found!`
`No results with a severity of 'warn' or higher found!`
`No results with a severity of 'info' or higher found!`
`No results with a severity of 'hint' or higher found!`

**Comment by P0lip** [comment]
> this is nitpicking 

it's a good improvement nonetheless 🙂
