### ISSUE TITLE
[Docker] Build for M1 Macs

### ISSUE THREAD

**Issue by jamietanna** [stoplightio/spectral#2189]
**User story.**
As a user on an M1 Mac, I can use a native Docker image, instead of an emulated image for my architecture, so that I can run Spectral more efficiently.

**Is your feature request related to a problem?**

**Describe the solution you'd like**

**Additional context**

When running `stoplight/spectral:6` on an M1 Mac:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

```

**Comment by philsturgeon** [comment]
@jamietanna you got a pull request for us there?

**Comment by jamietanna** [comment]
Sorry no, not had a chance to get around to it. Happy to look next week when back at work if no one else has gotten around to it

**Comment by mnaumanali94** [comment]
@jamietanna Did you get a chance to take a look at this? 

Related to: #2279

**Comment by P0lip** [comment]
The next version of CLI will have arm64 builds attached to it.

**Comment by rngtng** [comment]
Awsm. Thanks a lot your efforts!
