### ISSUE TITLE
Document Spectral support for multiple Thens

### ISSUE THREAD

**Issue by pamgoodrich** [stoplightio/spectral#2192]
This file:

https://meta.stoplight.io/docs/spectral/e5b9616d6d50c-custom-rulesets#then

Does not explain that Spectral supports multiple thens. This will be added to the platform style guide doc, but we need to update Spectral.

**Comment by heitortsergent** [comment]
Example of multiple `then`s: https://github.com/transcom/mymove/blob/master/swagger-def/.spectral.yml#L43

**Comment by P0lip** [comment]
We use it in the Spectral as well https://github.com/stoplightio/spectral/blob/develop/packages/rulesets/src/oas/index.ts#L106
