### ISSUE TITLE
How to use a custom function to display a message with varying severity?

### ISSUE THREAD

**Issue by JGPrakash** [stoplightio/spectral#2197]
Using the default ruleset to lint the open api, the result looks like this:

✖ 8 problems (2 errors, 4 warnings, 0 infos, 0 hints)

With the above result having two severity (errors and warnings),

In the same way, I want to implement it in the custom function.

How to show the different severity in custom functions?

**Comment by P0lip** [comment]
Unfortunately, that is not possible at the moment. See https://github.com/stoplightio/spectral/pull/1982
