### ISSUE TITLE
Breaking change detected: update of @stoplight/spectral-core 1.12.2 -> 1.12.3 causing breaking changes

### ISSUE THREAD

**Issue by pavelkornev** [stoplightio/spectral#2204]
**Describe the bug**
We tried to update `@stoplight/spectral-core` `1.12.2` -> `1.12.3` and validation breaks with the following issue:
`Error running Nimma`

It seems like in `1.12.3` [Nimma itself was updated](https://github.com/P0lip/nimma/compare/0.2.1...0.2.2).

We had lots of selectors like:
* `$.paths.[*].get`
* `$.paths.[*].*.responses`

Which suddenly stopped working the way they worked before...

**Comment by P0lip** [comment]
We indeed changed the way `.[` is handled. In jsonpath-plus, `.[` is treated as if it was a recursive lookup.
In other words, it's equal to `$.paths..[*]`. It was a bug we didn't treat it this way.
I suppose you still want the old behavior, so I recommend to update your JSONPath expressions as follows:

`$.paths.[*].get` -> `$.paths[*].get`
`$.paths.[*].*.responses` -> `$.paths[*].*.responses`

**Comment by pavelkornev** [comment]
Yeah, we have updated our JSON Paths already. I agree this was a bug in Nimma, it was just unexpected to see a failure after updating a minor release of the `@stoplight/spectral-core`

No action is required here, hence -> Closing. Let's keep this issue for tracking if somebody else faces this issue and finds it via Google search.
