### ISSUE TITLE
Output is missing a line break

### ISSUE THREAD

**Issue by nmoreaud** [stoplightio/spectral#2207]
This message should finish with a line break, following linux standards: `No results with a severity of 'error' found!`

Current ouput:
```
$ npx @stoplight/spectral-cli lint ./data_explorer/specs/v1/v1.yaml
No results with a severity of 'error' found!dev@SOME-COMPUTER:~/projects/python_project$
```

**Environment**
 - Library version: 6.4.1
 - Node version: 18.5.0

**Comment by P0lip** [comment]
Would you be willing to send a PR for that?
