### ISSUE TITLE
Empty `source` in result

### ISSUE THREAD

**Issue by kotofeyskaya** [stoplightio/spectral#2227]
**Describe the bug**
We use a ruleset that extends **oas** ruleset. We have a document with a **$ref** in it. When we `run` spectral, the `source` in the result set is **undefined** for external refs.

**To Reproduce**

1. Given this OpenAPI/AsyncAPI document 
```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
paths:
  /pets:
    $ref: './external/external-path-1.yaml#/~1pets'
```
and ref file:

We get the following result:
```
...
{
 code: "operation-description"
 message: "Operation \"description\" must be present and non-empty string."
 path: (3) ['paths', '/pets', 'get']
 range: {start: {…}, end: {…}}
 severity: 1
 source: undefined
}
```

**Expected behavior**
```
{
 code: "operation-description"
 message: "Operation \"description\" must be present and non-empty string."
 path: (3) ['paths', '/pets', 'get']
 range: {start: {…}, end: {…}}
 severity: 1
 source:'external/external-path-1.yaml'
}
```

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: MacOS BigSur
 - Browser: [e.g. Chrome 103]

**Comment by teluren** [comment]
Dear colleagues,
Is there any update on this issue? What is the possible fix date/release?

**Comment by aerialist7** [comment]
Hi @P0lip, @FredericKayser, @ObjectIsAdvantag, @magicmatatjahu

could you please help?

**Comment by P0lip** [comment]
I can't seem to be able to reproduce the issue.
Could you please tell which version of spectral-core you use as well as paste the JS code you have?

<img width="554" alt="image" src="https://user-images.githubusercontent.com/9273484/188886869-af5f8866-eb7b-48fa-a398-1005ce50b13b.png">

**Comment by aerialist7** [comment]
Hi @P0lip, thank you for the respond!
We use "@stoplight/spectral-core": "1.14.0"

**Comment by P0lip** [comment]
@aerialist7 could you share the JS code you have?

**Comment by aerialist7** [comment]
@P0lip, will share it tomorrow morning.
We run it in browser, seems you're run it in Node. Am I right? If yes, could you please try to run it in browser?

**Comment by aerialist7** [comment]
@P0lip, here is a sample
https://github.com/aerialist7/spectral-sample

1. `yarn install`
2. `yarn run start`
3. Open localhost
4. See browser console

![image](https://user-images.githubusercontent.com/32072831/189034279-a7b05d69-c5da-4509-84ac-ec9e3a856a22.png)

**Comment by P0lip** [comment]
You don't set `source` there which Spectral uses to determine the source.

Try the following:
- add 
   ```ts
   import { Spectral, Document } from "@stoplight/spectral-core" 
   import * as Parsers  from "@stoplight/spectral-parsers"
  ```
 - modify `spectral.run` to `.then(text => spectral.run(new Document(text, Parsers.Yaml, "/root.yaml")))`

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/9273484/189086956-314eab06-3502-4ef2-b0fa-3b3c38697ffd.png">


Please let me know if you have any other questions.

**Comment by aerialist7** [comment]
@P0lip, it wasn't obvious, but it works, thanks a lot!

**Comment by P0lip** [comment]
I'm glad it did the trick. 🙂 
@aerialist7 do feel free to update our documentation if you think we have some gaps. I'd appreciate that.
