### ISSUE TITLE
Add aliases for common OAS `given` targets

### ISSUE THREAD

**Issue by heitortsergent** [stoplightio/spectral#2236]
**Chore summary**
We have the [`aliases` feature](https://meta.stoplight.io/docs/spectral/e5b9616d6d50c-custom-rulesets#aliases) to help users target certain parts of a spec without having to remember the JSONPath expression, and we have 2 already created [here](https://github.com/stoplightio/spectral/blob/4447d81ace5aab90e7cd48a8e182103b6a90ee81/packages/rulesets/src/oas/index.ts#L32-L38) for OAS.

We can expand this list of aliases to cover more common targets that people use in their rulesets to make it easier for users to create and maintain rulesets.

**Tasks**
- [ ] Add new aliases: [Notion page with list of possible aliases](https://www.notion.so/stoplight/List-of-Aliases-9ff1454f3599450aa11d4588fda75f2d)
- [ ] Add docs

**Comment by mnaumanali94** [comment]
Would require: #2237

**Comment by heitortsergent** [comment]
Updated description with link to Notion page with list of new possible aliases: https://www.notion.so/stoplight/List-of-Aliases-9ff1454f3599450aa11d4588fda75f2d
