### ISSUE TITLE
Issue importing oas ruleset from @stoplight/spectral-rulesets

### ISSUE THREAD

**Issue by kingcanova** [stoplightio/spectral#2240]
**Describe the bug**
When trying to use the oas ruleset exported by the @stoplight/spectral-rulesets package in a backstage.io custom plugin an error occurs that does not let me render my frontend page or use the ruleset.

The error that is displayed on the webpage is: 
`ERROR 501: Lazy loaded chunk failed to load, try to reload the page: __importDefault is not defined`

Here is how the packages are being imported:
```
import { Spectral, Document } from "@stoplight/spectral-core";
import { oas } from "@stoplight/spectral-rulesets";
```
Ive also tried importing it using "require" but get the same error when trying that way.

Here is how the packages are being used:
```    
const spectral = new Spectral();
console.log(oas);
const myRuleset = {
    extends: [oas],
    rules: {
        "no-empty-description": {
            given: "$..description",
            message: "Description must not be empty",
            then: {
                function: truthy,
            },
        },
    },
}
useEffect(() => {
    spectral.setRuleset(myRuleset);
    console.log(spectral.ruleset);
    spectral.run(myDocument).then(setLintIssues);
}, []);
```

**Environment:**
Node: v1.15.1
Typescript: 4.6.4
Spectral-core: 1.13.0
Spectral-functions: 1.7.0
Spectral-parsers: 1.0.1
Spectral-ruleset-bundler: 1.3.1
Spectral-rulesets: 1.11.1
OS: MacOS Monterey
Browser: Chrome 103

**Comment by P0lip** [comment]
That is weird. We fixed `__importDefault` issue some time ago. 🤔 
Could you share the error stack for me to see the actual source of that error?

**Comment by kingcanova** [comment]
Hi @P0lip, I dont seem to have any other error logs than the one posted above (or im not sure where they would be) that shows up where the component that is utilizing the spectral should be rendered. I can fully render my component and run the above code on an example document if I dont import **oas** and dont add it as an extension to the custom ruleset.

**Comment by kingcanova** [comment]
Here is a screenshot: 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/17076518/184428196-87ea47a3-dc1e-4352-8559-0afc2ca354d0.png">

**Comment by P0lip** [comment]
> if I dont import oas and dont add it as an extension to the custom ruleset.

got it. Would it be possible for you to send some sample project so I can take a look at the code that gets executed?

**Comment by P0lip** [comment]
Nevermind, I see it now. It was re-introduced in https://github.com/stoplightio/spectral/blob/develop/packages/rulesets/src/shared/functions/index.ts
