### ISSUE TITLE
feature to lint whole project in IntelliJ

### ISSUE THREAD

**Issue by veer201989** [stoplightio/spectral#2244]
**User story.**
As a user, I can do lint my whole project (all the YAML/JSON files), so that I can identify the issues/warning/info.

**Is your feature request related to a problem?**
I am trying to lint my java project in which I have multiple YAML/JSON files, I want to lint all the files but I am not able to get any setup process and how to lint all the files in one go.

**Describe the solution you'd like**
I want to lint all the files (YAML/JSON) which are available in the project vie IntelliJ.

**Comment by P0lip** [comment]
Spectral [accepts](https://github.com/stoplightio/spectral/blob/develop/docs/guides/2-cli.md#spectral-cli) glob patterns.
Example: `spectral lint ./reference/**/*.oas*.{json,yml,yaml}`
Use that if you have more than a single file to lint - just make sure to adjust the glob pattern above to match your particular project strucutre.

**Comment by veer201989** [comment]
I want to setup spectral in maven/gradle to build the build. please share the steps to setup the build.

**Comment by P0lip** [comment]
Unfortunately, I'm not familiar with Maven/gradle, thus I won't be much of a help here 😞
