### ISSUE TITLE
Gitlab code quality support

### ISSUE THREAD

**Issue by lhimstedt** [stoplightio/spectral#2283]
**User story.**
As a developer, I can export the results to a Gitlab code quality report to see a summary of my code quality in the MR widget and the pipeline.

**Is your feature request related to a problem?**
Currently, there is only a format enum for JUnit. That's cool because you can see the results in Gitlab, but I prefer linting results in the code quality section. The linting results are more about the quality, not in all cases about functionality.

**Describe the solution you'd like**
It would be cool to have another output format in the CodeClimate JSON format.

**Comment by lhimstedt** [comment]
I found no related issue, maybe there was a discussion about this. Would be cool to get some other perspectives about this.

**Comment by mnaumanali94** [comment]
This would be a very nice addition. Would you be interested in creating a PR for this? 🙏🏼

**Comment by wtrocki** [comment]
I have done some investigation on how this can be done and it looks there is no easy way to actually get number of results. 
Results in recent versions have been changed to only contain certain serverity level. By default info level severity is not logged so we would never get any information about how many rules have run in the format interface.

**Comment by astec-dsa** [comment]
Would be nice to get this feature.

**Comment by smsalisbury** [comment]
The PR linked above will resolve this issue.
