### ISSUE TITLE
Is there any way that custom function can be build to validate only RE2 regular expression syntax

### ISSUE THREAD

**Issue by avinashpise** [stoplightio/spectral#2287]
**User story.**
As a Open API specification Developer,I can validate only RE2 regulare expression syntax.

**Is your feature request related to a problem?**
Spectral tool support to write a custom function to apply custom rules. We can build the custom rule using the core function such a schema, casing or pattern. Here if we use the schema funtion to validate the json schema, i belive it supports only PCRE syntaxt to validate the schema defination and not the RE2 syntax.
for Eg. if schema contains the lookahead pattern, then through error 
**Describe the solution you'd like**
Is there any way that RE2 syntax support can be incuded? any flag or any setting which can be passed to core function and it will validate only PCRE or RE2 or both.

**Comment by P0lip** [comment]
Hey!
You could use https://www.npmjs.com/package/re2.
Keep in mind that re2 is essentially a package providing Node.js bindings for RE2, meaning the package won't work in a browser.
