### ISSUE TITLE
Questions about features

### ISSUE THREAD

**Issue by alexec** [stoplightio/spectral#2333]
Does Spectral support

* OpenAPI v3.1
* Circular refs
* Relative paths

**Comment by magicmatatjahu** [comment]
@alexec HI!

1. Yes, Spectral supports OpenAPI v3.1. You can see `oas3_1` format which means that v3.1 is supported - https://github.com/stoplightio/spectral/blob/develop/packages/rulesets/src/oas/index.ts#L34
2. Yes, Spectral supports circular refs, but it leaves them in the resolved spec, so if your schema have something like:

   ```yaml
   type: object
   properties: 
     property:
       type: object
       properties:
         circular:
           $ref: '#/properties/property'
   ```
   
   Spectral will leave `$ref: '#/properties/property'`.
   
3. If you mean by the `relative paths` the references to the local files, yes, it supports it.

**Comment by alexec** [comment]
Thank you!

**Comment by alexec** [comment]
Does it support linting of `webhooks`?

**Comment by magicmatatjahu** [comment]
@alexec Yes, it supports :) https://github.com/stoplightio/spectral/blob/develop/packages/rulesets/src/oas/schemas/3.1.json#L27

**Comment by alexec** [comment]
Thank you!
