### ISSUE TITLE
Error #1: scope.sandbox.at(...).property.match is not a function

### ISSUE THREAD

**Issue by corealan** [stoplightio/spectral#2360]
### Discussed in https://github.com/stoplightio/spectral/discussions/2357

<div type='discussions-op-text'>

<sup>Originally posted by **corealan** December  2, 2022</sup>
Hello everyone!
I'm trying to run spectral from command line. And use following command:
spectral lint C:\TEST\test.yaml --ruleset C:\TEST\rules.yaml --format junit --output C:/TEST/Lint_report.xml --verbose
But i always got that error:
![image](https://user-images.githubusercontent.com/34137905/205278644-2de29ad3-5f26-467a-967a-d050ac6397f9.png)

Are there anyone faced same problem?</div>

**Comment by P0lip** [comment]
I responded in https://github.com/stoplightio/spectral/discussions/2357
