### ISSUE TITLE
`spectral lint` error `TypeError: ajv_1.Name is not a constructor`

### ISSUE THREAD

**Issue by Gerben-T** [stoplightio/spectral#2386]
**Describe the bug**
When running `spectral lint` i get the following error

```
[redacted]\node_modules\ajv-errors\dist\index.js:10
const used = new ajv_1.Name("emUsed");
             ^

TypeError: ajv_1.Name is not a constructor
``` 

coming from `node_modules\@stoplight\spectral-core\dist\ruleset\validation\ajv.js:8:51`

**To Reproduce**

Just running `spectral lint` on any openapi file, for example https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml

**Expected behavior**
Lint should complete and show success

**Environment (remove any that are not applicable):**
 - Library version: 6.6.0
 - OS: Windows 10
 - Node: v12.20.2

**Comment by P0lip** [comment]
Hey @Gerben-T!
Looks like it might be trying to use Ajv v6 rather than v8.
Do you use `npm` or `yarn`?
Either way, deduping may help - `npm dedupe` or `npx yarn-deduplicate` for yarn v1  or `yarn dedupe` for v2 and newer.

**Comment by Gerben-T** [comment]
> Hey @Gerben-T! Looks like it might be trying to use Ajv v6 rather than v8. Do you use `npm` or `yarn`? Either way, deduping may help - `npm dedupe` or `npx yarn-deduplicate` for yarn v1 or `yarn dedupe` for v2 and newer.

Thanks for the quick response! I'm using npm (version `6.14`). Sadly the command `npm dedupe` did not help.. Here is the output for that command

```
audited 397 packages in 1.14s

80 packages are looking for funding
  run `npm fund` for details       

found 0 vulnerabilities


Process finished with exit code 0
```

The error in `spectral lint` stayed the same

**Comment by Gerben-T** [comment]
> Hey @Gerben-T! Looks like it might be trying to use Ajv v6 rather than v8. Do you use `npm` or `yarn`? Either way, deduping may help - `npm dedupe` or `npx yarn-deduplicate` for yarn v1 or `yarn dedupe` for v2 and newer.

Thanks for the quick response! I had the wrong node/npm version installed in my project.. The version i needed was v8.10.0, because it is an old project. I also downgraded `spectral` to it's original version which was `^5.1.0` and everything seems to work right now. Thanks anyway for looking into this
