### ISSUE TITLE
Issue installing @stoplight/spectral-cli

### ISSUE THREAD

**Issue by caitlinnew** [stoplightio/spectral#2387]
**Describe the bug**
See video

https://user-images.githubusercontent.com/92755071/215109959-814b7576-5828-4f33-bf57-5d766dc65625.mp4

**Expected behavior**
Easy install and/or clear error messaging

**Screenshots**

**Environment (remove any that are not applicable):**
 - OS: Windows

**Comment by P0lip** [comment]
The old spectral should be uninstalled before installing a new one.
That should help.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/9273484/227258005-946bb9c8-4cfa-4942-b8b1-c98e13ed0e97.png">
