### ISSUE TITLE
Preserve `$ref` when resolving references

### ISSUE THREAD

**Issue by ctreatma** [stoplightio/spectral#2390]
**User story.**
As a spectral user, I can identify which objects are `$refs`, so that I can ensure that complex objects are appropriately named.

**Is your feature request related to a problem?**

We generate client code from our OpenAPI specification; sometimes, the structure of our spec causes the generators to produce suboptimal code.

For example, an API endpoint might define a request body schema like this:
```yaml
post:
  operationId: createThingy
  #...
  responses:
    "200":
      content:
        application/json:
          schema:
            oneOf:
            - $ref: '../../../components/schemas/OriginalThingyInput.yaml'
            - $ref: '../../../components/schemas/NewThingyInput.yaml'
```

That is valid, but a code generator will look at that and generate a model called `CreateThingy200Response`.

Thus far, we haven't found a way to detect, using `spectral`, whether the `oneOf` is inline or if it came from a resolved `$ref`.

**Describe the solution you'd like**

We would like an option that can be specified to resolve references _and_ maintain the `$ref` property so that we can tell where the `$refs` were after resolution.

**Additional context**

**Comment by P0lip** [comment]
Have you tried using [resolved](https://github.com/stoplightio/spectral/blob/e026a85239a44c7a2ae3e329e9644179bd392b90/docs/guides/4a-rules.md#resolved) on a rule?

**Comment by ctreatma** [comment]
I tried using `resolved: false`, and it looks like it disables all reference resolution, so we only get the content of the root document.  Our paths are referenced roughly like this:

```yaml
paths:
  /my/path:
    $ref: paths/mypath.yaml
```

so the schema chunk in the issue description is unreachable with `resolved: false`, and with resolution enabled, we have no record that there was a ref in the first place.

**Comment by P0lip** [comment]
A custom function has an access to an unresolved document, so you could try accessing that if you haven't done it yet

**Comment by mnaumanali94** [comment]
@ctreatma Does that work for you?

**Comment by ctreatma** [comment]
It sounds promising but I haven't had enough time to really dig into it.  I started looking through the unresolved document data for my spec but having some trouble figuring out how to go from a path in the resolved document to corresponding path in the correct unresolved document.

**Comment by P0lip** [comment]
I'll close the ticket in the meantime. Feel free to follow up here in case you ran into the issue :)
