### ISSUE TITLE
Unable to run spectral on mac

### ISSUE THREAD

**Issue by apurva-1** [stoplightio/spectral#2412]
> For support questions, please use the [Stoplight Discord Community](https://discord.com/invite/stoplight). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, our Discord is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**
Unable to lint files using Spectral 5.6.0 and Latest 6.x version. Getting Error 

**To Reproduce**
1. Given this OpenAPI/AsyncAPI document 'petstore.yaml'
2. Run this CLI command 'spectral lint petstore.yaml'
3. Getting Error (Spectral version 5.6.0  and 6.6.0- 
        Found 82 rules (66 enabled)
        No results with a severity of 'error' or higher found!
4. 

**Expected behavior**
Get a list of Error and Warnings for the YAML file.

Actual Behaviour -
Found 82 rules (66 enabled)
No results with a severity of 'error' or higher found!

**Screenshots**

**Environment (remove any that are not applicable):**
 - 5.6.0 and 6.6.0
 - OS :Mac Pro

**Additional context**

**Comment by P0lip** [comment]
Could you please contact us on [Stoplight Discord Community](https://discord.com/invite/stoplight) and provide the ruleset you are trying to use?
We'll get it from there.
