### ISSUE TITLE
TypeError: oas3Rules is not a function

### ISSUE THREAD

**Issue by cbetta** [stoplightio/spectral#249]
### **I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### What is the current behavior?

When following the README. I'm now getting the error `TypeError: oas3Rules is not a function` with the latest version of Spectral.

### What is the expected behavior?

The code in the readme should work.

### Please tell us about your environment:

  - Version: 3.0.3
  - Framework: [ ]
  - Language: [ES6]

### Other information

It seems the syntax has changed between 2.X and 3.X, but the docs haven't been updated.

**Comment by P0lip** [comment]
@cbetta 
You are right, we've made a change to rulesets and haven't updated the readme yet.
My apologies for that.
We're planning to update the documentation very soon.

As of Spectral 3.x, there is no `oas3Rules` export member.

```ts
const { oas3Functions, rules: oas3Rules } = require('@stoplight/spectral/rulesets/oas3');
```
^ this is how you should import the rules now.

Let me know if you have any troubles and once again, sorry for any inconvenience caused.

**Comment by chris-miaskowski** [comment]
Hi @cbetta, good spot! Thank you for reporting it! I'll take a stab at updating the README in a moment. Should be a quick fix. 

To add to what @P0lip said the `rules` is actually asynchronous now.
So you'd need to do something along these lines
```
const { oas3Functions, rules: oas3Rules } = require('@stoplight/spectral/rulesets/oas3');
// assuming you are executing this in an async function, otherwise simply use oas3Rules().then()
const rules = await oas3Rules();
```

**Comment by cbetta** [comment]
Excellent, thank you!

**Comment by chris-miaskowski** [comment]
hey @cbetta. The docs are now up to date and I added some extras on top of the original issue. Thanks again for spotting and reporting!
