### ISSUE TITLE
Update proxy-agent to remove vulnerable vm2 dependency

### ISSUE THREAD

**Issue by matthewsac** [stoplightio/spectral#2519]
Dependabot issued a critical alert on the vm2 library which is used by proxy-agent. A new version of proxy-agent removes this vulnerability by replacing vm2. Spectral needs to be updated to use this new version.

Links to the two Dependabot alerts that relate to this issue:

[265](https://github.com/stoplightio/platform-internal/security/dependabot/265)
[266](https://github.com/stoplightio/platform-internal/security/dependabot/266)

Link to the new proxy-agent version to be used:
[proxy-agent 406.3.0](https://github.com/TooTallNate/proxy-agents/releases/tag/proxy-agent%406.3.0)

**NOTE**: This update must also be done for prism and platform-internal. See the links to the other issues in the comments.

**Comment by matthewsac** [comment]
Prism: https://github.com/stoplightio/prism/issues/2342
Platform-internal: https://github.com/stoplightio/platform-internal/issues/17519

**Comment by P0lip** [comment]
@matthewsac Spectral has been already addressed in #2513
