### ISSUE TITLE
Support for AsyncAPI v3.0.0

### ISSUE THREAD

**Issue by asangas** [stoplightio/spectral#2559]
**User story.**
As an API designer, I can use Spectral linter, so that I can lint my version 3.0.0 specifications.

**Is your feature request related to a problem?**
Version 3.0.0 is not supported by Spectral

**Describe the solution you'd like**
Extend the ruleset to support v3.0.0

**Additional context**
https://www.asyncapi.com/blog/release-notes-3.0.0

**Comment by msolujic** [comment]
hi, do we have any update on this one, any ETA for AsyncAPI v3 support in Spectral?
