### ISSUE TITLE
[Feature] Pass pattern some regex modifiers as a function option

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#2578]
**User story.**
As a ruleset developer, I can pass regex modifiers to the pattern function, so that I can make more advanced rulesets with everything regex has to offer instead of just the default mode.

**Is your feature request related to a problem?**

Working on https://github.com/stoplightio/spectral-owasp-ruleset/pull/51 I had to write some fairly hectic regex due to not being able to set the `/i` modifier for case insenstivity.
```
      then: {
        field: "description",
        function: pattern,
        functionOptions: {
          match: "((l|L)ocal|(a|A)lpha|(b|B)eta|(t|T)est|(t|T)esting|(s|S)tag|(s|S)taging|(p|P)rod|(p|P)roduction|(n|N)ext|(p|P)reprod)",
        },
      },
```
**Describe the solution you'd like**

```
function: pattern,
functionOptions: {
  match: "(local|alpha|beta|test|testing|stag|staging|prod|production|next|preprod)",
  modifiers: 'i'
},
```

Or you could make it nicer for people and make human named switches like `case-insensitive: true` or whatever.

**Comment by P0lip** [comment]
@philsturgeon 
Hey!
Have you tried `match: "/(local|alpha|beta|test|testing|stag|staging|prod|production|next|preprod)/i"`?

**Comment by philsturgeon** [comment]
@P0lip haha well don't I feel like a numpty. 

Added this to docs so it doesn't come up again.

Also hello! Hope you're doing well mate. 🙌🏻

**Comment by P0lip** [comment]
Thanks for the PR, I appreciate it.
I am doing fine, thanks! I hope you're doing great too!

**Comment by tomorswift** [comment]
> [@philsturgeon](https://github.com/philsturgeon) Hey! Have you tried `match: "/(local|alpha|beta|test|testing|stag|staging|prod|production|next|preprod)/i"`?

Thanks for that I was pulling my hair out!
