### ISSUE TITLE
no-dupe-keys rule

### ISSUE THREAD

**Issue by P0lip** [stoplightio/spectral#258]
### **I'm submitting a...**
  - [ ] bug report
  - [x] feature request

### What is the current behavior?

There is no way to report duplicated properties.
If you have an object containing 2 or more properties with the same key, Spectral operates on the value of the last property and this is very likely to be unwanted,

### What is the expected behavior?

Having duplicated properties is not desired. We could have a no-dupe-keys rule to help spot such issues.

### What is the motivation / use case for changing the behavior?

Linters such as ESLint provide [rules](https://eslint.org/docs/rules/no-dupe-keys) to detect such errors.

### Please tell us about your environment:

  - Version:  3.x.x
  - Framework: [ ]
  - Language: all

### Other information

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, issues outside of the repo, forum, etc.)

**Comment by philsturgeon** [comment]
This is probably a layover from Spectral rules being heavily inspired by Speccy rules. We used js-yaml which would throw errors if you had duplicate keys, so we didn't need to bother adding rules to detect that.

YAML is perfectly happy with duplicate keys, it's valid YAML, but invalid JSON. js-yaml has a `{ json : true }` config option which makes the YAML loader more strict, and triggers an error if this happens.

Spectral is using https://github.com/stoplightio/yaml which is using https://github.com/mulesoft-labs/yaml-ast-parser/, and that is a fork of js-yaml... so it can probably do the same.

That said, a big old error might not be what we are looking for. 

Hope this context helps. :D

**Comment by marbemac** [comment]
> YAML is perfectly happy with duplicate keys... a big old error might not be what we are looking for

Technically it does, but realistically how many situations would somebody want duplicate keys versus not want them? In general I suggest we build default behavior around  majority use cases.

**Comment by philsturgeon** [comment]
I wasn’t advocating for allowing duplicate keys. I was trying to outline how Speccy handles it, by turning up the strictness and erring out hard and early when it spots duplicates. That would be one potential solution for Spectral, otherwise we need to find some sort of parser which maintains duplicates so we can detect them programmatically and I’m not sure that’s an option.

**Comment by P0lip** [comment]
> I wasn’t advocating for allowing duplicate keys. I was trying to outline how Speccy handles it, by turning up the strictness and erring out hard and early when it spots duplicates. That would be one potential solution for Spectral, otherwise we need to find some sort of parser which maintains duplicates so we can detect them programmatically and I’m not sure that’s an option.

I'm all in for being more opinionated on that and not letting the end user control the behavior via a rule.
As Marc said, nobody really wants to have duplicated properties, so we can simply treat as some sort of syntax error and log it by default.
Thoughts?
