### ISSUE TITLE
Provide a solution for for fixing self-signed certificate errors in VSCode

### ISSUE THREAD

**Issue by ghost** [stoplightio/spectral#2599]
When I use VSCode with a url for the RuleSet file, I get:
Unable to read ruleset at ... failed, reason: self signed certificate in certificate chain
While most extensions will work in VSCode by pointing to the OS certificate store (using the win-ca or other method), this extension uses some other method for storing trusted root certificates. 

We use Netskope, which generates a custom certificate for the ruleset file url. But how to do we get Spectral to trust the root cert for this cusom CA? 

Can you please document a method for adding a root certificate to the Spectral root certificate store? Or fix Spectral to use the same certificate store used by VSCode?

Until then, we can not use Spectral in our environment as designe.d

**Comment by mnaumanali94** [comment]
Shouldn't the issue be here: https://github.com/stoplightio/vscode-spectral
