### ISSUE TITLE
@stoplight/spectral-core depends on jsonpath-plus <10

### ISSUE THREAD

**Issue by jacquesg** [stoplightio/spectral#2710]
**Describe the bug**
See: https://github.com/advisories/GHSA-pppg-cpfq-h7wr

**Comment by jacquesg** [comment]
With 5205058d1c9b48e6785b7744e2e2716cc7f1e0f4 merged, could a new release be cut?

**Comment by parithibang** [comment]
@jacquesg When can we expect a patch release?

**Comment by pjungermann** [comment]
```js
"nimma": "0.2.2",
```

This dependency `nimma` depends on `jsonpath-plus` with version `^6.0.1` (optional dependency).

The latest version is `7.0.0` and since `4.0.0`, it's only a dev dependency and no optional dependency anymore.

**Comment by Mariscal6** [comment]
> @jacquesg When can we expect a patch release?

+1

**Comment by jacquesg** [comment]
I'm not the maintainer, I asked the same question :)

**Comment by jacquesg** [comment]
A new version of `nimma` in the `0.2` series is now available: https://www.npmjs.com/package/nimma/v/0.2.3

**Comment by jacquesg** [comment]
Added a PR to bump the dependency #2712
