### ISSUE TITLE
Parameters in links objects shouldn't be linted for not having a description property.

### ISSUE THREAD

**Issue by garethj-msft** [stoplightio/spectral#272]
### **I'm submitting a...**
  - [ x ] bug report

### What is the current behavior?

Lint an OAS 3 with links section, where a link object has a parameters collection containing the usual name to path dictionary.
Get warnings like this:

Rule:
Parameter objects should have a description.

Details:
paths./allSchools/createUploadSession.post.responses.201.links.getUploadSessionById.parameters.sessionId.description is not truthy

But the parameters collection in a links object is not a parameters object.

### What is the expected behavior?
No warning.

### What is the motivation / use case for changing the behavior?
Correctness.

### Please tell us about your environment:
Web version.

**Comment by philsturgeon** [comment]
Ok this sounds like the rule for parameters is just a little greedy. The trouble with making them too specific is that then we have trouble linting on partial files with $ref, as if we just see the word parameters we dont know if its links parameters or operation parameters. 🤔

**Comment by marbemac** [comment]
Hmm, right now we look for parameters objects that don't have a $ref key. While still not perfect, a better indicator might be check for presence of an `in` key. This would cover $ref and also fix the issue described here re link parameters property false identification.

Relevant rule: https://github.com/stoplightio/spectral/blob/develop/src/rulesets/oas/index.json#L344
