### ISSUE TITLE
Release notes for v6.14.1 are malformed

### ISSUE THREAD

**Issue by rittneje** [stoplightio/spectral#2734]
https://github.com/stoplightio/spectral/releases/tag/v6.14.1

As you can see, the formatting is wrong. It also seems to have pulled in many items from previous releases for some reason?

The actual diff is here: https://github.com/stoplightio/spectral/compare/@stoplight/spectral-cli-6.14.0...@stoplight/spectral-cli-6.14.1

**Comment by mnaumanali94** [comment]
Good catch. That's another part of the pipeline that we need to fix. I have updated those manually for now. Thank you!

**Comment by mnaumanali94** [comment]
@rittneje Close away if you think its all good now 🙏🏼
