### ISSUE TITLE
`spectral:arazzo` breaks with file not found in VSCode

### ISSUE THREAD

**Issue by erwinkramer** [stoplightio/spectral#2736]
**Describe the bug**
When using the Spectral VSCode extension i get the following output:

```
Using ruleset file: .
[Error - 12:53:55 AM] An error occurred while validating document c:\Users\erwin\bank-api\specs-generated\openapi.json: Unable to read ruleset at c:\Users\erwin\bank-api\.spectral.yml. Error: Could not load c:/Users/erwin/bank-api/spectral:arazzo (imported by .spectral.js): ENOENT: no such file or directory, open 'c:\Users\erwin\bank-api\spectral:arazzo'
seenDependencies (before): 0.
```

**To Reproduce**

Make a `.spectral.yml` file like this:

```
extends: ["spectral:oas", "spectral:arazzo"]
```

Then run it with VSCode and see it fails.

Then run it with the CLI and see the (supposedly fine) output: 

```
spectral lint ./specs-generated/openapi.json -v -F "hint"
Found 78 rules (67 enabled)
Linting c:/Users/erwin/bank-api/specs-generated/openapi.json
No results with a severity of 'hint' or higher found!
````

**Expected behavior**
Should work. It works with Spectral CLI, so should work with VSCode too (or at least have a consistent result over all forms).

**Environment (remove any that are not applicable):**
 - Library version: latest
 - OS: WIndows 11

**Additional context**
You can easily test it on this repo: https://github.com/erwinkramer/bank-api?tab=readme-ov-file#bank-api

**Comment by frankkilcommins** [comment]
Hi @erwinkramer,

Thanks for reporting. This probably belongs over at https://github.com/stoplightio/vscode-spectral. 

FYI - we've added Arazzo support to the vscode extensions but need to release (which we'll get to very soon).

**Comment by erwinkramer** [comment]
@frankkilcommins i see the merge, great! When will it be actually released to the marketplace?

**Comment by erwinkramer** [comment]
Everything works as expected now. Thanks. Going to close this.
