### ISSUE TITLE
Ruleset for attributes.

### ISSUE THREAD

**Issue by AshwithGundu** [stoplightio/spectral#278]
How can we check the attributes in the parameters section are in camelCase naming convention or not?
I mean like could someone give the ruleset for the above mentioned question.
Ex: companyName, age

**Comment by tbarn** [comment]
Hi @AshwithGundu! 

Could you share some of the code you've tried to do it with? It will help with a starting place of where you are and we can help from there.

**Comment by philsturgeon** [comment]
Take a look at #405 for some hints, we're gonna build some core rules, but you can get started with your own using the examples.
