### ISSUE TITLE
Spectral blog: Rulesets, Config, and GitHub Actions!

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#306]
We were so busy adding excellent new functionality we didn’t get around to blogging about it all. 

Let’s write up an article for the stoplight blog about everything since the last blog post: https://stoplight.io/blog/introducing-spectral/

Talk to Taylor and Scott about what format it should be in, and what the process looks like. This is our first attempt at providing content so we’ll have to figure out how it works.

**Comment by tbarn** [comment]
Live
