### ISSUE TITLE
Spectral Release Video 

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#308]
**Summary**
Scott to coordinate with Phil and Videographer to create and post up a video explaining Spectral. 

**User Story(s)**
n/a

**Scope**
- [x] develop spectral video script and flow 
- [x] create video asset 
- [x] include video into github README.md 
- [ ] include video on Spectral subpage

**Comment by tbarn** [comment]
Will open separate issue to get new button added on website
