### ISSUE TITLE
Spectral Release Webinar

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#309]
**Summary** 
Plan, Market, and host a webinar announcing the launch of Spectral and covering its feature set. 

**Scope**
- [ ] create webinar script 
- [ ] marketing and planning for webinar 
- [ ] host webinar 
- [ ] post webinar on Spectral sub-page

**Comment by tbarn** [comment]
I'm going to make a new issue announcing it to the community and closing this to avoid confusion.
