### ISSUE TITLE
Get rid of the "example" discrepancy between upstream JSF and SL/JSF

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#312]
**User Story**

As I Stoplight developer I want to use the upstream JSON Schema Faker and be able to leverage both example and examples properties.

**Background**

That change was added in order to support generating json examples in the next platform. 

First commit that initiated the work can be found here https://github.com/stoplightio/json-schema-faker/commit/4e3646e244c902ab7ff2b69e3d76e2e2de4df55a

**Repos using @stoplight/json-schema-faker**
- prism
- yogi (not sure whether we still use this repo anywhere...)
- platform
- studio

**Ideas for removing the discrepancy**
- merge the change to the upstream
- try to leverage https://github.com/json-schema-faker/json-schema-faker/tree/master/docs 

```
3.5 - extend keywords with custom generators
jsf.define('myProp', (value, schema) => schema);
```

**Comment by P0lip** [comment]
Unrelated to Spectral.
