### ISSUE TITLE
Hosted Spectral 

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#322]
## User Story

As a potential non-technical Stoplight user, I want to try out some of the products without signing up for an account or downloading CLI tools (what is a CLI?!). Getting feedback from Stoplight on my specifications might convince me to sign up for an account.

## Details

On the public-facing Spectral project website (SO-5) we should allow people tocopy and paste specs or provide a URL, and it will generate reports like https://www.ssllabs.com/ssltest/

## Acceptance Criteria
- No custom ruleset support just use Spectral's autodetect for OAS2/3
- Anonymous users can get feedback on a chunk of YAML /JSON 
- Anonymous users can get feedback on a URL
- Common sense security logic to avoid letting downloaded content be executed
- Common sense file size limitations (find the biggest OpenAPI file we know about and set the limit 10% higher)
- A list of warnings and errors will show up on a report 
- Report should have “private permalink” (non auto increment) so I can share the report with anyone who has the link

**Comment by brianmrock** [comment]
Comment history from Jira 

Phil Sturgeon
May 31, 2019, 1:56 AM

Taylor Barnett Scott Faust Marc MacLeod howdy! If this was to be done, what would you think we should do about converting these anonymous users into stoplight users?

Once they’ve run spectral on their docs, we could very easily have some screenshots of Studio as static ads that they then might just download, or we could have “Sign in with GitHub to run Spectral on more Repos” sorts of things.

This was a commonly requested Speccy feature, and I think it’ll really help with our marketing efforts. People love sharing little utilities that are clearly useful without having to advertise the whole platform.


Taylor Barnett
May 31, 2019, 10:52 AM

This would be awesome to have in the Spectral website!

Also it makes me wonder, should we bring the "Spectral" branding more into Studio so people understand the connection there? 


Phil Sturgeon
May 31, 2019, 11:40 AM

I’m not sure what spectral branding or studio branding look like currently so dunno about all that. 

Something that shows these are all seperate apps in a suite would be cool, but i also dont want to make people think you have to use all the things. The messaging I’d like aimed at developers is: you can use any of these things and glue em together, or grab your bosses credit card and we’ll glue it and host it for you. 

So Spectral should look like its related to Studio, but not “part of” it. 


Taylor Barnett
May 31, 2019, 11:49 AM

What I am thinking about is, someone sign-ins to run Spectral on more repos, and then the whole concept of "Spectral" disappears. It would be confusing. 


Phil Sturgeon
May 31, 2019, 12:21 PM

Oh yeah we don’t hide that from them, if we’re asking them to sign up to studio we tel them they’re signing up to studio 


Marc MacLeod
June 2, 2019, 9:57 PM

What if we put a powered by spectral w link to the github repo in relevant parts of the UI (really only the diagnostics area pictured below for now)?


 


Phil Sturgeon
June 3, 2019, 12:49 AM

Hey yeah that’s cool, but i think it’s backwards if the problem Taylor and I were discussing. We want to convert folks using online studio to other tooling, which they might then pay for. 


Taylor Barnett
June 3, 2019, 11:07 AM

Marc MacLeod That's actually the original problem I was bringing up.

But what you mentioned Phil Sturgeon is valid too!


Phil Sturgeon
June 3, 2019, 11:14 AM

Oh! I had it wrong! Well, I was trying to convert SpectralFreebyWebsiteUsers to Stoplight Dojo directly, or via Studio (because that has a lot of conversion baked i anyway) but… sure? Powered by Spectral seems handy.


Taylor Barnett
June 3, 2019, 11:49 AM

Yeah, it is the same issue I am talking about, but if you are a SpectralFreebyWebsiteUsers and go to Stoplight Dojo, you will be like, where's Spectral I was promised? 


Phil Sturgeon
June 3, 2019, 11:56 AM

OH right so “Sign in with GitHub to run Spectral on more Repos” could be:

A.) We add some actual functionality to the spectral website which will do a really light version of what analyzer is doing as a way to get user contact information for free and then try to convert those users, or

B.) “Sign up for Stoplight Platform to get all this and mooooore“

I’m not trying to write actual copy in these comments. :)


Marc MacLeod
June 3, 2019, 3:24 PM

For spectral specifically, I was thinking that the hook is more along the lines of shared / organizational custom style guides. So in Studio wherever we end up putting the configuration for spectral customization, we could add a dropdown to choose from shared style guides. Usage of that could funnel to create an account / organization in platform.


Phil Sturgeon
June 5, 2019, 3:34 PM

Yeah there are definitely a bunch of ways we can convince Studio users to upgrade to have a paying account. Maybe we could start up a story for that?

This thread should be figuring out some conversions from hosted spectral to:

Studio

Dojo

Other

and making sure they arent confused when they get there.

**Comment by tbarn** [comment]
Now Live thanks to @ssspear @P0lip @lottamus!

**Comment by philsturgeon** [comment]
We actually haven’t done any work at all on hosted spectral... that’s a web tool where folks can upload their own api descriptions and get feedback. This work was paused when it was discovered @rossmcdonald is working on a similar but different project.

**Comment by tbarn** [comment]
Oh, I misread the acceptance criteria. Carry on.

**Comment by philsturgeon** [comment]
I was wrong @taylor! I didn't see the sandbox we added (vacation :D). We can extend what is there if people ask for it, let's close this. Awesome job!
