### ISSUE TITLE
Prism : Integrate TestRail into Test Harness 

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#329]
**User Story**

As a Stoplight developer I want to be able to link test harness tests to specific test cases in TestRail, and to do that I need somewhere to put the "Case ID" e.g: C-123.

**Acceptance Criteria**
- Somewhere (could be body, filename, wherever) the case ID should be incorporated into test harness
- Not all tests need to have a case ID (for now at least) so it must be optional
- Reporting back to TestRail via their API or however integration works

**Comment by philsturgeon** [comment]
@XVincentX did we integrate test rail into the test harness already?

**Comment by XVincentX** [comment]
Hmm no; the harness's been there in steady state. We have only two tests and it's not automatically linked to anything.

**Comment by tbarn** [comment]
Is this for Prism or Spectral? Title says Prism.
