### ISSUE TITLE
Add migration documents from 3.X => 4.X

### ISSUE THREAD

**Issue by cbetta** [stoplightio/spectral#364]
**Chore summary**

To make it easier for someone to migrate an existing project.

**Tasks**
- [ ] Needs to explain what has changed
- [ ] Needs to provide a simple summary as to what changes the developer probably needs to make.

**Additional context**

I have Spectral integrated into Jest with some custom rules, and I’m getting errors when upgrading to 4.0. I can’t tell what I need to change, as there’s no clear document listing what changes have been made.

**Comment by tbarn** [comment]
I'm going to try to get something done on this next week. I could probably summarize one, but I think I'd be missing somethings so I am going to work with @P0lip on it.

**Comment by cbetta** [comment]
Thanks. I think the main issue I ran into was the fact that the import changed when using regular Node:

```diff
+ require('@stoplight/spectral/dist/rulesets/oas3')
- require('@stoplight/spectral/rulesets/oas3')
```

**Comment by tbarn** [comment]
Hey @cbetta, we just merged a migration guide. Hopefully it will fill in any gaps you have: https://github.com/stoplightio/spectral/blob/develop/docs/migration-guides/4.0.md

**Comment by cbetta** [comment]
🎉
