### ISSUE TITLE
Weird behave with error messages from custom functions

### ISSUE THREAD

**Issue by rafaelrocha** [stoplightio/spectral#367]
**Describe the bug**
Two weirds behavior with error messages from custom functions:
On Spectral 3.0.4  the rule's summary value overrides custom function message.
On Spectral 4.0.0 the rule's description value overrides custom function message. 

**To Reproduce**
[To reproduce 3.0.4](https://repl.it/@RafaelRocha2/IsItABugOnFunctionCustomMessage-304)
[To reproduce 4.0.0](https://repl.it/@RafaelRocha2/IsItABugOnFunctionCustomMessage-400)

**Expected behavior**
[The expected behavior would be like We can see on version 2.0.6](https://repl.it/@RafaelRocha2/functionCustomMessage-206)

Let me know whether I'm missing any other information.

And thanks for the great work with this tool folks!

**Comment by tbarn** [comment]
Hey @rafaelrocha! Thanks for the examples. Super helpful. I'm going to look more into this in the morning.

**Comment by P0lip** [comment]
Hello @rafaelrocha.
You are right - we, in fact, did change the behavior in 3.x.
Luckily, despite the lack of `summary` field, you can still achieve the expected output.
To get the old behavior back, you need to define a property `message` and put the following expression as the value:
```ts
message: '{{error}}',
```
`{{error}}` will be replaced with the message returned from the function.

[Here](https://repl.it/repls/HighDefinitiveFilesize) is the updated example.
Let me know if that's what you expected.
Happy to help further in case you find it insufficient.

**Comment by rafaelrocha** [comment]
Oh! I see. It definitely helps me.

Thanks you both, @tbarn and @P0lip !!

**Comment by P0lip** [comment]
Great to hear that!
If you have any further concerns, don't hesitate to reach out to us :)

**Comment by rafaelrocha** [comment]
Hi @P0lip , 

I just realized that the behavior of summary is still weird, looks like the error message is overriding its value. [here](https://repl.it/@RafaelRocha2/HighDefinitiveFilesize-1)

Is there something I could do to fix it as well?

**Comment by rafaelrocha** [comment]
Hi @P0lip ,

How about the summary value that is missing, is there anything I can do to get this values as well? [I'm testing here](https://repl.it/@RafaelRocha2/HighDefinitiveFilesize-1)

**Comment by P0lip** [comment]
@rafaelrocha
I'm afraid to inform you there is no way to have a `summary` property on validation result.
`summary` is gone entirely.
You can still have `description` printed, though.
If you want to go even further, you can even inline summary in a message.
https://repl.it/repls/DeepskyblueAchingForm

This is a bit hacky yet shows it's possible.
Does it help you in any way?

**Comment by rafaelrocha** [comment]
oh boy, I see. We were grouping the error messages by it and showing something like what you can see below:

```
[error] API Spec - MUST - Contain Information about Domain Model: x_domain_required
  - path: info
    message: The x-domain is not defined.
  - path: info
    message: The x-subdomain is not defined.
```

Anyway, we're going to re-evaluate how to present theses messages, thanks for the great support!!

**Comment by P0lip** [comment]
@rafaelrocha 
You are welcome!
If you need it for grouping purposes, consider using `code` property instead, as it might be a more stable property to group by.
