### ISSUE TITLE
Do not require JSON Schema to be inlined in rulesets

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#380]
**User story.**
As a ruleset maintainer, I would like to create rulesets which do not have JSON Schema inline, so that I can have more rules in a more concise file. 

**Is your feature request related to a problem?**
Currently the oas2 and oas3 rulesets have the OpenAPI metaschema files, and this is bloating a 100 line ruleset to almost 2k lines.

https://github.com/stoplightio/spectral/blob/develop/src/rulesets/oas2/index.json#L106

**Describe the solution you'd like**

Let’s add support for $ref with json-ref-resolver. 

```
    "oas2-schema": {
      "description": "Validate structure of OpenAPIv2 specification.",
      "message": "{{error}}",
      "type": "validation",
      "severity": 0,
      "recommended": true,
      "given": "$",
      "then": {
        "function": "schema",
        "functionOptions": {
          "schema": {
            "$ref": "../oas2-metaschema.json"
          }
        }
      }
```

**Comment by marbemac** [comment]
How about we take advantage of $refs, since we already have a very capable json-ref-resolver loaded up in Spectral? Could just dereference the ruleset file after loading it. This would be like an hour of work. Something like this:

```
"oas2-schema": {
      "description": "Validate structure of OpenAPIv2 specification.",
      "message": "{{error}}",
      "type": "validation",
      "severity": 0,
      "recommended": true,
      "given": "$",
      "then": {
        "function": "schema",
        "functionOptions": {
          "schema": {
            "$ref": "../oas2-metaschema.json"
          }
        }
      }
```

In fact, if we supported $refs in the ruleset file, they could be used in all sorts of ways to de-dupe things.

**Comment by philsturgeon** [comment]
@marbemac I think this would 100% lock us in to rulesets always being defined in JSON/YAML, and definitely not being TypeScript, right? Is that something we want to do?

**Comment by marbemac** [comment]
Probably missing something - could you share an example?

---

Defining in json versus ts shouldn't really matter, at least for the use cases I've considered - but again I might be missing something.

**.spectral.json**

```json
{
  "rules": {
    "oas2-schema": {
      "description": "Validate structure of OpenAPIv2 specification.",
      "message": "{{error}}",
      "type": "validation",
      "severity": 0,
      "recommended": true,
      "given": "$",
      "then": {
        "function": "schema",
        "functionOptions": {
          "schema": {
            "$ref": "../oas2-metaschema.json"
          }
        }
      }
    }
  }
}
```

**spectral.ts**

```ts
export const myRuleset = {
  rules: {
    "oas2-schema": {
      description: "Validate structure of OpenAPIv2 specification.",
      message: "{{error}}",
      type: "validation",
      severity: 0,
      recommended: true,
      given: "$",
      then: {
        function: "schema",
        functionOptions: {
          schema: {
            $ref: "../oas2-metaschema.json"
          }
        }
      }
    }
  }
};
```

**Comment by philsturgeon** [comment]
You got an example there that looks like it’ll be fine. Alrighty, updating the description!

**Comment by P0lip** [comment]
I'd be very cautious about usage of `$refs` here. While usage of them in non-restricted environments such as the Node.js one is in fact safe and straightforward, supporting them reliably in a browser or worker envs may turn out to be more difficult.

I'd suggest adding an extra build step here and simply resolve those $refs during the build time.
What do you think?

@philsturgeon @marbemac

**Comment by nulltoken** [comment]
> I'd suggest adding an extra build step here and simply resolve those $refs during the build time.

@P0lip Would that forbid Spectral users from benefiting from that handy proposal?

**Comment by philsturgeon** [comment]
There is no build time for arbitrary YAML file passed into CLI via URL/Path. 

--
Phil Sturgeon
@philsturgeon

**Comment by nulltoken** [comment]
@philsturgeon That was indeed my understanding. Would there be a way for spectral users to also be able to externalize their schemas from their rulesets?

**Comment by P0lip** [comment]
@nulltoken @philsturgeon
In general, I'm not against utilizing json-ref-resolver for this case.
I suspect that the vast majority of  Spectral users run Spectral in Node.js environment, so they don't have any meaningful restrictions.
What I wanted to point out is that fs-like $refs are unlikely to be resolved properly in an environment with shimmed or no fs module, such as browser or worker, therefore we need to be more careful in this regard.
That said, we can still find a robust solution to keep both parties satisfied.
Here is what I propose:
- register a custom protocol handler in json-ref-resolver (such as `spectral://` - that handler could use internal resolve function we use for resolving rulesets - the function is pretty much environment-safe)
- fs-based access would be allowed in such a case, but at the risk of developer - if someone does not aim to run the code in a browser, we should not forbid that

Thoughts?

**Comment by philsturgeon** [comment]
This is an interesting problem and y'all making great points. An original goal for rulesets was to have something so simple it could be a single JSON/YAML file, but reality has got in the way of that goal. 

We already have the problem where #430 is going to add functionality not available to a Ruleset-on-a-URL, and this just seems like another thing. That said, its not a confusing thing. If you are putting your Ruleset-on-a-URL then expect it to be HTTP-resolvable, right? Browsers are gonna try and follow $refs, normal internetting rules apply? 

Rulesets as NPM: can do literally anything, enjoy.
Rulesets as local files: can do literally anything enjoy
Rulesets on a URL: cant have custom functions or hit the filesystem :shrug:

Seems ok to me.
