### ISSUE TITLE
Option to hide warnings

### ISSUE THREAD

**Issue by Flori00** [stoplightio/spectral#383]
I don't need the warnings, I only need the errors.
I can't remove the warnings, is there a command?
I want that only the Errors get displayed.

**Comment by philsturgeon** [comment]
For now there is not a feature to return only errors, but you can write a custom ruleset which turns off all the rules and only enables the ones you’re interested in. Check out docs/rulesets.md for an example.

A similar feature is being discussed on #368

**Comment by philsturgeon** [comment]
I think we'll be implementing this as part of #368 so let's just chat over there.
