### ISSUE TITLE
docs: new guide for Continuous Integration

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#388]
Take the `Continuous Integration` content from workflows and make a new guide (link to it from workflows). 

https://github.com/stoplightio/spectral/blob/5ac0a309088503a4a8e17fa6e1f820c8a7dfe160/docs/guides/workflows.md#L47

This can be extended to use the new `--format=junit` option added in #478, and --output=foo to output content to a known location then have CircleCI see that. Add some screenshots of how it looks in CircleCI.

Bonus points if you also add instructions for Travis CI.

Add an `## Other Integrations` section with a link to our Spectral GitHub Action (#327) and Taylors Spectral GitHub Bot (https://github.com/tbarn/spectral-bot)

**Comment by marbemac** [comment]
Phil, is this still relevant? If so, all you ;).

**Comment by philsturgeon** [comment]
Yeah we still want to document how CI works, its a common question which deserves more than a section on workflow.

**Comment by philsturgeon** [comment]
Oh sorry I missed the question. Yes I'd be happy to write docs, but this also assumes #327 is done otherwise the GitHub Action is not very useful for a huge chunk of our users.

**Comment by philsturgeon** [comment]
Done in https://github.com/stoplightio/spectral/pull/1623
