### ISSUE TITLE
new rules: error for anyOf & oneOf in OpenAPI v2

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/spectral#393]
**User story.**

As an average user who is not completely familiar with the intricacies of JSON Schema <≠> OpenAPI and the differences between OpenAPI v2 and v3, I often mix up JSON Schema, OAS2 and OAS3 keywords like anyOf and oneOf, so please let me know when I put the wrong keyword in the wrong place.

**Is your feature request related to a problem?**

API description documents should conform to the description format in question, as putting invalid keywords in those documents can lead to inconsistent behavior across various tools that might mistakenly support those keywords. Other tooling which is actually compliant will then look like its failing.

**Describe the solution you'd like**

The rule should error if an `anyOf`, `oneOf` or `not` appears in OpenAPI v2, but `anyOf` is in fact allowed.

**Comment by marbemac** [comment]
In fact we should just report usage of oneOf or anyOf as errors in openapi, since it's not valid openapi - no need for separate "strict" concept.

**Comment by tbarn** [comment]
Except in v3 though, right?

**Comment by philsturgeon** [comment]
V2 has allOf
V3 has allOf, oneOf, anyOf, not

**Comment by tbarn** [comment]
We also let people in Next create OAS v2 specs with oneOf and anyOf, so we might need to explain that too.

**Comment by philsturgeon** [comment]
Is it x-oneOf and x-anyOf or are we putting invalid keywords into their API description documents? 

This is all the more reason to create errors for oneOf and anyOf in Spectral. Folks can turn the rule off if they really want to keep on writing invalid documents.
