### ISSUE TITLE
Support yaml anchors

### ISSUE THREAD

**Issue by ioggstream** [stoplightio/spectral#404]
**Describe the bug**
The following yaml with anchor does not validate correctly

**To Reproduce**

1. Go to online spectral parser
2. paste the content of the following yaml https://paste.fedoraproject.org/paste/F8NCdqF9qO7QDRTwiA1vmA
3. See error

```
/paths//pets/post/responses/default should have required property '$ref'
``

**Expected behavior**
No errors

**Environment (remove any that are not applicable):**
 - Browser: Chrome 61

**Comment by P0lip** [comment]
Hey @ioggstream.
Thanks for reaching out!
I'm afraid to say we don't handle merge keys at the very moment.
This particular feature does not seem to be a part of the spec, but it's rather an extension to it, therefore it's not supported out of the box.
Don't worry - it's a popular feature we really want to provide support for, so the issue you face will eventually be gone.
I can't assure you of any date, but it's in our roadmap and will be implemented soon.

**Comment by ioggstream** [comment]
@P0lip Thanks for your reply and you PR!

Just for curiosity, which are the advantages of not using an external yaml library?

**Comment by XVincentX** [comment]
@ioggstream Spectral needs more than the parsed result.

It needs source maps, access to the raw AST and access utilities that no library's offering at the moment.

**Comment by P0lip** [comment]
@ioggstream 

As Vincenzo stated, there is no ready-to-go solution that would meet all of our requirements.
For instance, there is no utility that would allow us to map given property (using json path) to the actual place in the file. We have our own implementation of that functionality over [here](https://github.com/stoplightio/yaml/blob/master/src/getLocationForJsonPath.ts) - this function is used heavily by Spectral.
Then, in our other products, on a number of occasions, we need to reverse the lookup and find the most relevant JSON path for a given location. This is implemented [here](https://github.com/stoplightio/yaml/blob/master/src/getJsonPathForPosition.ts).

The primary reason though, a bit unrelated to Spectral, is the fact we need to support JSON and Markdown in the same manner, exposing the same interface.
https://github.com/stoplightio/json
https://github.com/stoplightio/markdown
