### ISSUE TITLE
Support execution behind a corporate proxy

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#446]
**User story.**
As a user working behind a corporate proxy, I can configure spectral, so that I can run it without errors when `ref$` points to internet based urls.

**Is your feature request related to a problem?**
In #245, @marbemac made it possible to resolve http based remote references. 

https://github.com/stoplightio/spectral/blob/027664fcf7f58f542a323d338b9017ba18adc9a3/src/resolvers/http.ts#L7

However, for those of us working behind a corporate proxy, well... things do tend to _not_ work. 

```
 842:13    error  [invalid-ref] FetchError: request to https://REDACTED/doco.yaml failed, reason: connect ETIMEDOUT XX.XX.XX.XX:443
```

**Describe the solution you'd like**
- Ideally, supporting `http_proxy` and `https_proxy` would just be awesome :tada:
- An optional argument to the cli would also fit my request.

**Additional context**
https://github.com/bitinn/node-fetch/issues/195

**Comment by marbemac** [comment]
Hmm, simplest is probably using something like https://github.com/gajus/global-agent when in node context. Would require bumping minimum node version up to v10 since they rely on language features (versus monkey patching etc), but that's probably alright since node 8 is EOL in December anyways. Thoughts @P0lip @philsturgeon?

**Comment by philsturgeon** [comment]
@marbemac great idea, let's do it this way. Seeing as node-fetch is based on requests internally this should work just fine. 

@nulltoken do you have a workaround for now? We can raise node requirements to v10 for v5.0 but doing it for v4.x might be a bit cheeky. If we find a few more breaking changes we'd like to do (removing addRules and addFunctions for example) then it'd be nice to do it later on, but I also don't corporate firewall users to be blocked for three months.

**Comment by nulltoken** [comment]
@philsturgeon Well, my current workaround is tethering through my mobile... which isn't the richest experience ;-)

Would you know the _forecast_ ETA for 5.0?
Any chance to get a beta channel release?

For what it's worth, I'd be a taker for a `-dev` channel release released whenever a PR is merged.

**Comment by philsturgeon** [comment]
@nulltoken yeah I'll just put together an ad-hoc v5 branch and start putting together breaking changes in there, and we'll merge it to develop when its time to get serious about it. What install channel are you using? Docker? NPM?

**Comment by nulltoken** [comment]
> What install channel are you using? Docker? NPM?

Npm

> I'll just put together an ad-hoc v5 branch

:heart:

**Comment by philsturgeon** [comment]
Sorry for the delay here, we were cranking on v4.1.0. We’ll take this on as part of the sprint starting today, and develop will become the v5 branch.

**Comment by nulltoken** [comment]
@philsturgeon So glad this got merged. Do you foresee a release of this as part of the v4 branch soon?

**Comment by philsturgeon** [comment]
For sure. We started tagging v4.2-beta’s just before this one was merged so there’ll be another beta soon. 

--
Phil Sturgeon
@philsturgeon

**Comment by P0lip** [comment]
@nulltoken 
v4.2.0-beta2 containing this proxy feature has just been released.
