### ISSUE TITLE
Formatter: JUnit

### ISSUE THREAD

**Issue by ryandcoates** [stoplightio/spectral#478]
**User story.**
As a cli user, I can do output in a format supported by Azure Pipelines, so that I can display the test report during each pipeline run.

**Describe the solution you'd like**
Azure piplines 'Publish Test results' task supports a number of outputs, assume JUnit or NUnit/XUnit would be the best option
[More info here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)

**Comment by philsturgeon** [comment]
JUnit would definitely be useful, for Azure, CircleCI, and most other popular tools. It’s the one I’ve needed the most. https://circleci.com/blog/how-to-output-junit-tests-through-circleci-2-0-for-expanded-insights/

I assume with that done we can add other similar formats like xUnit in the future.
