### ISSUE TITLE
Add OAS check for un-used definitions

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/spectral#49]

**Comment by nulltoken** [comment]
Being pointed at to unused definitions would indeed be very useful!

**Comment by Amachua** [comment]
Agreed, do you plan to make such update soon? :)

**Comment by philsturgeon** [comment]
@Amachua it's currently not on the roadmap, but I absolutely agree this would be useful. @nulltoken is an awesome contributor but he's not on the company payroll. 

@nulltoken if you want to take a swing at this, I'll be happy to [plant 500 trees](https://offset.earth/philsturgeon) on your behalf :D

**Comment by nulltoken** [comment]
@philsturgeon Awww.... That's a good offer.

Although I've read some portions of the code, I'm not familiar enough with it to even measure the complexity of the change.

Let me take some days to see if I can commit to such a thing.

**Comment by nulltoken** [comment]
> Agreed, do you plan to make such update soon? :)

@Amachua It's now in progress. You can :eyes: an early proposal at #635
