### ISSUE TITLE
Allow multiple paths as argument

### ISSUE THREAD

**Issue by mrjoops** [stoplightio/spectral#534]
**User story.**
As a CI tool, I can lint all the files in a repository, so that I can see a report for all the files with a single command line.

**Is your feature request related to a problem?**
It is time consuming to iterate manually through all files, run the command, store the status, do some computation to get the global status and display the report.

**Describe the solution you'd like**
Today only one file is accepted as argument, it would be great to accept multiple paths (file or directory), maybe with wildcards too.

**Comment by P0lip** [comment]
@mrjoops 
Thank you for submitting the idea. I really like it.
It's in fact something we could improve, therefore I'm more than happy to include it in our development roadmap.
I can't promise on any deliverables in this or next week, but hopefully the change is included in the next major or minor release.

**Comment by philsturgeon** [comment]
I put it into the October feature sprint so that'll probably be v5.1 as this feature sprint aims to get v5.0-beta1 ready.
