### ISSUE TITLE
ruleset: JSON:API

### ISSUE THREAD

**Issue by ahx** [stoplightio/spectral#544]
**User story.**
As a developer, I can use Spectral to guide me while designing my [JSON:API](https://jsonapi.org/) API.
Spectral returns errors and warnings if responses do not look like JSON:API responses.

**Describe the solution you'd like**
I can use a new ruleset jsonapi-openapi which extends the spectral:oas ruleset. Using this ruleset helps me describe APIs that conform with JSON:API.
Beginning with rules to describe response bodies only would be a great start.

**Additional context**
Could we make use of http://jsonapi.org/schema ?

I hope this makes sense.

**Comment by philsturgeon** [comment]
@dgeb did you ever make any progress on this one?

**Comment by philsturgeon** [comment]
Also should it be a "JSON Schema in OpenAPI" ruleset? Because im not sure how a "plain JSON:API" ruleset would work, as we need a JSON/YAML file to look at.

**Comment by ahx** [comment]
@philsturgeon 
> Also should it be a "JSON Schema in OpenAPI" ruleset? Because im not sure how a "plain JSON:API" ruleset would work, as we need a JSON/YAML file to look at.

It should work just like the other rulesets, but tailored to be helpful when designing JSON:API conform APIs. I don’t think I understand your question.

**Comment by philsturgeon** [comment]
“When designing an API” designing how? Designing with OpenAPI or when designing with RAML? There has to be some sort of medium for it to look at, so I’m trying to confirm that everyone is ok with “JSON:API in OpenAPI”.

**Comment by ahx** [comment]
@philsturgeon designing with OpenAPI. Using OpenAPI YAML files as a medium. 
I am thinking about an OpenAPI first approach. – Writing the OpenAPI file first (YAML), then everything else.

**Comment by michaelmerrill** [comment]
@ahx any progress on this? I'd be happy to help!

**Comment by ahx** [comment]
@michaelmerrill I did not do any work in this. Sorry. 😬
Note that there is also https://github.com/openapi-contrib/style-guides.
