### ISSUE TITLE
Wrong deprecation message?

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#551]
https://github.com/stoplightio/spectral/blob/54c91f12010bed9fb29bf6f02b4be245aa4d4bf2/src/spectral.ts#L115-L116

Shouldn't this reference `setFunctions`?

**Comment by philsturgeon** [comment]
Nope we’re removing addRules and addFunctions in v5.0. Set is replace and has larger utility than addRules which is only additive. This is correct :)

**Comment by nulltoken** [comment]
@philsturgeon Thanks for sharing this. 

Maybe should the changelog also reflect that mid-term plan?

It currently states `addRules and addFunctions have been deprecated, use setRules and setFunctions instead`, which makes the deprecation message a bit confusing.

**Comment by philsturgeon** [comment]
I see what you’re saying but not quite. The setFunction stuff is a helper not really intended for widespread usage. The previous use case of folks wanting to use addFunctions was adding custom functions to their rulesets, but that is now in clouded in the general ruleset logic which is loaded with loadRuleset().
