### ISSUE TITLE
Clear out old TS rules and functions

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#561]
Go on a delete-spree taking away all of the old TS ruleset stuff. 

- [x] Spectral.addRules() 
- [x] Spectral.addFunctions()
- [x] src/rulesets/oas/index.ts
- [x] src/rulesets/oas2/index.ts
- [x] src/rulesets/oas3/index.ts
- [ ] src/types/rule.ts
- [ ] anything else?

Whenever this gets done, it means the next release will need to be v5.0.

**Comment by philsturgeon** [comment]
@nulltoken if you want to start nuking bits I would really appreciate that. It would solve the confusion in #677.

**Comment by nulltoken** [comment]
@philsturgeon Let me see what I can come up with.

**Comment by nulltoken** [comment]
> @philsturgeon Let me see what I can come up with.

So... I've started to chew on #689. It may not cover all the scope of _this_ issue but should definitely hit "the one ruleset to rule them all" topic from https://github.com/stoplightio/spectral/pull/677#issuecomment-542388747.

To start with, I'm going to learn a bit from the failing tests that are going to break. Then I might ping @P0lip when I've got a rough proposal of what I'd like to propose.

**Comment by P0lip** [comment]
> Then I might ping @P0lip when I've got a rough proposal of what I'd like to propose.

Sure thing @nulltoken. As always, I'm happy to help. :)
LMK once you have anything you'd like to share. Good luck!
Huge thanks for your contribution. :heart:

**Comment by philsturgeon** [comment]
Let's bump the default --fail-severity to `warn` while we are at it, as this is a biiiig breaking change and we can use it as a basis for 5.0. Right now it's `hint` (to avoid breaking BC.

**Comment by P0lip** [comment]
Done in https://github.com/stoplightio/spectral/pull/773
