### ISSUE TITLE
Create rule format for JSON schema files

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/spectral#571]
I believe there is only support today for OpenAPI formats. We should also allow users to run rules against JSON schema formats (or just generic objects, whichever is easiest).

The context here is that we need to allow Studio users to run rules on JSON schema files. I was thinking we could allow users to set a `format` attribute (`json-schema`, for example) on the rule to have it target JSON schema models.

**Comment by philsturgeon** [comment]
You can lint any files not just OpenAPI, it could be asyncapi, agithub actuon yaml Cole, anything at all. Where did this request come from?

**Comment by rossmcdonald** [comment]
@philsturgeon This is in the context of Spectral running within Studio. Isn't there a "format" designation set on rules based on which type of file they should be run against (ie, oas2, oas3)? Are there other formats that I'm just not aware of?

**Comment by rossmcdonald** [comment]
BTW I've also opened https://github.com/stoplightio/studio/issues/122 since I didn't know exactly where the change would be needed. If this is just in Studio then we can close this one. I wasn't sure if we needed to add support for a new file format type or not.

**Comment by philsturgeon** [comment]
AHA! Ok, so stuff will run against all formats by default. We added formats for oas2 and oas3 only so people could run certain rules on a specific version, but if you run a ruleset against a JSON Schema file it’ll work. I’m not sure what studio does with this.
