### ISSUE TITLE
Spectral Docker Develop Image - Module Not Found

### ISSUE THREAD

**Issue by drmmr763** [stoplightio/spectral#589]
**Describe the bug**
Attempting to use the linter provided by the Spectral docker image (https://hub.docker.com/r/stoplight/spectral) and getting a node "Module Not Found" error. This only seems to happen with the `develop` tag, which I am utilizing because I wanted to make use of the new Junit formatter (https://github.com/stoplightio/spectral/pull/519). 

**To Reproduce**

stoplight/spectral:latest (completes without error):
```
docker run -v "$(pwd):/app" stoplight/spectral:latest lint "/app/storage/api-docs/api-docs.json" --verbose --format=json --output="/app/api-violations.json" 
```

spotlight/spectral:develop (throws error):
```
docker run -v "$(pwd):/app" stoplight/spectral:develop lint "/app/storage/api-docs/api-docs.json" --verbose --format=junit --output="/app/api-violations.json"
```
Stacktrace
```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'tslint/lib/utils'
Require stack:
- /usr/src/spectral/dist/functions/schema.js
- /usr/src/spectral/dist/functions/index.js
- /usr/src/spectral/dist/spectral.js
- /usr/src/spectral/dist/cli/services/linter.js
- /usr/src/spectral/dist/cli/commands/lint.js
- /usr/src/spectral/dist/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/src/spectral/dist/functions/schema.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/spectral/dist/functions/schema.js',
    '/usr/src/spectral/dist/functions/index.js',
    '/usr/src/spectral/dist/spectral.js',
    '/usr/src/spectral/dist/cli/services/linter.js',
    '/usr/src/spectral/dist/cli/commands/lint.js',
    '/usr/src/spectral/dist/cli/index.js'
  ]
}

```

**Expected behavior**
I expected the linter command to complete without errors and populate the report in junit format. 

**Environment (remove any that are not applicable):**
 - Library version: Latest build published to DockerHub (https://github.com/stoplightio/spectral/tree/12ca287175001865235a9871e035b5a03540aff4)
 - OS: Host OSX, but running in Docker.

**Debugging Attempts**
* Tried to create a new dockerfile and add the required module myself in the build but was not successful.
* Googled the missing module and haven't found a clear source of the problem.

**Comment by XVincentX** [comment]
@drmmr763 Apparently we're using `tslint` in the production code — but it's listed as a devDependency which does not get installed in the docker container. We'll issue a fix very soon.

**Comment by drmmr763** [comment]
Hi @XVincentX I appreciate you working on a fix and getting it out real fast!

So, I tried it out. I see on dockerhub the develop image was rebuilt with this release:
Dockerhub Hash: `5a7afa9`

Git commit:
https://github.com/stoplightio/spectral/tree/5a7afa9d81c21ba1bb3dbc3734c532f40156f0c4

I rebuilt the image locally:
`docker build -f Dockerfile.spectral . -t spectral:develop`

My dockerfile:
```
FROM stoplight/spectral:develop
```

Docker images:
```
MBP386-0G8WN:teletherapy cwindnagle$ docker images | grep "spectral"
spectral                                    develop             2d1e9ec3b7c9        29 minutes ago      133MB
stoplight/spectral                          develop             2d1e9ec3b7c9        29 minutes ago      133MB
```

Then the run command:
```
docker run -v "$(pwd):/app" stoplight/spectral:develop lint "/app/storage/api-docs/api-docs.json" --verbose --format=junit --output="/app/api-violations.json"
```

And, I get the same error output as the stack trace above. (Re-pasted below just incase I missed something):

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'tslint/lib/utils'
Require stack:
- /usr/src/spectral/dist/formatters/junit.js
- /usr/src/spectral/dist/formatters/index.js
- /usr/src/spectral/dist/cli/services/output.js
- /usr/src/spectral/dist/cli/commands/lint.js
- /usr/src/spectral/dist/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/src/spectral/dist/formatters/junit.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/spectral/dist/formatters/junit.js',
    '/usr/src/spectral/dist/formatters/index.js',
    '/usr/src/spectral/dist/cli/services/output.js',
    '/usr/src/spectral/dist/cli/commands/lint.js',
    '/usr/src/spectral/dist/cli/index.js'
  ]
}
```

Did I miss a step somewhere?

**Comment by XVincentX** [comment]
It's working correctly for me; maybe you tried before the new image was uploaded on DockerHub?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1416224/65537948-93900d80-df06-11e9-9b2a-1f5ee6744a42.png">

**Comment by drmmr763** [comment]
Hi @XVincentX I see you didn't use the "develop" tag in your test. I am able to reproduce the error using develop tag on play-with-docker. maybe the tag isn't necessary? (Again, trying to get to the new junit parser to work which is unreleased atm). 

![image](https://user-images.githubusercontent.com/643104/65543525-4e0c1a00-dedf-11e9-9c9a-7f06e5b36822.png)

**Comment by XVincentX** [comment]
It turns out it's used in another part as well. #592

**Comment by drmmr763** [comment]
Thanks @XVincentX want to confirm after the new build its working! Thanks so much for this. I can now fully implement into our CI / CD.

**Comment by philsturgeon** [comment]
Junit is in v4.2.0-beta2 so you can npm install that. 😎

--
Phil Sturgeon
@philsturgeon
