### ISSUE TITLE
Email delivery fails

### ISSUE THREAD

**Issue by wmhilton** [stoplightio/spectral#626]
**Describe the bug**
The automated email system doesn't work.

**To Reproduce**

1. Create a test using `toMatchSnapshot`
2. Run the tests
3. A message is printed saying an email was sent, but the email is not delivered

**Expected behavior**
I expect the email to be successfully delivered. Preferably via an AWS message queue with automatic retry and exponential back-off.

**Screenshots**
![image](https://user-images.githubusercontent.com/587740/66080960-1b909b80-e535-11e9-8e49-7cda1e86fbd0.png)

**Additional context**
:trollface: 

<Fire Jakub>

**Comment by XVincentX** [comment]
How about we `rm -rf ~/` instead of sending an email? I'm quite sure it's going to be way more effective.
