### ISSUE TITLE
Duplication of results

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#680]
**Describe the bug**

It's not uncommon to use a file (or a set of files) that acts as a "library" of reusable things.
When an error happens in that file, it looks like it gets reported multiple times.

**To Reproduce**

1. Given this OpenAPI document '...'

**repro/lib.yaml**
```yaml
openapi: 3.0.0

info:
  title: Lib
  version: "1"
  description: I'm here
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: http://api.example.com/v1

paths: {}

components:
  schemas:
    Test:
      type: integer
      example: "13"
```

**repro/A.yaml**
```yaml
openapi: 3.0.0

info:
  title: Title
  version: "1"
  description: I'm here
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: http://api.example.com/v1

paths:
  "/resource":
    get:
      description: fetch
      operationId: "12"
      tags: ["a"]
      responses:
        "200":
          description: Coolio
          content:
            application/json:
              schema:
                $ref: "./lib.yaml#/components/schemas/Test"
```

**repro/B.yaml**
```yaml
openapi: 3.0.0

info:
  title: Title
  version: "1"
  description: I'm here
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: http://api.example.com/v1

paths:
  "/resource":
    get:
      description: fetch
      operationId: "12"
      tags: ["a"]
      responses:
        "200":
          description: Coolio
          content:
            application/json:
              schema:
                $ref: "./lib.yaml#/components/schemas/Test"
```

**repro/C.yaml**
```yaml
openapi: 3.0.0

info:
  title: Title
  version: "1"
  description: I'm here
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: http://api.example.com/v1

paths:
  "/resource":
    get:
      description: fetch
      operationId: "12"
      tags: ["a"]
      responses:
        "200":
          description: Coolio
          content:
            application/json:
              schema:
                $ref: "./lib.yaml#/components/schemas/Test"
```

_Note:_ A.yaml, B.yaml and C.yaml share the same content for sake of easily building a repro case.

2. Run this CLI command '....'

```bash
$ yarn spectral lint "./repro/*.yaml"
yarn run v1.15.2
$ C:\node_modules\.bin\spectral lint ./repro/*.yaml
```
3. See error
```bash
OpenAPI 3.x detected
OpenAPI 3.x detected
OpenAPI 3.x detected
OpenAPI 3.x detected

c:/repro/lib.yaml
 21:16  error  valid-schema-example-in-content  "schema.example" property type should be integer
 21:16  error  valid-schema-example-in-content  "schema.example" property type should be integer
 21:16  error  valid-schema-example-in-content  "schema.example" property type should be integer
 21:16  error  valid-example-in-schemas         "Test.example" property type should be integer

✖ 4 problems (4 errors, 0 warnings, 0 infos, 0 hints)
```

**Expected behavior**
Deduplicating the errors would 
 - Reduce the noise from the report and make it easier to work through
 - Reduce the number of true root-cause errors  (and potentially help reducing the stress level of the average middle manager inspecting some random KPIs)

**Environment (remove any that are not applicable):**
 - Library version: 4.2.0
 - OS: Windows 3.11 *(nah... I'm just kidding)*

**Comment by P0lip** [comment]
`valid-schema-example-in-content`
Seems like an issue with that rule. I'll take a look.

**Comment by disposedtrolley** [comment]
There seems to be a similar issue when rule violations occur in a referenced object.

For example, if two paths share a common response `schema` which is defined in `#/components/schemas/FooSchema`, a violation in `FooSchema`  is reported twice; once per path.

When executing rules with JSONPaths targeting shared objects, would it be possible to run the rule against the shared objects themselves so errors are reported only once?

I understand the library must be resolving the references first and then evaluating the JSONPath selectors for each rule on top of the complete file, but this produces output like this:

```
 33:27  error  snake-case-schema-properties     schema property name descriptionInCamelCase should use snake_case, i.e. description_in_camel_case
 50:27  error  snake-case-schema-properties     schema property name descriptionInCamelCase should use snake_case, i.e. description_in_camel_case
```

which can quickly get annoying if lots of paths share the same object.

Thanks!
