### ISSUE TITLE
Support for async custom functions?

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/spectral#694]
Is it possible to use async/promise-based libraries in custom functions? If not, is there a specific reason? And is there a way to work around this limitation?

**Comment by marklindell** [comment]
I too am interested in this support. I would like to use other libraries that require callbacks.

**Comment by P0lip** [comment]
@marklindell async functions should be supported soon.
Nothing is set in the stone yet, but hopefully you won't need to wait too long.
