### ISSUE TITLE
Write an example showing YAML to JSON

### ISSUE THREAD

**Issue by tbarn** [stoplightio/spectral#73]
### **I'm submitting a...**

feature request

### What is the expected behavior?

Have an example that clearly shows how to convert from YAML to JSON using https://github.com/stoplightio/yaml

### What is the motivation / use case for changing the behavior?

Make it easier to use specification files that are in YAML with Spectral

**Comment by paulapaulTW** [comment]
Hi Taylor - I was playing around with the examples in the README and had a question about what you were looking for in this issue.  If I have a YAML specification I can use the example in the README 'as is' if I assign the const myOAS to a snippet of my YAML specification as a template string (without converting to JSON) - are there some examples you are looking for where things are easier if you convert the YAML to JSON?  Let me know if I can lend a hand with this one - Paula
