### ISSUE TITLE
How to validate against single component, for example Schema?

### ISSUE THREAD

**Issue by naivefun** [stoplightio/spectral#803]
The .run API runs against complete spec, what if I'd like to validate only path item or schema? What's the API for that?

**Comment by P0lip** [comment]
@naivefun 
Hey! You have at least 2 choices.
The recommended way is to leverage Spectral rulesets and [create your own rule](https://github.com/stoplightio/spectral/blob/develop/docs/getting-started/rulesets.md#adding-a-rule).
The other, less recommended, way is to simply pass the object you'd like to lint to `run`.
Could you show me the piece of the document you are trying to lint?
I can help you come up with a rule.

**Comment by philsturgeon** [comment]
Seems like you got what you need @naivefun. Enjoy!
