### ISSUE TITLE
Help creating bundle run in Node JS and browser

### ISSUE THREAD

**Issue by oreshkin-ay** [stoplightio/spectral#846]
Trying to create bundle  format: 'umd'. It works in the browser. But gives an error message run node.
Config rollup:
![image](https://user-images.githubusercontent.com/17002069/70605369-6f8dbf80-1c0b-11ea-9b00-45c95226e5d7.png)
![image](https://user-images.githubusercontent.com/17002069/70605593-ddd28200-1c0b-11ea-8f8e-0cc13b30ae50.png)

**Comment by P0lip** [comment]
Hey! I'm going to address the nanoid issue today. AFAIR we don't need to generate secure ids, so it should be perfectly fine to use a plain math random.
This should fix the issue. 
Re the rollup setup - you may still need to keep it.

**Comment by P0lip** [comment]
I've just fixed the issue with nanonid. It's been released as 5.0.0-beta2. Feel free to check it out.
If you do need to stick to v4.2.x for the time being, try aliasing `nanoid` module to `nanoid/non-secure`.
