### ISSUE TITLE
Help install local package

### ISSUE THREAD

**Issue by oreshkin-ay** [stoplightio/spectral#851]
I download zip. Then unzip at my project. Run "npm install spectral-develop". 
![image](https://user-images.githubusercontent.com/17002069/70687952-a9210200-1cc1-11ea-8056-f98755c4543f.png)

![image](https://user-images.githubusercontent.com/17002069/70687899-7c6cea80-1cc1-11ea-9028-8a5e8554f73c.png)

If running npm install  @stoplight/spectral, it works. I want install v5.0.0-beta2 in the same way.

**Comment by P0lip** [comment]
@oreshkin-ay 
You can specify the version, like so `npm install @stoplight/spectral@5.0.0-beta2`.

**Comment by oreshkin-ay** [comment]
Thank you very match

**Comment by P0lip** [comment]
@oreshkin-ay Can I consider the ticket resolved? :)

**Comment by oreshkin-ay** [comment]
@P0lip I have new problem :(
![image](https://user-images.githubusercontent.com/17002069/70736873-51ff4980-1d22-11ea-846d-fb929700395d.png)
Can you help me build format: 'umd'?
