### ISSUE TITLE
Spectral's IRuleResult an IPosition reference which is always null

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/spectral#92]
Spectral's `IRuleResult` interface which is the type returned from the validation process extends `IValidationResult` which has a nullable position reference.

While it is correct — Spectral does not have (yet?) the ability of generating the position information — these are up to the caller.

In order to reduce the confusion (which I personally had) it would be better to simply make sure such interface does not have that property at all.

**Comment by P0lip** [comment]
The issue can be closed as soon as Spectral 2.0 is released.

**Comment by XVincentX** [comment]
Ok cool.
