### ISSUE TITLE
Make Windows contributors' experience a bit nicer!

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#921]
As noted in https://github.com/stoplightio/spectral/pull/775#discussion_r347605034 there's no longer any feedback from a Windows based CI server.

#919 puts under the light that contributing to Spectral from a Windows environment isn't the sweetest experience.

Would it be possible to setup a Windows based CI-server to ensure xplat consistency for pull request (whether they're issued by a Spectral core team member or an external contributor)?

/cc @m-mohr

**Comment by philsturgeon** [comment]
Let's chat about this over on #919 so we've not got two similar sounding issues. I keep clicking the wrong one. :D
