### ISSUE TITLE
Builtin casing.pascal doesn't allow abbreviations

### ISSUE THREAD

**Issue by bkabrda** [stoplightio/spectral#926]
**Describe the bug**

The builtin pattern for matching `casing.pascal` doesn't allow abbreviations. E.g. `MyHTTPResponse` is considered invalid.

**To Reproduce**

Try to validate a string value `MyHTTPResponse` against `casing.pascal`.

**Expected behavior**

Validation passes.

**Environment (remove any that are not applicable):**

Using Docker image stoplight/spectral:5 (image id 38270ed7d5da).

**Additional context**

Perhaps there could be a `functionOptions` option added to allow for this in order to preserve backwards compatible behavior.

**Comment by philsturgeon** [comment]
This is one of the longest standing arguments in programming other than tabs vs spaces: naming things, and particularly what to do about abbreviations. 

A lot of people say the correct way to handle abbreviations is to treat them as a word, so `MyHttpResponse` would be "correct". node-change-case agrees with this, and we follow the same rules as that. 

I certainly don't want to say anyone is right or wrong here, its tabs vs spaces, but we do need to pick one and some consensus seems to exist around this approach. If we keep tacking more and more options into this function I worry it'll get a bit rough to test, so... I dunno what to suggest.

Any chance you like the look of `MyHttpResponse` better and are happy to consider it a feature not a bug? :D

**Comment by bkabrda** [comment]
@philsturgeon thanks for the response. I totally understand your concern with bloating the options field. Our team really needs to have abbreviation all-caps for *reasons*. For now we're just using `"[A-Z][A-Za-z0-9]*"` to check PascalCase which I guess is good enough for us. We can definitely keep doing that if you don't want to consider adding the option (but obviously we'd prefer if you did add the option :)).

**Comment by philsturgeon** [comment]
Ok, we'll have to leave you with the regex approach for now @bkabrda. If more folks start requesting this, or a PR appears, we can look into it.
