### ISSUE TITLE
Spectral's IRuleResult is missing the summary property…

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/spectral#93]
which has a way better description of the validation error than message and title. I discovered this while debugging the piece of software and we should investigate whether it's a leftover and it should be added — or maybe deleted.

**Comment by philsturgeon** [comment]
Can you confirm if this is still an issue in the release/2.0 branch? #104 might have fixed it.

**Comment by XVincentX** [comment]
Yeah I believe we can close this, it's not relevant anymore.
