### ISSUE TITLE
The sample validation does not support null in samples

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/spectral#989]
The new sample validation does not support null values, that are perfectly legitimate for non required attributes.
Thus, many errors are now reported, which greatly complicates the use of this validation.

For example :
* model
![image](https://user-images.githubusercontent.com/20415788/73830442-fb375d00-4804-11ea-8990-44fc2f8f3314.png)
* sample
![image](https://user-images.githubusercontent.com/20415788/73830203-8bc16d80-4804-11ea-9f92-e0955539a1f5.png)
* invalid reported issue in sample: 
![image](https://user-images.githubusercontent.com/20415788/73830245-a09e0100-4804-11ea-9673-a64eb1fa1bed.png)

The problem is only with the 'standard' OAS samples, not with the Spotlight extension:
![image](https://user-images.githubusercontent.com/20415788/73830341-d17e3600-4804-11ea-8186-d7564d942b40.png)
No error reported here.

**Comment by nulltoken** [comment]
>that are perfectly legitimate for non required attributes.

@john-doe-2016 :wave: Could you please share a link to the part of the spec that refer to this?

My understanding of the [OAS 3.0.x spec](http://spec.openapis.org/oas/v3.0.3#fixed-fields-19) is that `null` isn't supported. However, it supports the `nullable` modifier.

Also relevant: https://stackoverflow.com/a/48114322/335418

**Comment by nulltoken** [comment]
@john-doe-2016 Closing this for now. Would you have more to share, please add some comments so that we can revisit this.
