### ISSUE TITLE
Unable to install npm package

### ISSUE THREAD

**Issue by zeke** [stoplightio/spectral#990]
Hi @P0lip, @rossmcdonald, and the rest of the maintainers 👋 

I'm unable to install this package from npm:

```
$ npm i @stoplight/spectral
npm ERR! Unexpected end of JSON input while parsing near '...bbUxpr2zZ5vL4G5HpDno5'
```

The log indicates it's actually an issue with the transitive `immer` dependency, which is a dependency of `@stoplight/json-ref-resolver@3.0.8`.

I've opened an issue here: https://github.com/immerjs/immer/issues/546

**Comment by P0lip** [comment]
Hey.
I'm sorry to hear you're having troubles installing Spectral.
I tried installing it using both npm and yarn, and both installations completed successfully.
Could you try clearing the npm cache?
`npm cache clean --force` 
Perhaps the cache entered some weird state.
Let me know how it goes.

**Comment by zeke** [comment]
`npm cache clean --force` did the trick. Thank you, @P0lip ✨

**Comment by P0lip** [comment]
Awesome, glad to hear.
Shall you have any other troubles, don't hesitate to reach out.
